src/bin/bindgen.rs, src/lib.rs, src/parser.rs
=> parser: Disable conditionally class constants

src/clang.rs, src/clangll.rs, src/parser.rs
=> Add support for elaborated types.

Cargo.toml, src/bin/bindgen.rs, src/gen.rs, src/lib.rs
This is on top of #10 because they conflicted, yet I needed clang-sys for one of the tests.
r? @nox
=> Update syntex and use clang-sys for path-searching

.gitignore, src/bin/bindgen.rs, src/clang.rs, src/gen.rs, src/lib.rs, src/parser.rs
This adds support for generating MSVC bindings, using clang's MSVC C++ ABI support.  It requires a command line flag for selecting this binding due to an inability to pick up the msvc target triple.
=> Add support for generating MSVC bindings (using clang)

Cargo.toml
To include the fix for Windows build.
=> Bump clang-sys version to 0.8.0

src/gen.rs, src/parser.rs, src/types.rs
This allows making type aliases to be blacklisted.
=> Allow blacklist typedef

README.md
=> Expand the build instructions when using llvm 3.9

src/bin/bindgen.rs
=> Append the input header to the end of the clang args, instead of the front

src/bin/bindgen.rs, src/parser.rs
The -isystem stuff fixes issue #53.
Stripping leading _ on Windows is weird; it needs to not be stripped on MSVC (leading @), but on gcc at one point it needed to be.  But now it no longer does.  I don't know.  'cargo test' succeeds with mozjs bindings generated with these fixes.
=> Skip -isystem stuff if --target is specified, and don't strip leading _ on Windows

Cargo.toml, src/codegen/helpers.rs, src/codegen/mod.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/item.rs, src/ir/ty.rs, tests/tools/run-bindgen.py
Built on top of #58, this adds support for untagged unions if not running under the `--no-unstable-rust-flag`.
The last commit is an example try run passing with this, but should be reverted (and the `--no-unstable-rust` flag passed by default to our harness).
This depends on https://github.com/serde-rs/aster/pull/109.
r? @nox
=> Union support

src/clang.rs, src/ir/function.rs
Not sure whether it is the right thing to do.
=> Avoid mangling name for tpl class member. Fix #68

src/lib.rs
I switched to the consuming builder pattern, as that seemed the easiest, and ditched the phantom markers while I was at it.
=> Fix lifetime issues with buildgen::builder()

tests/tools/run-bindgen.py
Python style (PEP8) is 4 space indentation, and you'll be hard pressed
to find anything else in the python community. We should match up with
expectations, editor defaults, etc.
r? @emilio
=> Use 4 space indentation in run-bindgen.py

tests/headers/class_with_typedef.hpp, tests/tests.rs, tests/tools/run-bindgen.py
See individual commit messages for details.
Fixes #97
r? @emilio
=> More testing and test infrastructure stuff

src/codegen/mod.rs, src/ir/comp.rs, tests/expectations/class.rs, tests/expectations/const_tparam.rs, tests/headers/class.hpp, tests/headers/const_tparam.hpp
We signal method constness in the `this` pointer creating a `const` pointer, but the `to_rust_ty` implementation never checked that.
=> Take pointer constness into account, to fix generation of const methods.

src/lib.rs
We don't support match patterns anymore.
r? @emilio
=> Remove `match_pat` options and builder methods

src/clang.rs
Hi, tried to fix the issue mentioned. Not sure, if changing fn args makes sense (the err message probably doesn't...). cargo test --features llvm_stable was succesful.
- changed output of fn num_args to option<u32>
- changed fn args to handle option<u32> instead of usize
=> fix: clang::Cursor::num_args should return Option<u32> #132

src/clang.rs, src/ir/context.rs
Changed the potentially null pointer to an Optional.
The caller previously assumed the pointer was always valid and not null, so I called `expect` to make it fail early if it isn't.
Fixes #144.
=> #144 Changed `clang::TranslationUnit::parse` to return an Option

src/ir/annotations.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/enum_ty.rs, src/ir/function.rs, src/ir/int.rs, src/ir/item.rs, src/ir/item_kind.rs, src/ir/layout.rs, src/ir/module.rs, src/ir/ty.rs, src/ir/var.rs, src/lib.rs, src/parse.rs
=> Document the `ir` module

src/ir/item.rs, src/lib.rs, src/parse.rs
=> Document the `parse` module

src/ir/ty.rs, src/ir/var.rs
This should fix #160.
r? @emilio
=> Use safe_canonical_type for parse time

tests/tests.rs
When running all the test in parallel, all the memory on my laptop
is consumed by rustc processes, my machine become unusable and the
tests do not make progress.
It seems to make sense to have serial by default, as the number of
process depends on the number of test files.
To run the test in parallel:
RUN_TEST_PARALLEL=1 cargo test --feature llvm_stable
This is a first approach at this issue, I'm still really new to rust.
I was trying to run the test for an easy fix, but it was killing my machine.
Ideally it would have been nice to be able to control exactly how many
process to run in parallel, maybe using chunks somewhere. I could try
to see if I can work it out if it would be a better solution.
=> Run test in serial by default to not take all memory

src/clang.rs, src/ir/annotations.rs
=> Check bounds when calling Comment::get_child (fix #142)

src/clang.rs, src/ir/ty.rs
=> Change clang::Type::num_elements to return Option

src/clang.rs, src/ir/function.rs, src/ir/ty.rs
=> Return Option<Type> in clang::Type::ret_type fix #141

src/clang.rs, src/ir/annotations.rs
=> 143 comment get tag attr

src/clang.rs, src/ir/annotations.rs
=> Use iterators for comment children and attributes fix #166

src/clang.rs, src/ir/comp.rs, src/ir/ty.rs
=> clang::Type::num_template_args return Option<u32> fix #135

src/ir/item.rs, src/ir/ty.rs, src/lib.rs
=> Be less noisy about known to be unimportant errors.

.travis.yml, tests/tests.rs
This makes `cargo test` test the appropriate release/debug bindgen binary and extends Travis CI testing to also test release builds.
r? @emilio
=> Run tests on release builds

src/codegen/mod.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/function.rs, src/ir/item.rs, src/ir/mod.rs, src/ir/ty.rs, src/ir/type_collector.rs
This commit move the `TypeCollector` trait out from the `codegen` module and into its own submodule in `ir::type_collector`. Additionally, it puts the various `TypeCollector` trait implementations next to the types that each implementation is for.
I'm going to start using this trait outside of codegen, and I think it makes more sense in `ir` since it is implemented by `ir` types and is all about `ir` things.
r? @emilio
=> Move the `TypeCollector` trait to the `ir` module

src/ir/function.rs
This has hit @Manishearth today.
r? @fitzgen
=> Fix empty mangling handling on OSX

src/clang.rs, src/ir/ty.rs
Fixes #138 
Since I am new to Rust, I hope I didn't do things too badly
=> Fix for #138 : rework for elem_type() which now returns Option<Type> instead of Type

src/clang.rs, src/ir/comp.rs, src/ir/ty.rs
Fix #136 by providing a bound checked iterator replacing the interface.
=> clang::Type::template_args return Option<TypeTemplateArgIterator>

src/clang.rs
Now, functions calling Cursor::num_template_args() call expect() on the return value to make sure it is a valid value
=> Fix #121: Cursor::num_template_args(...) returns Option<u32> instead of c_int

tests/headers/class_with_typedef.hpp, tests/tools/run-bindgen.py
The only difference in bindings is because the methods were inlined, so with
llvm 3.9 we can skip those.
=> tests: Get rid of feature-specific tests.

src/codegen/mod.rs, src/ir/context.rs, tests/expectations/type_alias_empty.rs, tests/tools/run-bindgen.py
I'm going to re-use this stuff, plus I think it is way more understandable when pulled out of `codegen`.
This did have the unfortunate consequence of changing iteration order of types, resulting in different anonymous bindgen names for things like unions and such. We *could* sort the whitelisted item set before codegen to alleviate this kind of thing in the future, but I'm not sure it is worth the extra overhead...
r? @emilio
=> Factor out the collection and traversal of the transitive closure of whitelisted items

src/ir/context.rs
`insert()` returns `true` if the item was *not* in the set before, so we can use that to avoid a double lookup.
r? @emilio
=> Avoid an extra lookup when finding new whitelisted items to traverse

src/clang.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/enum_ty.rs, src/ir/function.rs, src/ir/item.rs, src/ir/module.rs, src/ir/ty.rs, src/ir/var.rs, src/lib.rs
It has always been a mess.
r? @fitzgen
=> clang: Simplify visiting code.

src/clang.rs, src/ir/comp.rs
=> Make clang::Cursor::specialized return an Option

README.md
The scripts were moved in
https://github.com/servo/servo/pull/13372
=> Fix link to stylo script in README.md

src/bin/bindgen.rs, src/clang.rs, src/ir/item.rs, src/lib.rs
While running `cargo fmt` for my PR I realized that other files were touched.
=> Some cargo-fmt corrections.

src/clang.rs
Well apparently nobody is using  `Cursor::ret_type` 😢
=> Make clang::Cursor::ret_type return an Option<Type> — Fixes #131

src/clang.rs, src/ir/item.rs
Fixes #123
Paired with @glasserc
=> clang::Cursor::definition should return Option<clang::Cursor>

src/ir/context.rs, src/ir/item.rs
See individual commit messages for details.
r? @emilio
=> Dangling item id in partial specializations

src/ir/item.rs
r? @emilio 
We walk the expanded code already. These cursors are children of the translation unit for some reason, and let you iterate over tokens from before the macro was expanded. Pretty safe to ignore here.
=> Don't be loud about ignoring macro expansion cursors

.travis.yml, ci/before_install.sh
Adds 3.9 builds and macOS builds.
Clang is installed from llvm.org instead of installed from `apt-get`/`brew` (this is significantly faster, especially on macOS because brew is really slow).
=> Rework CI and add macOS builds

src/clang.rs, src/ir/ty.rs
=> change return value of Type::pointee_type() to Option<Type>

src/clang.rs
=> Added checks for clang::Cursor::template_arg_value

src/clang.rs, src/ir/enum_ty.rs
Also reorganize calling code to avoid duplicate checking of cursor type.
Fixes #127
=> Wrap enum_val_signed in an Option.

src/clang.rs, src/ir/enum_ty.rs
Patterned after the changes merged in #220.
Fixes #128
=> Wrap enum_val_unsigned in an Option

src/clang.rs
This PR fixes #120 . `clang::Cursor::semantic_parent` now just calls `clang::Cursor::fallible_semantic_parent`, and the ffi call has been moved into `fallible_semantic_parent`.
This change broke a number of tests which call `is_toplevel()` (which itself calls `semantic_parent()`):  
> panicked at called Option::unwrap() on a None value
So I re-wrote `is_toplevel()` to call `fallible_semantic_parent()`, which returns an `Option<Cursor>` type instead.
=> Make clang::Cursor::fallible_semantic_parent make ffi call

src/clang.rs, src/ir/item.rs, src/ir/ty.rs
Needed `is_valid()` when debugging, so figured we should land this and update places where we compare against the magical sentinel value.
r? @emilio
=> Add `clang::Type::is_valid` and use it instead of checking self.kind() against CXType_Invalid

src/codegen/mod.rs, tests/expectations/tests/use-core.rs, tests/headers/use-core.h
r? @fitzgen, @nox or anyone else?
=> Fix --use-core for functions, since we used the aster helper.

Cargo.toml, src/bin/bindgen.rs, src/bin/options.rs, src/lib.rs
In progress port to `clap`, obsoletes the `docopt` port in servo/rust-bindgen#202.
=> Clap your hands say yeah! 👏🏻

CONTRIBUTING.md
This commit extends CONTRIBUTING.md with information on how to use
`creduce` to minimize input header test cases that cause `bindgen` to
panic, generate bad bindings, or any other incorrectness.
r? @emilio
=> Describe how to use `creduce` with `bindgen`

.travis.yml, ci/before_install.sh
The wait time to get OSX machines on Travis CI is *way* too long at the
moment. We'll be able to revert this commit in the future, once Travis
CI adds more OSX machines to their cluster, hopefully.
r? @emilio
=> Disable OSX builds on Travis CI

src/clang.rs, src/ir/ty.rs
Fixes https://github.com/servo/rust-bindgen/issues/124
Since I am new to Rust, I hope I didn't do things too badly
=> clang::Cursor::referenced should return Option<clang::Cursor>

src/bin/bindgen.rs
r? @fitzgen
Too bad we can't test it on CI because CI has the path correctly setup :(
Fixes #242
=> Fix path detection after #228

src/codegen/helpers.rs, src/codegen/mod.rs, tests/expectations/tests/enum_explicit_type.rs, tests/expectations/tests/macro-expr-basic.rs, tests/headers/enum_explicit_type.hpp, tests/headers/macro-expr-basic.h
Proper fix on aster soon, still worth to get this in I guess.
r? @fitzgen
=> codegen: Special-case i64::MIN since it produces a overflow on aster.

src/ir/item.rs
When we fail to parse Clang stuff into our IR and give up, and assume
that we are looking at a named template type, we now emit a warning to
assist with debugging.
r? @emilio
=> Warn when giving up and assuming a named type

src/ir/comp.rs, src/ir/function.rs, src/ir/item.rs, src/ir/ty.rs
Rather than making `TypeCollector` implementations recursively call
`collect_types` on their subtypes, just gather immediate subtypes into
the `ItemSet`. The subtypes' `TypeCollector` implementation will be
recursively called by `WhitelistedItemsIter`. This makes it less likely
we will "skip" a layer by recursively calling `collect_types` on
some subtypes without adding the subtypes themselves to the set.
r? @emilio
=> Clean up TypeCollector implementations

src/codegen/mod.rs, tests/expectations/tests/anon_union.rs, tests/expectations/tests/class.rs, tests/expectations/tests/class_with_inner_struct.rs, tests/expectations/tests/jsval_layout_opaque.rs, tests/expectations/tests/struct_with_anon_union.rs, tests/expectations/tests/struct_with_anon_unnamed_union.rs, tests/expectations/tests/struct_with_nesting.rs, tests/expectations/tests/typeref.rs, tests/expectations/tests/union_dtor.rs, tests/expectations/tests/union_fields.rs, tests/expectations/tests/union_template.rs, tests/expectations/tests/union_with_anon_struct.rs, tests/expectations/tests/union_with_anon_struct_bitfield.rs, tests/expectations/tests/union_with_anon_union.rs, tests/expectations/tests/union_with_anon_unnamed_struct.rs, tests/expectations/tests/union_with_anon_unnamed_union.rs, tests/expectations/tests/union_with_big_member.rs, tests/expectations/tests/union_with_nesting.rs, tests/headers/union_with_big_member.h
Our debug-detection code assumes so.
Fixes #246
r? @fitzgen
=> codegen: Always implement debug for __BindgenUnionField.

src/ir/context.rs
This adds `debug!` logging for all paths that insert items into
`BindgenContext::items`, and adds some `debug_assert!`s against dangling
`ItemId`s.
r? @emilio
=> Add more logging for item insertion and asserts

.travis.yml, libbindgen/src/codegen/mod.rs, libbindgen/src/lib.rs, src/options.rs
Similar to our ability to emit the clang AST, this adds an option to
emit our IR for debugging purposes.
This can wait to land until after #204 is merged.
r? @emilio
=> Add an option to emit our ir for debugging

libbindgen/src/clang.rs, libbindgen/src/codegen/mod.rs
Little things. See commit messages for details.
r? @emilio
=> Little logging things

.travis.yml
Another fix to greatly improve test suite turnaround times.
=> Avoid superfluous repeated builds on Travis

libbindgen/Cargo.toml, libbindgen/src/lib.rs, libbindgen/src/log_stubs.rs, libbindgen/tests/tests.rs
Note that the log crate isn't completely banished, as other is required by other dependencies.
Believe it or not, this change was the original aim of #204.
=> libbindgen: Make logging optional

libbindgen/Cargo.toml
This is not the latest version, because the latest version doesn't work
due to serde-rs/quasi#65.
The issue of keeping using 0.20 is that libbindgen depends on aster 0.28
while quasi depends on aster 0.27, which leads to duplicate versions of
aster dependency. Updating quasi to 0.21 brings aster to 0.29, which
also works for libbindgen.
=> Update quasi to 0.21

libbindgen/src/codegen/mod.rs, libbindgen/src/ir/int.rs, libbindgen/src/ir/item.rs, libbindgen/src/ir/ty.rs, libbindgen/src/ir/var.rs, libbindgen/tests/expectations/tests/constant-evaluate.rs, libbindgen/tests/headers/constant-evaluate.h
Partially addresses #274 until my patch or a similar one gets accepted and we can use it.
r? @fitzgen or @upsuper
=> ir: Avoid generating out-of-range values in constants.

libbindgen/src/ir/item.rs
The assertion that the template alias's inner type was our name target,
and that we didn't need to recurse, is failing when generating
SpiderMonkey bindings. I'm not 100% sure when this can happen, but
clearly it can, and it is easy to support, so let's support it.
r? @emilio
=> Recurse on the inner type when finding a template alias name target

libbindgen/src/codegen/mod.rs, libbindgen/tests/expectations/tests/anon_union.rs, libbindgen/tests/expectations/tests/class_with_dtor.rs, libbindgen/tests/expectations/tests/crtp.rs, libbindgen/tests/expectations/tests/template.rs
This should generate tests for fully specialized templates.
TODO:
r? @emilio
=> First steps to fix issue #57

libbindgen/src/clang.rs, libbindgen/src/ir/enum_ty.rs
Returning an Option<Type> relieves callers from having to check whether clang::Cursor::enum_type returns `CXType_Invalid`.
Fixes #125
=> clang::Cursor::enum_type should return an Option<Type>

README.md
These were deleted accidentally in 073b12ff35a8ec6314d655804915f177ce453227.
=> Restore links in README.md

libbindgen/src/ir/context.rs, libbindgen/src/ir/item.rs
Some of these changes are still under the question but I guess it's how @fitzgen describe it in issue #201.
=> Unify naming methods into a single method + options builder type

libbindgen/src/codegen/mod.rs, libbindgen/tests/expectations/tests/duplicated-namespaces-definitions.rs, libbindgen/tests/expectations/tests/duplicated-namespaces.rs, libbindgen/tests/expectations/tests/duplicated_constants_in_ns.rs, libbindgen/tests/expectations/tests/module-whitelisted.rs, libbindgen/tests/expectations/tests/namespace.rs, libbindgen/tests/expectations/tests/nested_within_namespace.rs, libbindgen/tests/expectations/tests/template_alias_namespace.rs, libbindgen/tests/expectations/tests/whitelist-namespaces-basic.rs, libbindgen/tests/expectations/tests/whitelist-namespaces.rs
We previously generated uses of the root module with absolute paths:
use root;
However this only works if the generated bindings are the root of the
crate. If they were in some submodule then that path would not be
valid. They are now generated relative to the current module, like this:
use self::super::super::root;
Fixes #96
r? @emilio
=> Use the generated root module via a relative path

libbindgen/src/ir/item.rs
In non-release builds with debug assertions, keep track of the set of
`ItemId`s that we have iterated over in `ItemAncestorsIter` and make
sure that we don't reach an ancestor we have already yielded, which
would trigger an infinite loop.
=> Assert that we won't infinite loop

libbindgen/src/codegen/mod.rs, libbindgen/src/lib.rs, src/options.rs
This unifies options and is more flexible.
I'd prefer to do the `bitflags!` thing as a followup, because airport WiFi (it could be an E-Easy).
r? @fitzgen
=> Add an API to decide what gets generated more granularly.

libbindgen/build.rs
Recent versions of Cargo seems to not provide $OUT_DIR and some other environment variables anymore when building build scripts.
CC @upsuper
=> Use std::env::var instead of env! in build srcipt

libbindgen/src/codegen/mod.rs, libbindgen/tests/expectations/tests/anon_union.rs, libbindgen/tests/expectations/tests/class_with_dtor.rs, libbindgen/tests/expectations/tests/crtp.rs, libbindgen/tests/expectations/tests/template.rs
=> codegen: generate stable names for tests functions.

libbindgen/Cargo.toml
It seems #322 doesn't upgrade the clang-sys of libbindgen, so bindgen is using two different versions of clang-sys. We should fix it.
r? @emilio
=> Upgrade clang-sys in libbindgen

libbindgen/src/ir/item.rs
For toplevel operator overload, and for `CXCursor_UsingDirective`
=> Silence the 'Unhandled cursor kind' warning for a few things

bindgen/Cargo.toml, libbindgen/Cargo.toml, libbindgen/src/clang.rs, libbindgen/src/ir/ty.rs, libbindgen/src/lib.rs
It's a pity that we don't support clang 3.7 and similar for generating C
bindings, when it should be straight-forward.
This change should allow us to support older clang versions, and also 
experiment with pre-release clang APIs if needed.
This depends on: https://github.com/KyleMayes/clang-sys/pull/44
=> [rfc] Use a dynamically loaded clang to do as much as we can with old clang versions, and experiment with new ones.

libbindgen/src/ir/context.rs
So I think this is it? Fix issue #209 
r? @fitzgen
=> Add assert for dangling references without an associated ItemId

.travis.yml, libbindgen/Cargo.toml, libbindgen/src/ir/context.rs
These checks are expensive enough that we only want to do them when hacking on
bindgen itself, not anytime someone does a debug build of something that depends
on bindgen.
r? @emilio
=> Use a feature to control dangling item assertions

libbindgen/src/clang.rs, libbindgen/src/ir/ty.rs
=> Wrap Type into Option

libbindgen/src/clang.rs, libbindgen/src/codegen/mod.rs, libbindgen/src/ir/annotations.rs, libbindgen/src/ir/comp.rs, libbindgen/src/ir/enum_ty.rs, libbindgen/src/ir/function.rs, libbindgen/src/ir/item.rs, libbindgen/src/ir/ty.rs, libbindgen/src/lib.rs
See the first commit for details.
Second commit is just `cargo fmt`.
r? @emilio
=> Only load libclang once, and don't unload it

README.md
There are several changes:
* Announce that Clang 3.9 is the new default
* Update the install steps for 3.9
* Add installing steps for Windows
* Update stylo's usage of bindgen
=> Update README.md to reflect the current situation

libbindgen/Cargo.toml, libbindgen/src/lib.rs, libbindgen/src/regex_set.rs
Rather than implementing a private RegexSet, implement it in terms of regex::RegexSet,
which should be more efficient. Retain the existing RegexSet module and just reimplement
its internals, in order to preserve the external API.
=> Update to regex 0.2; use regex::RegexSet for matching

bindgen-integration/cpp/Test.h, libbindgen/Cargo.toml, libbindgen/src/codegen/helpers.rs, libbindgen/src/codegen/mod.rs, libbindgen/src/ir/context.rs, libbindgen/src/ir/ty.rs, libbindgen/tests/expectations/tests/anon_enum.rs, libbindgen/tests/expectations/tests/bitfield_method_mangling.rs, libbindgen/tests/expectations/tests/inherit_typedef.rs, libbindgen/tests/expectations/tests/reparented_replacement.rs, libbindgen/tests/expectations/tests/union_fields.rs, libbindgen/tests/expectations/tests/unknown_attr.rs, libbindgen/tests/headers/anon_enum.hpp
=> codegen: Prefer use instead of type aliases.

CONTRIBUTING.md, README.md
Use the `doctoc` program to generate tables of contents, stop referring
to forking and make this the canonical `bindgen`, move the section on
building to last.
r? @emilio
=> Clean up the README.md and CONTRIBUTING.md docs

.gitignore, Cargo.lock, Cargo.toml
=> Version bump, ignore expectations' Cargo.lock

Cargo.lock, Cargo.toml
This avoids compiling two versions of some crates, which hopefully fixes tidy errors for https://github.com/servo/servo/pull/15216.
=> Update quasi_codegen to 0.29

.gitignore
The leading ./ breaks git, apparently. At least, they were still showing up as untracked files when I did git status.
r? @emilio or @Yamakaky
=> Fix .gitignore and extra crates' Cargo.lock files

Cargo.lock, Cargo.toml, src/codegen/mod.rs
This fails under BaseErrorResult in Stylo builds.
I have no idea right now why that isn't whitelisted (should be, given we're
calling it from TErrorResult's code generation).
Let's disable this pending further investigation since I don't have time to dig
into it right now.
r? @fitzgen
=> Remove recently-added assertion that can legitimately trigger

src/codegen/mod.rs, src/ir/ty.rs, tests/expectations/tests/class.rs, tests/expectations/tests/var-tracing.rs, tests/headers/class.hpp
=> treat incomplete array as zero length array

bindgen-integration/cpp/Test.cc, bindgen-integration/cpp/Test.h, bindgen-integration/src/lib.rs, src/codegen/mod.rs, tests/expectations/tests/class.rs, tests/headers/class.hpp
Turns out they were broken before
https://github.com/servo/rust-bindgen/issues/456.
Let's test it so it doesn't regress.
r? @fitzgen
=> tests: Add an integration test for static arrays.

src/codegen/mod.rs, src/ir/item.rs, src/ir/ty.rs
=> ir: Cleanup name duplication in aliases and named types.

.travis.yml, ci/before_install.sh
This reverts commit fc38f9b18a9dacc76b7e8a5c8633f0f02289daae.
r? @fitzgen
=> Re-enable OSX builds on Travis CI

src/clang.rs
This commit extends our existing Clang AST dumping to include more information,
such as a cursor's canonical, referenced, and declarations cursors if they
exist. It prints out most of the information that libclang gives us directly,
but not the information that we attempt to (re)construct on top of the libclang
APIs.
r? @emilio or @Yamakaky
=> Enhance Clang AST dumping

Cargo.lock, Cargo.toml, src/clang.rs, src/ir/ty.rs
=> Fix a recent template-specialization-related regression.

src/chooser.rs, src/clang.rs, src/codegen/mod.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/enum_ty.rs, src/ir/function.rs, src/ir/item.rs, src/ir/layout.rs, src/ir/module.rs, src/ir/objc.rs, src/ir/ty.rs, src/ir/type_collector.rs, src/ir/var.rs, src/lib.rs, src/main.rs, src/options.rs, src/regex_set.rs, tests/tests.rs
It's been a while, and we have a lot of reformatting with the latest version of `rustfmt`.
=> Run `cargo fmt`

.travis.yml, CONTRIBUTING.md, ci/assert-docs.sh, ci/assert-no-diff.sh, ci/assert-rustfmt.sh, ci/test.sh, src/chooser.rs, src/clang.rs, src/codegen/mod.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/enum_ty.rs, src/ir/function.rs, src/ir/item.rs, src/ir/layout.rs, src/ir/module.rs, src/ir/objc.rs, src/ir/ty.rs, src/ir/type_collector.rs, src/ir/var.rs, src/lib.rs, src/main.rs, src/options.rs, src/regex_set.rs, tests/tests.rs
=> Assert that code is properly `rustfmt`ed in CI

src/clang.rs, src/codegen/mod.rs, src/ir/function.rs, src/ir/objc.rs, tests/expectations/tests/objc_method.rs, tests/headers/objc_method.h
Welp, I attempted to get the method arguments working.
I must confess, that I have not ran this against actual objective c code yet though.
=> objc: Support method arguments

src/chooser.rs, src/lib.rs, src/main.rs, src/options.rs, tests/tests.rs
Fixes #50 
- Adds a `catch_unwind` to catch panic at binding generation. 
- Prints out a more detailed message that points to the potential misuse of flags, when `generate()` fails.
- Added false-by-default `verbose` option flag to specify whether detailed message should be printed for the time being
r? @emilio
=> Added catch_unwind to catch panic at generator

src/codegen/struct_layout.rs
fast workaround to fix issue #493
need to investigate why layout is empty
=> check empty layout when padding bytes

src/codegen/helpers.rs, src/codegen/mod.rs, tests/expectations/tests/use-core.rs, tests/headers/use-core.h
=> codegen: Fix remaining cases of missing core prefix.

.travis.yml, CONTRIBUTING.md, Cargo.toml, bindgen-integration/Cargo.toml, src/main.rs, tests/tests.rs
Fixes: https://github.com/servo/rust-bindgen/issues/409
=> Rename llvm_stable feature and remove references from docs.

src/clang.rs, src/codegen/mod.rs, src/ir/comp.rs, src/ir/ty.rs, tests/expectations/tests/class_nested.rs, tests/expectations/tests/layout_array.rs, tests/expectations/tests/layout_cmdline_token.rs, tests/expectations/tests/layout_mbuf.rs, tests/expectations/tests/struct_containing_forward_declared_struct.rs, tests/expectations/tests/template.rs, tests/headers/class_nested.hpp
=> ir: Don't parse non-semantic-children cursor as inner structs.

src/ir/item.rs, src/ir/mod.rs, src/ir/named.rs, src/ir/traversal.rs
This is just landing the initial analysis, and does not start leveraging this analysis's results instead of using the `Item::signature_contains_named_type` method yet.
r? @emilio
=> Discover which template type parameters are actually used

CONTRIBUTING.md, src/codegen/mod.rs, src/ir/context.rs, src/ir/item.rs, src/ir/item_kind.rs, src/lib.rs, src/options.rs
This will solve #484 . Right now it's really basic and I will change some of things in future commits like docs and other things.
r? @fitzgen
=> Graphviz implementation

src/clang.rs
Clang on macOS Sierra doesn't have `clang_getCanonicalType`. It's used only when dumping clang AST, so I hope the fudge is acceptable.
=> Support older clang

.travis.yml
Not only for the large build times, but also because builds have been stalled
for long, and I had to merge a few PRs manually already.
r? @fitzgen
=> Disable osx testing.

src/clang.rs
This is a sorta-hot call already.
I've noticed #544 wants to add more assertions about this, and was going to
suggest moving them to `debug_assert!`.
But there's an easier way :)
r? @fitzgen
=> clang: Avoid a hot FFI call for getting the cursor kind.

src/codegen/mod.rs
=> codegen: Don't pad union fields.

README.md
Added clang-3.9 to debian install command. Without it, `cargo build` of [libbindgen-tutorial-bzip2-sys](https://github.com/fitzgen/libbindgen-tutorial-bzip2-sys) fails with:
```
/usr/include/stdio.h:33:11:` fatal error: 'stddef.h' file not found, err: true
```
=> fix clang installation instruction for debian os

src/clang.rs, src/lib.rs
Resolves issue #476. Moves out logic for checking whether a cursor has a filename (previously used exclusively in private function lib::filter_builtins) into the actual cursor. This code is then used to check whether a cursor is a builtin when dumping the AST.
=> Do not print builtin macro definitions in ast_dump

bindgen-integration/cpp/Test.cc, bindgen-integration/cpp/Test.h, bindgen-integration/src/lib.rs, src/codegen/mod.rs, tests/expectations/tests/bitfield_align.rs, tests/expectations/tests/bitfield_method_mangling.rs, tests/expectations/tests/jsval_layout_opaque.rs, tests/expectations/tests/layout_align.rs, tests/expectations/tests/layout_eth_conf.rs, tests/expectations/tests/layout_mbuf.rs, tests/expectations/tests/only_bitfields.rs, tests/expectations/tests/struct_with_bitfields.rs, tests/expectations/tests/union_with_anon_struct_bitfield.rs, tests/expectations/tests/weird_bitfields.rs
This commit reintroduces accessor methods for bitfields in the generated
bindings.
Fixes #519 
r? @emilio
=> Reintroduce bitfield accessors

src/codegen/helpers.rs, src/codegen/mod.rs, tests/expectations/tests/duplicated-namespaces-definitions.rs, tests/expectations/tests/duplicated-namespaces.rs, tests/expectations/tests/duplicated_constants_in_ns.rs, tests/expectations/tests/inline_namespace.rs, tests/expectations/tests/inline_namespace_conservative.rs, tests/expectations/tests/inline_namespace_whitelist.rs, tests/expectations/tests/issue-372.rs, tests/expectations/tests/issue-410.rs, tests/expectations/tests/issue-447.rs, tests/expectations/tests/issue_311.rs, tests/expectations/tests/module-whitelisted.rs, tests/expectations/tests/namespace.rs, tests/expectations/tests/nested_within_namespace.rs, tests/expectations/tests/reparented_replacement.rs, tests/expectations/tests/struct_typedef_ns.rs, tests/expectations/tests/template_alias_namespace.rs, tests/expectations/tests/union-in-ns.rs, tests/expectations/tests/whitelist-namespaces-basic.rs, tests/expectations/tests/whitelist-namespaces.rs
+ related issue: #562 
I just added those attributes at the root mod. And I'm not sure whether it should be better if we could set this setting in `build.rs`.
=> automatically allow non rust naming conventions

.travis.yml, ci/before_install.sh
First, update our existing 3.8.X and 3.9.X libclang testing versions to their latest point releases. Second, add testing on the latest 3.7.X release and the latest 4.0.X release.
r? @emilio
=> Run tests with more versions of libclang

src/codegen/mod.rs, tests/expectations/tests/enum_and_vtable_mangling.rs, tests/expectations/tests/nested_vtable.rs, tests/expectations/tests/ref_argument_array.rs, tests/expectations/tests/virtual_dtor.rs, tests/expectations/tests/virtual_inheritance.rs, tests/expectations/tests/virtual_overloaded.rs, tests/expectations/tests/vtable_recursive_sig.rs
```
warning: found non-foreign-function-safe member in struct marked #[repr(C)]: found zero-size struct in foreign module, consider adding a member to this struct
```
Emilio said on IRC:
> the empty vtable means that we don't care of figuring out the proper vtable layout, so we create an empty struct
Sounds like all that matters is to have a pointer, we don’t look at the data behind it. Using `c_void` seems appropriate, then.
=> Make vtables non-zero-size to fix a rustc warning.

src/clang.rs, src/ir/ty.rs, tests/expectations/tests/struct_typedef_ns.rs
Still a lot to be sorted out though.
=> clang: Fix most of the clang 5.0 regressions in our tests.

src/clang.rs, src/lib.rs
This should resolve #571. As discussed with @fitzgen I have moved the builtin-filtering out of `ast_dump` itself; this logic now happens at the point of call in `src/lib.rs`
=> #571: Allow ast_dump to print builtins; filter builtins locally

src/ir/context.rs
Per #603.
This still leaves `bindgen` having to make a call as to what to say when asked whether `Char` `is_signed()`.  I've opted just to leave this as `true`, on the grounds that:
* I don't currently understand an example where it matters
* I suspect that if there are cases where it matters, then it shouldn't!
* Because by definition, use of unadorned `char` in the original header says that it doesn't care about signedness
* (signed is the common case, so that's a more sensible guess than unsigned)
=> Treat char as c_char

src/ir/context.rs, src/ir/item.rs, src/ir/ty.rs
Getting closer to figuring out some of the other template related issues in clang 4.0, but not quite ready to land them yet. Figure this should probably land in the meantime. This is just a better fallback in the face of the unknown for panics that we've had reports of in the wild, but which I haven't had time to creduce.
r? @emilio
=> Fall back to opaque types rather than panicking on parse failure

src/ir/template.rs
Return `None` whenever we can't find a template definition, not only when the
template is a builtin.
Hitting this in other tests with libclang 4
r? @emilio or @upsuper
=> Generalize template instantiation fallibility

Cargo.toml
This enables one to locally do
$ cargo doc
and get library level documentation. Without the changes, cargo doesn't know whether to build docs for the binary or library, and so instead it gives an error and stops.
r? @emilio
=> Don't build documentation for the binary, just the lib

src/ir/named.rs
This replaces various `unwrap` calls with `expect` calls that have better diagnostic messages if/when they fail.
Doing this as part of the investigation into why the analysis is failing when producing bindings for stylo.
r? @emilio
=> Provide better diagnostics for assertions in the template analysis

Cargo.lock, Cargo.toml
Glancing through the git log it looks like a public API or two was renamed, and what with the template refactoring work, it seems like emitted bindings will be different enough that a breaking version bump is called for.
r? @emilio
=> Bump to version 0.23.0

src/lib.rs, src/regex_set.rs
1. Added new method `command_line_flags` to `Builder` to generate
list of command line arguments supplied.[file: src/lib.rs]
2. Added new method `get_set` and `get_items` method to `RegexSet`
to return immutable reference to it's fields.[file: src/regex_set.rs]
3. Added simple test case for `command_line_flags` method.[file: src/lib.rs]
=> Issue #548 : Added command line flag generation method to Builder 

src/codegen/mod.rs, src/lib.rs, src/options.rs
=> Option to avoid generating layout tests

Cargo.lock, Cargo.toml, bindgen-integration/build.rs, src/lib.rs
Use `AsRef<str>` rather than `Into<String>` because `&&str` (what you get when iterating `&[&str]`) does not implement the latter.
=> Add Builder::clang_args (plural)

build.rs
It may not exist after packaging. This should unblock publishing bindgen.
=> build: Don't always expect a tests/headers directory.

src/ir/named.rs, src/lib.rs
This is a follow up to c8a206a, and the support for blacklisting in the named template parameter usage analysis. This ensures that ever item we ever call `constrain` on has an entry in `used` for the set of template parameters it uses. Additionally, it adds extra assertions to enforce the invariant.
We cannot completely avoid analyzing blacklisted items because we want to consider all of a blacklisted template's parameters as used. This is why we ensure that blacklisted items have a used template parameter set rather than ensuring that blacklisted items never end up in the worklist.
This fixes the panic I saw in https://github.com/servo/servo/pull/16392, but there are still issues leftover in the resulting bindings that I am tracking down.
r? @emilio
=> Finish fixing blacklisting + template analysis

src/lib.rs
I tried my best to understand the existing doc comments, but please verify that I did not change their intended meaning.
Also, I'm not sure if my local `rustfmt` is set up correctly, but running `cargo fmt` locally caused a lot of rust code to be changed, so I did not commit those changes.
=> Fix doc comments

src/clang.rs, src/ir/function.rs
As pointed out in #653, clang 3.8 asserts when trying to mangle a C++
constructor or a destructor.
The following patch tries to use the `clang_Cursor_getCXXManglings` function
first.
This assumes that the last mangling we're interested in is the proper one,
which seems to be true looking at LLVM, and on trunk on my machine.
Fixes #653
=> ir: Try to get C++ manglings with the appropriate API first.

Cargo.toml
Better fix for #671 for downstream crates.
r? @upsuper or @emilio
=> Bump the required clang-sys version to 0.15.2

Cargo.lock, Cargo.toml
This bumps the dependency clang-sys from 0.15.2 to 0.16.0. It removes some heavy dependencies from the tree, notably serde_json.
This resolves issue #499.
=> Kill serde_json dependency

Cargo.lock, Cargo.toml, src/lib.rs
It turns out that some versions of Clang don't have `#include <...> search starts here:` in their output (KyleMayes/clang-sys#54).
I changed the storage type of the include search paths in `clang-sys` from `Vec<PathBuf>` to `Option<Vec<PathBuf>>` to reflect the possibility that finding and parsing the include search paths might fail.
=> Bump clang-sys to 0.17.0

src/ir/template.rs
=> ir: Handle default template parameters in libclang >3.9.

src/codegen/mod.rs, tests/expectations/tests/bitfield-enum-basic.rs
Currently, bitflag enums only implement `BitOr`. However, it is fairly common to `&` bitflags, requiring the `BitAnd` trait to be implemented as well. I also implemented `BitOrAssign` and `BitAndAssign` in the process.
=> Add other bitwise ops for bitflag enums

Cargo.lock, Cargo.toml
This update improves detection of versioned instances of `libclang.so` (e.g., `libclang.so.3.9`).
See [here](https://github.com/KyleMayes/clang-sys/tree/db88aea22b3ad67020fab331b42ddc071e598c8c#dependencies) for information on which instance is selected when there are more than one to choose from.
Thanks to @semarie for a pull request implementing this.
=> Bump clang-sys version to 0.18.0

Cargo.lock, Cargo.toml, ci/test.sh, src/codegen/mod.rs, src/codegen/struct_layout.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/dot.rs, src/ir/item.rs, src/ir/ty.rs, src/lib.rs, tests/expectations/tests/bitfield-method-same-name.rs, tests/expectations/tests/bitfield_align.rs, tests/expectations/tests/bitfield_method_mangling.rs, tests/expectations/tests/jsval_layout_opaque.rs, tests/expectations/tests/layout_align.rs, tests/expectations/tests/layout_eth_conf.rs, tests/expectations/tests/layout_mbuf.rs, tests/expectations/tests/only_bitfields.rs, tests/expectations/tests/struct_with_bitfields.rs, tests/expectations/tests/union_with_anon_struct_bitfield.rs, tests/expectations/tests/weird_bitfields.rs, tests/test-one.sh
This PR moves bitfields and the computation of their allocation units into the IR. They were previously computed on-the-fly during code generation. In addition to breaking up and compartmentalizing a portion of the gargantuan `CodeGeneration` implementation for `CompInfo`, this paves the way for adding const-fn bitfield unit constructors.
Also some improvements to `tests/test-one.sh`.
Also some graphviz output improvements that got tangled up in the last commit without a good way to pull them out into their own commit (sorry).
r? @emilio
=> Move bitfields into the IR

bindgen-integration/src/lib.rs, src/codegen/mod.rs, src/ir/comp.rs, tests/expectations/tests/bitfield-method-same-name.rs, tests/expectations/tests/bitfield_align.rs, tests/expectations/tests/bitfield_method_mangling.rs, tests/expectations/tests/jsval_layout_opaque.rs, tests/expectations/tests/layout_align.rs, tests/expectations/tests/layout_eth_conf.rs, tests/expectations/tests/layout_mbuf.rs, tests/expectations/tests/only_bitfields.rs, tests/expectations/tests/struct_with_bitfields.rs, tests/expectations/tests/union_with_anon_struct_bitfield.rs, tests/expectations/tests/weird_bitfields.rs
This commit gives bindgen the ability to generate constructors for bitfield allocation units. This enables more ergonomic use of struct literals for bindings structs that contain bitfields.
Additionally, when we are generating unstable Rust, these constructors are marked as const functions. This enables the creation of const binding structs that contain bitfields. (Something necessary for Servo's usage of SpiderMonkey).
r? @emilio
=> Add bitfield allocation unit constructors

src/codegen/mod.rs, src/ir/item.rs, tests/expectations/tests/anon_union.rs, tests/expectations/tests/class_nested.rs, tests/expectations/tests/class_with_dtor.rs, tests/expectations/tests/crtp.rs, tests/expectations/tests/default-template-parameter.rs, tests/expectations/tests/issue-569-non-type-template-params-causing-layout-test-failures.rs, tests/expectations/tests/issue-691-template-parameter-virtual.rs, tests/expectations/tests/non-type-params.rs, tests/expectations/tests/partial-specialization-and-inheritance.rs, tests/expectations/tests/template.rs
This should be good enough, following the pattern of anonymous items, and should
prevent most of the current noise in stylo updates.
Closes #620
Fixes #619
=> codegen: Reuse the next_child_local_id hack for template instantiations.

Cargo.lock, Cargo.toml
This should fix https://bugzilla.mozilla.org/show_bug.cgi?id=1365488
There aren't any breaking changes since 0.25, only new features and fixes for libclang >3.9
=> Minor version bump to peek up clang-sys updates in stylo.

src/ir/function.rs
Rust automatically adds one _ in the symbol. If we don't remove it, we will
endup getting three _.
r? @emilio
=> Fix osx mangling hack

src/codegen/mod.rs, tests/expectations/tests/bitfield-method-same-name.rs, tests/expectations/tests/bitfield_align.rs, tests/expectations/tests/bitfield_method_mangling.rs, tests/expectations/tests/jsval_layout_opaque.rs, tests/expectations/tests/layout_align.rs, tests/expectations/tests/layout_eth_conf.rs, tests/expectations/tests/layout_mbuf.rs, tests/expectations/tests/only_bitfields.rs, tests/expectations/tests/struct_with_bitfields.rs, tests/expectations/tests/union_with_anon_struct_bitfield.rs, tests/expectations/tests/weird_bitfields.rs
Const function can't have variables or blocks.
r? @fitzgen
=> Fix bitfield generation bug with const function

tests/headers/call-conv-field.h, tests/tests.rs
This is a temporary work around for issue #593 and this test failing on MacOS because we don't currently handle when the bindgen executable's target OS is not the same as the emitted bindings' target OS.
r? @emilio
=> Only run call-conv-field.h test on linux

src/codegen/mod.rs, src/ir/function.rs
This unblocks stylo in windows until we get `__thiscall` support in syntex. see #541.
=> ir: Don't panic when finding an unknown calling convention until code generation

.gitignore, tests/test-one.sh
Check for correct arguments, quote variables, ensure exactly one test
file matches the pattern, and print usage information.
Here are some examples:
~~~
$ ./tests/test-one.sh
Usage: ./tests/test-one.sh <fuzzy-name>
~~~
~~~
$ ./tests/test-one.sh zzz
ERROR: no files found with pattern "zzz"
~~~
~~~
$ ./tests/test-one.sh union
ERROR: Expected exactly 1 result, got 15:
./tests/headers/struct_with_anon_unnamed_union.h
./tests/headers/union_dtor.hpp
./tests/headers/union_with_anon_union.h
./tests/headers/union_with_big_member.h
./tests/headers/anon_union.hpp
./tests/headers/union_fields.hpp
./tests/headers/union_with_anon_struct_bitfield.h
./tests/headers/struct_with_anon_union.h
./tests/headers/union-in-ns.hpp
./tests/headers/union_with_anon_unnamed_union.h …
=> Refactor test script

src/codegen/mod.rs, src/ir/item.rs, src/ir/template.rs, src/ir/ty.rs
And also its trait methods `is_named` and `as_named` into `is_template_param`
and `as_template_param` respectively.
These new names better reflect what the trait is about.
r? @emilio
=> Rename `AsNamed` to `AsTemplateParam`

book/src/requirements.md
Homebrew now defaults to llvm 4.0.x so there's no need to specify a specific version to get compatibility, unless we specifically want people using 3.9.
=> Drop llvm@3.9 versioning for homebrew.

tests/test-one.sh
On Mac OS where egrep is != GNU grep, the script fails with
~~~
egrep: repetition-operator operand invalid
ERROR: no files found with pattern "virtual_inheritance"
~~~~
The `$pattern` is supposed to be a substring in the test name to run.
The leading and trailing stars are wrong, since egrep takes a regular expression, not a glob.
=> Fix tests/test-one.sh.

Cargo.lock, Cargo.toml, src/lib.rs
This is for https://bugzilla.mozilla.org/show_bug.cgi?id=1366050
But it has to wait for https://github.com/KyleMayes/clang-sys/pull/57 to land and version number bumped.
(I'm making up the new version numbers for now.)
r? @emilio
=> Passing additional clang arguments for Linux 32 cross compiling

src/ir/ty.rs
After some discussion in #765 we do not think anymore that this can ever be true.
=> Remove Type::detect_has_vtable_cycle.

.github/ISSUE_TEMPLATE.md
The inclusion of an `#include` means that the test case
* is not minimal, and
* is harder to reproduce the bug with, since not everyone has the same headers (or versions of headers) on their system.
r? @emilio
=> Minimal test cases don't have `#include`s

ci/no-includes.sh, ci/test.sh, tests/tests.rs
See each commit message.
Disallowing *system* includes and not *all* includes because we have one local include in `extern.hpp`, and local includes will at least be consistent/reproducible.
r? @emilio
=> No system includes in test headers

tests/tests.rs
Automatically detect libclang version when testing and use approppriate
expectation files.
Ref to issue #794.
=> Automatically detect libclang version when testing

.travis.yml, book/src/tutorial-0.md, book/src/tutorial-1.md, book/src/tutorial-3.md, book/src/tutorial-4.md, book/src/tutorial-5.md, book/src/tutorial-6.md
This also removes old references to `libbindgen` and replaces them with
`bindgen`. I renamed the repo containing the tutorial's full code, so those
github links should work, and this isn't just an artifact of a blind
search/replace.
Part of #803
=> Update the tutorial for the latest bindgen release

.gitignore, CONTRIBUTING.md, src/lib.rs, src/options.rs, tests/tests.rs
See each commit message.
Fixes #811.
r? @emilio
=> Dump preprocessed input headers

book/src/cpp.md
When using -x=c++ in bindgen arguments, we hit #340. We should use -x c++ instead.
=> Document -x c++, not -x=c++

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.md, src/lib.rs, tests/headers/arg_keyword.hpp
It should be really easy to generate standalone, isolated test cases for bindgen bugs now \o/
See each commit for further details.
r? @emilio
=> Preserve comments when dumping preprocessed input headers

ci/assert-docs.sh
Running `cargo check --features testing_only_docs` will catch missing doc
comments, and we can avoid doing a full build.
r? @emilio
=> Speed up CI runs by only `cargo check`ing for docs

tests/expectations/tests/test_multiple_header_calls_in_builder.rs, tests/tests.rs
These changes allow `cargo test` to pass on Windows.
There are two followup work we should do at some point:
* setup AppVeyor so that we don't break Windows development either
* convert `no_system_header_includes` to be pure Rust so that it supports Windows natively
=> Have tests pass on Windows

src/ir/cant_derive_debug.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/derive.rs, src/ir/function.rs, src/ir/item.rs, src/ir/layout.rs, src/ir/mod.rs, src/ir/template.rs, src/ir/traversal.rs, src/ir/ty.rs
It's failing about 30 tests now and most of them is related to template. I'm also not so sure about the place to call compute_can_derive_debug in gen. 
Fix: #767 
r? @fitzgen
=> Use fix point analysis to implement can_derive_debug

.github/ISSUE_TEMPLATE.md
Neither Emilio nor I find it helpful, so lets rm -rf
=> Remove RUST_LOG=bindgen from the issue template

Cargo.lock, Cargo.toml
Brings in  #822 which unblocks https://bugzilla.mozilla.org/show_bug.cgi?id=1366956,
and also #829 which should greatly reduce merge conflicts in checked in bindings.
=> Bump to 0.28

src/codegen/mod.rs, src/ir/analysis/has_vtable.rs, src/ir/analysis/mod.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/derive.rs, src/ir/item.rs, src/ir/layout.rs, src/ir/template.rs, src/ir/ty.rs
=> has vtable analysis

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.md, Cargo.toml, book/src/introduction.md, ci/deploy-book.sh, src/codegen/mod.rs, src/ir/comp.rs, src/ir/function.rs, src/lib.rs, src/main.rs, src/options.rs, tests/headers/call-conv-field.h
Fixes #852 
r? @emilio or @Manishearth
=> s/servo/rust-lang-nursery/ \o/

appveyor.yml, ci/assert-no-diff.bat, ci/test.bat, ci/test.sh
CC @upsuper @emilio 
Issues:
- `test/expectations` fails at:
```
error[E0512]: transmute called with differently sized types: u64 (64 bits) to i32 (32 bits)
--> tests\bitfield_align_2.rs:78:18
|
78 |         unsafe { ::std::mem::transmute(val as u64) }
|                  ^^^^^^^^^^^^^^^^^^^^^ transmuting between 64 bits and 32 bits
```
- MSVC with LLVM 3.9: many tests fails
- 32-bit builds: many tests fails
Appveyor build: https://ci.appveyor.com/project/UK992/rust-bindgen/build/1.0.62
=> (WIP) Setup Appveyor

src/codegen/mod.rs, src/ir/analysis/has_vtable.rs, src/ir/context.rs, src/ir/derive.rs, src/ir/item.rs, src/ir/ty.rs
=> Remove unused `Extra` associated types

src/ir/item.rs, tests/expectations/tests/template.rs, tests/headers/template.hpp
=> Stablize name of pointer and array

releases/friends.sh, releases/release-announcement-template.md
And a script to find all the folks who contributed to the release.
Anything we should add or remove to the release announcement template? Once we've hashed this out, I'll make the first release announcement thread on u.r-l.o :-)
r? @emilio @nrc
=> Add a template for release announcements

src/codegen/mod.rs, src/ir/analysis/derive_default.rs, src/ir/analysis/mod.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/derive.rs, src/ir/item.rs, src/ir/layout.rs, src/ir/ty.rs, tests/expectations/tests/crtp.rs, tests/expectations/tests/issue-573-layout-test-failures.rs, tests/expectations/tests/issue-574-assertion-failure-in-codegen.rs, tests/expectations/tests/issue-674-1.rs, tests/expectations/tests/issue-674-2.rs, tests/expectations/tests/issue-674-3.rs, tests/expectations/tests/no-recursive-whitelisting.rs, tests/expectations/tests/replace_use.rs, tests/expectations/tests/typeref.rs
=> Can derive default analysis

src/ir/context.rs, src/ir/item.rs
=> Clean up left over derive debug nits

src/codegen/mod.rs, src/ir/analysis/derive_copy.rs, src/ir/analysis/has_type_param_in_array.rs, src/ir/analysis/mod.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/derive.rs, src/ir/item.rs, src/ir/layout.rs, src/ir/template.rs, src/ir/ty.rs
r? @fitzgen  or @emilio. Fix: #766
=> Can derive copy analysis

src/ir/analysis/derive_default.rs, tests/expectations/tests/no-derive-debug.rs, tests/expectations/tests/no-recursive-whitelisting.rs, tests/expectations/tests/opaque-template-inst-member-2.rs, tests/expectations/tests/opaque-template-inst-member.rs, tests/expectations/tests/opaque_pointer.rs, tests/expectations/tests/template.rs
Fix regression of derive default analysis.   
Also fix opaque handing exposed by the above fix. r? @fitzgen
=> Fix recursive whitelisting and handling of opaque for derive default

.travis.yml, ci/before_install.sh
=> ci: Cache LLVM builds.

src/ir/context.rs, src/ir/item.rs, src/ir/ty.rs, tests/expectations/tests/template.rs, tests/headers/template.hpp
This fixes stylo build failures when template instantiations tests caused a rust
compile error due to a bad test name.
This commit makes names better sanitized, preventing similar errors in the
future.
=> ir: Sanitize base names more aggressively

Cargo.toml
We now have various files that are unnecessary for package, including the book, the release note template, and even a 1.3MB PNG file!
This change makes us only include the necessary files (source files, build script, and metadata). Using whitelist so that we have fewer items, and it would be harder to regress.
=> Only include necessary files in package

src/codegen/mod.rs, tests/expectations/tests/16-byte-alignment.rs, tests/expectations/tests/anon_struct_in_union.rs, tests/expectations/tests/anon_union.rs, tests/expectations/tests/class.rs, tests/expectations/tests/class_with_inner_struct.rs, tests/expectations/tests/issue-493.rs, tests/expectations/tests/jsval_layout_opaque.rs, tests/expectations/tests/layout_eth_conf.rs, tests/expectations/tests/layout_mbuf.rs, tests/expectations/tests/struct_with_anon_union.rs, tests/expectations/tests/struct_with_anon_unnamed_union.rs, tests/expectations/tests/struct_with_nesting.rs, tests/expectations/tests/typeref.rs, tests/expectations/tests/union-in-ns.rs, tests/expectations/tests/union_dtor.rs, tests/expectations/tests/union_fields.rs, tests/expectations/tests/union_template.rs, tests/expectations/tests/union_with_anon_struct.rs, tests/expectations/tests/union_with_anon_struct_bitfield.rs, tests/expectations/tests/union_with_anon_union.rs, tests/expectations/tests/union_with_anon_unnamed_struct.rs, tests/expectations/tests/union_with_anon_unnamed_union.rs, tests/expectations/tests/union_with_big_member.rs, tests/expectations/tests/union_with_nesting.rs, tests/expectations/tests/use-core.rs, tests/headers/16-byte-alignment.h
This fix creates a new private field with the required aligned size. This new
private field ensures that the union has the required size.
This fixes: #908
=> Fixes alignment errors with new Rust union type

Cargo.lock, Cargo.toml, src/codegen/mod.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/template.rs, src/lib.rs, src/options.rs
This patch enables bindgen to run rustfmt on generated bindings. Rustfmt is used
from the global PATH. Two new command-line arguments are added:
1. --format-bindings: Enables running rustfmt
2. --format-configuration-file: The configuration file for rustfmt (not required).
Fixes: #900
=> Adds support for running rustfmt on generated bindings

src/ir/context.rs
Currently, there are various analyses related to deriving various traits that we unconditionally run. However, if we aren't going to derive those traits in codegen, then computing whether or not we can derive the traits is wasteful.
r? @emilio
=> Only run analyses when we are going to use their results

src/ir/context.rs
If we aren't going to derive `PartialEq`, then it doesn't make sense to even run the analysis.
r? @photoszzt or @emilio
=> Only compute which types we can derive PartialEq for if we'll use it

src/clang.rs
Older clang don't have it, and while we can't pass our whole test suite with those older clangs, we can still generate simple C bindings, so it makes sense not to panic for C++ only things.
=> Check if `clang_Type_getNumTemplateArguments` is loaded before use

src/ir/analysis/derive_copy.rs, src/ir/analysis/derive_default.rs, src/ir/analysis/has_type_param_in_array.rs, src/ir/context.rs
=> Fix misleading comments

src/codegen/helpers.rs, src/codegen/mod.rs, src/codegen/struct_layout.rs
Thanks @fitzgen for the detailed instructions.
Fixes #928.
=> Simplify helpers::blob

src/ir/analysis/derive_copy.rs, src/ir/analysis/has_destructor.rs, src/ir/analysis/mod.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/template.rs, src/ir/ty.rs
Fixes #927 . Note that this creates a dependency between the "cannot derive copy" and "has destructor" analysis, i.e. the "has destructor" analysis must run before the "cannot derive copy" analysis, because "cannot derive copy" needs the results of "has destructor".
=> Rewrite `has destructor` analysis as a fixed-point analysis

Cargo.lock, Cargo.toml
Version bump, primarily to get #832 and #892 in now that 1.19 is out and untagged unions are usable in stable!
r? @emilio
=> Bump version to 0.30.0

src/codegen/mod.rs
WIP fix for issue #929 
With libclang 4, passes all tests on my machine except `dump_preprocessed_input`, but that fails on the master branch as well
=> Avoid generating fields/methods for opaque objects

src/codegen/mod.rs, src/ir/context.rs, src/lib.rs, src/options.rs, src/time.rs
New module `time_phases` with an RAII timer which prints to stderr, and command-line flag `--time-phases` to enable it.
Fixes #933
=> Time phases

CONTRIBUTING.md
These are currently inaccurate as `cargo fmt` is not enforced for bindgen.
This section can be re-instated if and when code formatting is enforced.
=> Delete automatic code formatting guidelines

src/ir/context.rs
=> ir: Pass the target to clang if it wasn't explicitly passed already.

CONTRIBUTING.md
This should help new contributors who are coming to the code base for the first time get up and running.
r? @emilio
=> Add an architectural overview of `bindgen` to CONTRIBUTING.md

src/lib.rs, src/options.rs
Closes #986 
This is my first time contributing to rust so hopefully I did everything right, otherwise let me know.
=> Make whitelisted_var consistant with CLI flags

src/lib.rs, src/options.rs
Closes #985 
I also noticed a reference to `whitelisted_function` within the book, should this be updated as well?
https://github.com/rust-lang-nursery/rust-bindgen/blob/a371de097f5e37eb01754525fb1e2029ca88b0be/book/src/whitelisting.md
I've started to learn rust recently, so please let me know if there is anything I missed.
=> Depreciate whitelisted function.

src/codegen/mod.rs, src/ir/context.rs, src/ir/item.rs, src/lib.rs
This deprecates `Builder::hide_type`.
Related to #984.
r? @fitzgen
=> Add a `Builder::blacklist_type`

src/lib.rs, src/options.rs
Closes #987
Also, we were making a call to the now deprecated `Builder::hide_type`,
changed that over to call `Builder::blacklist_type.
=> Depreciate `Builder::whitelisted_type`.

src/ir/context.rs, src/lib.rs, src/regex_set.rs
Fixes https://github.com/rust-lang-nursery/rust-bindgen/issues/958
r? @fitzgen
=> Make BindgenOptions private

src/codegen/mod.rs, src/ir/context.rs, src/ir/derive.rs, src/ir/item.rs, src/lib.rs, src/options.rs, tests/expectations/tests/derive-hash-struct-with-anon-struct-float.rs, tests/expectations/tests/derive-hash-struct-with-float-array.rs, tests/expectations/tests/derive-hash-struct-with-pointer.rs, tests/expectations/tests/derive-hash-template-def-float.rs, tests/expectations/tests/derive-hash-template-inst-float.rs, tests/headers/derive-hash-blacklisting.hpp, tests/headers/derive-hash-struct-with-anon-struct-float.h, tests/headers/derive-hash-struct-with-float-array.h, tests/headers/derive-hash-struct-with-pointer.h, tests/headers/derive-hash-template-def-float.hpp, tests/headers/derive-hash-template-inst-float.hpp
=> Derive ord when possible

src/ir/analysis/derive_partial_eq_or_partial_ord.rs, src/ir/context.rs, src/ir/derive.rs, src/ir/function.rs, src/ir/layout.rs, src/lib.rs
See each commit for details.
r? @emilio
=> Some little deriving cleanups

.gitattributes
Addresses #1023.
The line endings accidentally don't matter for the majority of the tests because we pass both the generated .rs files and expectations .rs files through rustfmt, which normalizes the line endings to LF. But this change makes it explicit that we expect to test against files with LF line endings.
=> Always check out test headers and expectations as LF

src/ir/objc.rs, tests/expectations/tests/objc_class_method.rs, tests/expectations/tests/objc_method.rs, tests/expectations/tests/objc_property_fnptr.rs
Fixes #1004.
After looking at how `msg_send!` is supposed to be used, I realized that
we were erroneously passing type signatures to it.
The expectations compile now, but some of them are not formatted properly.
My guess is that `rustfmt` does not know how to format the following:
```
msg_send!(obj, arg1:1 arg2:2 arg3:3)
```
Notice the lack of separatros between the `arg`s.
Any advice on how to proceed here is appreciated.
r? @fitzgen
=> Make objc-related expectations compile

src/lib.rs
Seems like the right thing to do, and allows me to test stuff piping to rustc instead of saving to a file.
=> lib: Print warnings to stderr instead of stdout.

src/lib.rs, src/options.rs
This patch flips --rustfmt-bindings to --no-rustfmt-bindings and enables
formatting by default. If rustfmt is not accessible, a warning is
printed and the bindings are printed unformatted.
Addresses #977.
=> Enable --rustfmt-bindings by default

book/src/cpp.md
Trying to set expectations for what we can do with C++ a little better.
r? @emilio
=> book: Clean up the C++ section some more

src/codegen/impl_debug.rs, src/codegen/mod.rs, src/codegen/struct_layout.rs, src/ir/analysis/derive_copy.rs, src/ir/analysis/derive_debug.rs, src/ir/analysis/derive_default.rs, src/ir/analysis/derive_hash.rs, src/ir/analysis/derive_partial_eq_or_partial_ord.rs, src/ir/analysis/has_destructor.rs, src/ir/analysis/has_float.rs, src/ir/analysis/has_type_param_in_array.rs, src/ir/analysis/has_vtable.rs, src/ir/analysis/template_params.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/enum_ty.rs, src/ir/function.rs, src/ir/item.rs, src/ir/module.rs, src/ir/template.rs, src/ir/ty.rs, src/ir/var.rs, src/parse.rs
=> Strongly type ids

src/codegen/impl_debug.rs, src/codegen/impl_partialeq.rs, src/codegen/mod.rs, src/ir/comp.rs, tests/expectations/tests/bitfield_large_overflow.rs
This PR is some changes to early bitfield filtering to help fix (#1007) This does not close (#1007), but allows for checking if the bitfield is too large during a later stage.
@fitzgen r?
=> Remove early anonymous bitfield filtering and consolidate name method

src/ir/comp.rs, src/ir/context.rs, tests/expectations/tests/bitfield_large_overflow.rs, tests/headers/bitfield_large_overflow.hpp
@fitzgen r?
Fixes #1007 by ensuring that bitfields larger than type will be opaque, ensuring the layout is correct.
=> Make bitfields larger than type opaque

CONTRIBUTING.md, csmith-fuzzing/driver.py, csmith-fuzzing/predicate.py
This allows it to be used by both fuzzers and when using `creduce`. See each commit for details.
r? @pepyakin
=> Factor out a general purpose predicate script from the `csmith` driver

tests/headers/call-conv-field.h, tests/tests.rs
Fixes https://github.com/rust-lang-nursery/rust-bindgen/issues/1067
I didn't check it on macos because I don't have one, but it will be a surprise if it doesn't work.
=> Make the default target for expectation files as x86_64-unknown-linux

src/codegen/mod.rs, src/ir/comp.rs
Its more clear what the methods/fields are returning/storing when we add "width"
to the name.
r? @pepyakin
=> Rename `bitfield` to `bitfield_width`

csmith-fuzzing/README.md, csmith-fuzzing/driver.py, csmith-fuzzing/predicate.py
Reduced test cases FTW \o/
r? @emilio or @pepyakin 
Also, this prints out everything needed to file a bug report; just copy paste! For example, this is what it looks like when I ran it most recently:
<details><pre><code>
$ ./driver.py 
Fuzzing `bindgen` with C-Smith...
Iteration: 0
Error: ['./predicate.py', '--bindgen-args', '--with-derive-partialeq --with-derive-eq --with-derive-partialord --with-derive-ord --with-derive-hash --with-derive-default --  -I/home/fitzgen/rust-bindgen/csmith-fuzzing', '/tmp/input-uij7lxep.h'] exited with code 1
+Running: ['cargo', 'run', '--manifest-path', '/home/fitzgen/rust-bindgen/Cargo.toml', '--', '/tmp/input-uij7lxep.h', '-o', '/tmp/bindings-vyl0qlte.rs', '--with-derive-partialeq', '--with-derive-eq', '--with-derive-partialord', '--with-derive-ord', …
=> Automatically run `creduce` in `csmith-fuzzing/driver.py`

src/codegen/mod.rs, src/ir/function.rs
This lets us capture 'static inline' functions in the ir and filter them
later down the pipeline. This is the first step on the way to handling
these functions better.
=> Store function linkage in the ir

src/lib.rs
=> Issue #1029: Print error messages if header is a folder or unreadable

src/codegen/mod.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/enum_ty.rs, src/ir/function.rs, src/ir/layout.rs, src/ir/template.rs, src/ir/traversal.rs, src/ir/ty.rs, src/ir/var.rs
Should be no change in behavior.
=> ir: Cleanup a bunch of constructors

src/options.rs
Fixing up a comment from #1105
=> give better variable name

book/src/whitelisting.md
While working on #990 depreciated the `whitelisted_function` I noticed a couple of links in the book that also should be updated to refer to the updated methods.
@fitzgen one question here, I assume I will also need to update the version number within the url as new documentation won't be built until the next release?
=> Fix whitelisting documentation links in book.

src/lib.rs
Some cases in spawning rustfmt were not properly returning the source. Make it
more reliable.
This hit me when trying to update bindgen in Firefox.
=> lib: Always generate bindings.

Cargo.lock, Cargo.toml
Only bugfixes have landed since the last release (#1112 and #1114), apart from
doc fixes.
=> Minor version bump.

Cargo.lock, Cargo.toml, src/ir/item.rs
The item may come from a recursive check down the stack, and as we say there:
> Unchecked because we haven't finished this type yet.
Fixes #1127
=> ir: We can't guarantee the type to be in the item map while propagating AlreadyResolved

src/ir/comp.rs, tests/expectations/tests/issue-1076-unnamed-bitfield-alignment.rs, tests/headers/issue-1076-unnamed-bitfield-alignment.h
=> Unnamed bit-fields and alignment

csmith-fuzzing/predicate.py
Embarrassingly, we were ignoring and swallowing a dumb reference error that prevented the temp files from ever getting cleaned up.
The good news: with ignoring bitfields and packed structs, I got to `driver.py` iteration 27145 without triggering any `bindgen` bugs, and then the disk got full! :-p
r? @pepyakin
=> Actually cleanup temp files in predicate

CHANGELOG.md, releases/release-announcement-template.md
It is initially populated with information from our release announcements.
It has an "unreleased" section for accumulating notable changes that haven't been released yet, and to make it easier to summarize releases when we do publish them.
Fixes #1131
r? @emilio or @pepyakin
=> Add a changelog

src/codegen/mod.rs, src/codegen/struct_layout.rs, src/ir/comp.rs, src/ir/ty.rs, tests/expectations/tests/divide-by-zero-in-struct-layout.rs, tests/expectations/tests/layout.rs, tests/headers/issue-537.h
This is a bandaid for #537. It does *not* fix the underlying issue, which requires `#[repr(packed = "N")]` support in Rust. However, it does make sure that we don't generate type definitions with the wrong layout, or fail our generated layout tests.
r? @emilio or @pepyakin
=> Detect `#pragma pack(...)` and make `pack(n)` where `n > 1` opaque

src/lib.rs
From rustfmt docs, the --write-mode flag is unecessary when passing the flag to stdin. If we leave it there, rustfmt-nightly complains that it cannot find the file named --write-mode, so let's remove the flag.
here's the logs when I leave the flag : 
```
Error: file `--write-mode=display` does not exist
Error { repr: Custom(Custom { kind: Other, error: StringError("Internal rustfmt error") }) }
```
<details>
<summary>The build.rs : </summary>
```rust
extern crate bindgen;
use std::env;
use std::path::PathBuf;
fn main() {
println!("cargo:rustc-link-lib=static=transistor.nro");
println!("cargo:rustc-link-search=native=libtransistor/build/lib");
let bindings = bindgen::Builder::default()
.header("libtransistor/include/libtransistor/nx.h")
// Don't use host headers, to make sure we're …
```
=> Remove unnecessary flag from rustfmt invocation

src/codegen/mod.rs, tests/expectations/tests/bitfield-32bit-overflow.rs, tests/expectations/tests/bitfield-method-same-name.rs, tests/expectations/tests/bitfield_align.rs, tests/expectations/tests/bitfield_align_2.rs, tests/expectations/tests/bitfield_method_mangling.rs, tests/expectations/tests/derive-bitfield-method-same-name.rs, tests/expectations/tests/derive-debug-bitfield.rs, tests/expectations/tests/derive-partialeq-bitfield.rs, tests/expectations/tests/jsval_layout_opaque.rs, tests/expectations/tests/jsval_layout_opaque_1_0.rs, tests/expectations/tests/layout_align.rs, tests/expectations/tests/layout_eth_conf.rs, tests/expectations/tests/layout_eth_conf_1_0.rs, tests/expectations/tests/layout_mbuf.rs, tests/expectations/tests/layout_mbuf_1_0.rs, tests/expectations/tests/only_bitfields.rs, tests/expectations/tests/struct_with_bitfields.rs, tests/expectations/tests/union_bitfield.rs, tests/expectations/tests/union_bitfield_1_0.rs, tests/expectations/tests/union_with_anon_struct_bitfield.rs, tests/expectations/tests/union_with_anon_struct_bitfield_1_0.rs, tests/expectations/tests/weird_bitfields.rs
This fixes https://github.com/rust-lang-nursery/rust-bindgen/issues/954.
r? @emilio
=> Avoid bitfield getters and setters accessing memory beyond "self"

CONTRIBUTING.md, bindgen-integration/build.rs
Also note the need to rebuild bindgen when running a single test.
r? @emilio
=> Improve documentation of the integration tests

CHANGELOG.md, src/codegen/mod.rs, src/ir/enum_ty.rs, tests/headers/constify-module-enums-namespace.hpp, tests/headers/constify-module-enums-simple-nonamespace.hpp
...by using canonical_path rather than canonical_name.
Fixes #1125.
r? @emilio
=> Properly handle namespaces for enum configuration options

src/clang.rs, src/ir/context.rs, src/ir/var.rs
This makes it easier to call it without passing around a TranslationUnit,
which will prove itself useful to parse `__attribute__` nodes.
=> Move tokens method from TranslationUnit to Cursor

ci/script.sh, tests/quickchecking/Cargo.toml, tests/quickchecking/src/bin.rs, tests/quickchecking/src/lib.rs, tests/quickchecking/tests/fuzzed-c-headers.rs
Prior to this commit the quickchecking crate used for generating proprty tests for bindgen was a [lib] target and had configurations that required commenting/uncommenting code to enable/disable. This meant it was inconvienent/prohibitive to configure the property tests on a per-run basis. This commit reorganizes the `quickchecking` crate to provide both [lib] and [[bin]] targets in order to expose those configurations through a CLI.
The configurations that are exposed through the [[bin]] target's CLI are:
* Count/number of tests to run.
* Directory to provide fuzzed headers
* Generation range corresponding to the range quickcheck uses to
* generate arbitrary.
__Usage from the__ `tests/quickchecking` __directory__
```bash
quickchecking 0.2.0
Bindgen property tests with quickcheck. Generate …
```
=> Quickchecking crate CLI

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Bump to 0.32.0

CONTRIBUTING.md, tests/quickchecking/Cargo.toml, tests/quickchecking/README.md, tests/quickchecking/src/bin.rs, tests/quickchecking/src/fuzzers.rs
Logic to enable/disable special casing (due to known issues #550, #684, and #1153) has been exposed as features in the `quickchecking` crate's Cargo.toml file and corresponding `cfg` attributes in the source.
In addition to adding Cargo features, this PR represents the following:
- Documentation in `bindgen`'s CONTRIBUTING.md that points to a new README.md located in the `quickchecking` crate's directory.
- The Debug trait was implemented for the `HeaderC` type. This enables failing property tests to be reported as C source code rather than a Rust data structure.
- The ArrayDimensionC type is now used in header generation for union, struct, and basic declarations.
Thanks for taking a look and for any feedback!
Closes #1169
r? @fitzgen
=> Enable Cargo features for quickchecking crate

src/lib.rs
Trying to address issue  #1182.
r? @fitzgen
=> Fix command_line_flags mis-generation of rust-target's flags.

src/lib.rs
rust-lang-nursery/rustup.rs#1294 added a proxy executable for rustfmt that will act on the correct bundled rustfmt for the default release channel set by rustup.
And, assuming I'm reading the expected release notes correctly, it seems like rust 1.23, due out fairly shortly, will add the bundled version of rustfmt to stable.
This fixes #1184
=> Revert to only calling plain rustfmt

book/src/cpp.md
This should close https://github.com/rust-lang-nursery/rust-bindgen/issues/1172 . It's my first contribution to the book, so I hope it's not too far from expected usage!
=> Mark C++ exceptions as unsupported in the book

src/options.rs
This PR makes the "CARGO_PKG_VERSION" env variable optional, which facilitates crate compilation using tools other than Cargo.
=> Make CARGO_PKG_VERSION option_env!, rather than env!

src/ir/context.rs
Unfortunately we can't test it for the same alignment issues that "long double"
has.
I also included the diagnostic code, just in case it happens again.
=> ir: Handle _Complex _Float128 correctly.

Cargo.lock, Cargo.toml, src/lib.rs
I'll need it to format some stuff on mozilla-central.
=> lib: Add a way to override rustfmt path.

bindgen-integration/build.rs, bindgen-integration/cpp/Test.h, src/callbacks.rs, src/ir/var.rs
This is symmetric, yet less powerful, than enum_variant_behavior.
Fixes #687.
=> callbacks: Introduce MacroParsingBehavior to allow ignoring macros.

src/lib.rs
Also, perform `clang` parameter check earlier. If that results in `is_cpp == true`, the later `|=` operations could be elided.
=> Check for more common C++ header file extensions

src/lib.rs
=> lib: Use #[deprecated] properly.

Cargo.lock, Cargo.toml, src/lib.rs, src/options.rs
They do nothing, and are effectively superseded by --raw-line and friends.
They also tend to confuse people.
Closes #104
=> options: Remove the linking-related options.

Cargo.toml, src/lib.rs
- Link to the user's guide from the docs and manifest
- Include README.md in Cargo package so it is visible on crates.io and docs.rs.
- Include LICENSE in Cargo package so that the package is legal to distribute.
=> Make some docs more visible

README.md
=> Match tag line on github in README to downplay implied reliability of binding to C++

src/codegen/mod.rs, src/features.rs, src/lib.rs, tests/expectations/tests/bitfield-enum-basic.rs, tests/expectations/tests/enum-doc-bitfield.rs, tests/expectations/tests/issue-1198-alias-rust-bitfield-enum.rs
=> optionally use associated constants in bitfields

bindgen-integration/build.rs, bindgen-integration/src/lib.rs, src/codegen/mod.rs, src/lib.rs
=> Add an option to add lines per module.

src/lib.rs
This is just a small PR to fix the "semvar" typo to "semver".
=> Fix typo in `clang_version` documentation

csmith-fuzzing/predicate.py
This let me add a test function which called a method in the reduced
code, preventing creduce from eliminating everything entirely.
=> Add an option to extend the compiled code after each reducing step

book/src/tutorial-5.md, book/src/whitelisting.md, src/callbacks.rs, src/clang.rs, src/codegen/mod.rs, src/ir/comment.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/derive.rs, src/lib.rs, src/time.rs
This does change a struct field and a couple of functions, but I don't believe that those are publicly exposed.
=> Fix typos.

bindgen-integration/cpp/Test.h, src/codegen/mod.rs, src/ir/context.rs, src/ir/int.rs, src/ir/layout.rs
=> ir: Don't assume wchar is 2 bytes.

bindgen-integration/cpp/Test.h, src/codegen/helpers.rs, src/codegen/mod.rs, src/ir/context.rs, src/ir/int.rs, src/ir/layout.rs
blob() does care about alignment, so we can get into an architecture where there
are integers where size != align.
This is a tentative fix for servo/servo#21093, though
as mentioned there I couldn't find a repro on my machine.
=> Fix integer_type to actually return integers all the time.

src/features.rs
Eliminates the manual implementation of `From<RustTarget>` for
`RustFeatures`.
My initial implementation of "features" bothered me how this was missing.
=> Track Rust target features with declaration macro

src/clang.rs, src/ir/context.rs, src/ir/item.rs, src/ir/ty.rs
As a first step for issue #119, I modified the only call where we created a NullCursor to pass a None instead.
=> Change a call to add_item that was passing a NullCursor.

src/regex_set.rs
RegexSet uses `regex::RegexSet` internally since https://github.com/rust-lang-nursery/rust-bindgen/commit/51f5162f250a5ec10bc5ba8b91b60b45762bc999, which implements the method described in the comment.
=> Remove an out-of-date comment in RegexSet.

src/options.rs
before, `bindgen -- -I blah` would try to open `-I` as a header file, leading to a very confusing error message.
The "real" use case behind this is described here: https://github.com/NixOS/nixpkgs/pull/45330
I have checked that these ways of passing args still work/error as expected:
```
bindgen a.h
bindgen a.h --
bindgen a.h -- -Dblah=1
bindgen -- -Dblah=1
bindgen --
bindgen
```
=> options: mark clang-args last

src/lib.rs
Clang doesn't allow `=` between `-x` and the language name.
=> Fix args_are_cpp to look for -x without =

Cargo.lock, Cargo.toml, src/codegen/mod.rs, src/ir/ty.rs, src/lib.rs, src/options.rs, tests/expectations/tests/blocks-signature.rs, tests/headers/blocks-signature.hpp
Since #1378 broke a bunch of OSX builds.
Most people don't care about them and they're in some OSX system headers which
means that this could break normal C and C++ stuff.
This introduces --generate-block / generate_block to generate these signatures,
and adds tests so that this is getting tested.
=> Put blocks behind a switch.

src/codegen/mod.rs
=> Skip bitfield unit tests on big-endian platforms.

book/src/tutorial-1.md
The version listed in the tutorial quite old (0.26.3) and I used it without thinking when following the tutorial. It'd be nice if it were more up to date.
=> Docs: Update bindgen version in tutorial.

src/lib.rs
Looks like the accepted argument has always been "functions", and this output has always been "function".
=> Fix Builder::command_line_args() --generate typo

bindgen-integration/build.rs, bindgen-integration/cpp/Test.cc, bindgen-integration/cpp/Test.h, bindgen-integration/src/lib.rs, src/callbacks.rs, src/ir/item.rs
=> Add item_name parse callback.

.github/ISSUE_TEMPLATE.md, Cargo.toml, README.md
There is also one broken link in the github project details (that I think can not be changed with a pull request).
=> Update broken links: Rust-lang-nursery => Rust-lang

bindgen-integration/build.rs, bindgen-integration/cpp/Test.h, src/callbacks.rs, src/ir/var.rs
This is the minimum necessary change to have a str_macro in analogy to the int_macro callback. Unlike int_callback, this can't change anything about how code is generated, but it is still usable to influence the build system based on it. For example, in the course of [making Rust usable on the RIOT embedded operating system](https://github.com/RIOT-OS/RIOT/issues/9799), I'd print `cargo:rustc-config=riot_board="..."` from bindgen with a value from a string define.
=> callbacks: Allow reporting string macros

src/clang.rs, src/ir/context.rs, src/ir/var.rs
Instead of converting all the tokens to utf-8 before-hand, which is costly, and
allocating a new vector unconditionally (on top of the one clang already
allocates), just do the tokenization more lazily.
There's actually only one place in the codebase which needs the utf-8 string,
all the others can just work with the byte slice from clang.
This should have no behavior change, other than be faster. In particular, this
halves the time on my machine spent on the test-case from #1465.
I'm not completely sure that this is going to be enough to make it acceptable,
but we should probably do it regardless.
=> clang: Tokenize more lazily.

src/ir/context.rs, src/lib.rs, src/regex_set.rs
I welcome suggestions on better ways to report warnings.
cc #1055
=> Warn about unused whitelist options

Cargo.lock, Cargo.toml, src/codegen/mod.rs, src/ir/analysis/derive_copy.rs, src/ir/analysis/derive_debug.rs, src/ir/analysis/derive_default.rs, src/ir/analysis/derive_hash.rs, src/ir/analysis/derive_partialeq_or_partialord.rs, src/ir/analysis/has_destructor.rs, src/ir/analysis/has_float.rs, src/ir/analysis/has_type_param_in_array.rs, src/ir/analysis/has_vtable.rs, src/ir/analysis/mod.rs, src/ir/analysis/sizedness.rs, src/ir/analysis/template_params.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/dot.rs, src/ir/objc.rs, src/lib.rs
I did a bit of profiling today, for no good reason. I wanted to get rid of some of our hash maps from before hand so it's good to know that this really helps.
```
$ time ./bindgen-old tests/stylo.hpp --no-rustfmt-bindings >/dev/null 2>&1                                                                                                                           
./bindgen-old tests/stylo.hpp --no-rustfmt-bindings > /dev/null 2>  6.06s user 0.76s system 98% cpu 6.912 total
$ time ./bindgen-new tests/stylo.hpp --no-rustfmt-bindings >/dev/null 2>&1                                                                                                                                      
./bindgen-new tests/stylo.hpp --no-rustfmt-bindings > /dev/null 2>&1  4.51s user 0.63s system 98% cpu 5.198 total
```
=> Some perf tweaks

src/ir/comment.rs
Fixes https://github.com/rust-lang/rust-bindgen/issues/1480
=> Remove deprecated calls to trim_(right|left)_matches

CHANGELOG.md, src/codegen/helpers.rs, src/codegen/mod.rs, src/features.rs, src/ir/comp.rs, tests/expectations/tests/issue-537-repr-packed-n.rs, tests/headers/issue-537-repr-packed-n.h
Fixes https://github.com/rust-lang/rust-bindgen/issues/537.
=> Support #[repr(packed(N))] on Rust 1.33+

book/src/blacklisting.md, book/src/cpp.md, book/src/replacing-types.md, book/src/tutorial-2.md
* Some pages of the book's documentation markdown pages used `.html` in their links rather than `.md`.  This evidently works with `mdBook`, but fails when viewing the pages of the book from the Github source tree.
* The `.html` links were replaced with `.md` to fix this.
Since Google searches often end up leading to the non-GH pages version of the book, this change makes it a lot easier for users to navigate between different pages of the book when viewing it through Github directly.
=> Fix book links when viewing via Github

.gitignore, src/lib.rs
Prior to this change bindgen would simply print any error that occurred
while attempting to run rustfmt straight to stderr using `fmt::Debug`.
Combined with the fact that rustfmt is enabled by default now this meant
that if rustfmt was missing or not working a cryptic error would be
printed.
Without this patch:
```
$ PATH= ./target/debug/bindgen /tmp/foo.h
Custom { kind: Other, error: StringError("Cannot find binary path") }
/* automatically generated by rust-bindgen */
```
With this patch:
```
$ PATH= ./target/debug/bindgen /tmp/foo.h
Failed to run rustfmt: Cannot find binary path (non-fatal, continuing)
/* automatically generated by rust-bindgen */
```
I changed the error handling to use `fmt::Display` instead, since this
is user-visible output, and also added "Failed to run rustfmt:" …
=> Produce a more useful error message when rustfmt can't be found. Fixes #1205

Cargo.lock, Cargo.toml
This reverts commit 0d004a726d932cec27d94499e48bc7e3943cb457, reversing
changes made to 2a01e8d499d71e596e4b02f8fd6897f061405e1a.
Fixes #1504.
=> Revert #1489.

src/codegen/mod.rs, tests/expectations/tests/blocks-signature.rs, tests/expectations/tests/blocks.rs, tests/headers/blocks.hpp
The block pointer with one argument 
```objc
bool foo(void (^)(size_t bar));
```
should be generated as `*const ::block::Block<(usize,), ()>` instead of `*const ::block::Block<(usize), ()>`
=> fix one argument block pointer issue, #1378

src/lib.rs, src/options.rs
And don't do it conditionally on the presence of --target. We pass the clang
arguments to clang-sys now, so it doesn't get the wrong path.
Fixes #1542.
=> options: Add an option to opt-out of include path detection.

src/lib.rs
`command_line_flags` returns an invalid option `--default-enum-variant` which I replaced with the right `--default-enum-style`
=> updated `default-enum-variant` to `default-enum-style`

rustfmt.toml
Running `cargo fmt` or `cargo +nightly fmt` gives the following warnings:
```
Warning: Unknown configuration option `fn_brace_style`
Warning: Unknown configuration option `item_brace_style`
Warning: Unknown configuration option `struct_lit_multiline_style`
Warning: Unknown configuration option `where_trailing_comma`
```
rustfmt changed these options here, and this PR reflects the changes:
* `fn_brace_style` and `item_brace_style` were folded into `brace_style`: https://github.com/rust-lang/rustfmt/commit/f8074b340d328513077b59084e0ea3856181e699#diff-6d8a5e2104954a026de2bfe2b936aea4R541
* `struct_lit_multiline_style` option was renamed to `struct_lit_single_line`: https://github.com/rust-lang/rustfmt/commit/45d4f7a2dd1c95e47d4ae4dc413dfb71e53c16ff#diff-9de0a570da3404ffd4b364ef6a9f8195L1749 …
=> Update rustfmt.toml options for compatibility with modern rustfmt

book/src/tutorial-1.md
Hello 👋,
This PR is just a minor suggestion to update bindgen's version to the latest as per [crates.io](https://crates.io/crates/bindgen).
Thanks for the great work :-)
=> Update bindgen version

Cargo.toml
This allows to opt out of clap support if you're using the lib version of bindgen.
=> Make clap optional.

src/ir/ty.rs, tests/expectations/tests/blocks-signature.rs, tests/expectations/tests/blocks.rs, tests/headers/blocks.hpp
=> Make TypeKind::BlockPointer's canonical type in IR be itself

src/ir/ty.rs, tests/expectations/tests/incomplete-array-padding.rs, tests/expectations/tests/zero-sized-array.rs, tests/headers/incomplete-array-padding.h
So as to not pad stuff incorrectly, or needlessly add extra alignment, for
example.
Fixes #1589
=> ir: Properly find the layout of incomplete arrays.

src/codegen/mod.rs, src/ir/context.rs, src/ir/int.rs
This is a breaking cheange since WChar is exposed, but should be no behavior
change otherwise.
=> Cleanup wchar_t layout computation to happen later.

ci/script.sh, src/lib.rs
=> Allow to override rustfmt path with an environment variable.

.travis.yml, Cargo.toml, ci/script.sh, src/lib.rs
This PR adds a new feature, enabled by default, called `which-rustfmt`. When enabled, this feature enables using the `which` crate to search for the `rustfmt` binary. `which` is now an optional dependency. Disabling this feature trims some dependencies in the case that bindings are generated at build time and never checked in.
This PR changes the API of `rustfmt_path` to return `Result<Option<Cow<PathBuf>>>`.
Ok(None) is returned in the case where `which` is disabled and no `rustfmt` command is
supplied explicitly either via configuration or env variable.
Downstream code checks for the presence of None to directly return the source without
emitting an error.
Fixes GH-1614.
I named the feature `which-rustfmt` instead of `which` because the feature is tied to the functionality, not the …
=> Add a feature to make which dependency optional

Cargo.lock, Cargo.toml, src/lib.rs
=> fxhash -> rustc-hash

src/ir/analysis/has_vtable.rs, src/ir/analysis/sizedness.rs, src/ir/derive.rs
See https://github.com/rust-lang/rust/issues/64710.
Bogus implementations were introduced in 230545e7c, d3e39dc62, and 379bb1663.
=> ir: Make Ord and PartialOrd implementations agree.

src/lib.rs
Implements #1628.
If the `which-rustfmt` feature isn't enabled, assume that the binary is
called "rustfmt" and that it is in the user's PATH, instead of returning
an error.
=> Fallback: call "rustfmt" directly without which

src/codegen/helpers.rs, src/codegen/mod.rs, src/features.rs, tests/expectations/tests/use-core.rs
`c_void` is available as `::std::os::raw::c_void` and
`::core::ffi::c_void`. If the "--use-core" option is specified (but no
--ctypes-prefix is provided), we should emit `::core::ffi::c_void`
rather than the `std` one.
Addresses #1584
=> Use c_void from core when --use-core is specified

src/ir/context.rs
For the remaining named parts of Context::gen.
resolve_typerefs in particular takes 177 ms on my machine when running bindgen on Gecko.
=> Add a couple more timers.

src/ir/context.rs
=> Don't always output translation_unit timer.

Cargo.lock, Cargo.toml, src/ir/context.rs, src/ir/item.rs, src/lib.rs
In an opt build this doesn't make much difference, but in a debug build it brings down the runtime for bindgen on Gecko from 30 seconds to 20 seconds.  Ideally we'd build the style crate build script with optimizations, but for now this is useful.
=> Cache the result of Item::path_for_whitelisting.

Cargo.toml
=> Turn off regex default features.

src/codegen/mod.rs, tests/expectations/tests/class.rs, tests/expectations/tests/class_1_0.rs, tests/expectations/tests/derive-hash-struct-with-incomplete-array.rs, tests/expectations/tests/incomplete-array-padding.rs, tests/expectations/tests/issue-643-inner-struct.rs, tests/expectations/tests/layout_align.rs, tests/expectations/tests/layout_large_align_field.rs, tests/expectations/tests/libclang-9/class.rs, tests/expectations/tests/libclang-9/class_1_0.rs, tests/expectations/tests/libclang-9/derive-hash-struct-with-incomplete-array.rs, tests/expectations/tests/libclang-9/incomplete-array-padding.rs, tests/expectations/tests/libclang-9/issue-643-inner-struct.rs, tests/expectations/tests/libclang-9/layout_align.rs, tests/expectations/tests/libclang-9/zero-sized-array.rs, tests/expectations/tests/zero-size-array-align.rs, tests/expectations/tests/zero-sized-array.rs
Flexible array members are represented in the generated binding by a
`struct __IncompleteArrayField<T>`. Since such members do not contain any
information about how big they are, it is impossible to automatically
clone or copy them, either in C or rust.
It looks like the implementation for `Copy` has already been removed with #1477. This change removes the remaining implementation for `Clone`.
Fixes #1431.
=> Do not generate implementation for clone for FAM

Cargo.lock, Cargo.toml
This should fix the issue with parsing some int literals, see https://github.com/jethrogb/rust-cexpr/pull/17.
=> Update cexpr dependency

src/codegen/mod.rs, src/features.rs, tests/expectations/tests/constructor-tp.rs, tests/expectations/tests/constructors_1_33.rs, tests/expectations/tests/gen-constructors.rs, tests/expectations/tests/issue-447.rs, tests/expectations/tests/issue-807-opaque-types-methods-being-generated.rs, tests/expectations/tests/libclang-3.8/partial-specialization-and-inheritance.rs, tests/expectations/tests/var-tracing.rs, tests/headers/constructors_1_33.hpp
Hi,
this solves #1660
I added a new rust_target 1.36 which will replace `mem::uninitialized()` with `MaybeUninit`.
should we use `mem::zeroed()` instead of uninitialized? this might be a little more safe in some small cases (i.e. scalar primitives and raw pointers only)
=> Add support for MaybeUninit

src/codegen/mod.rs, tests/expectations/tests/class.rs, tests/expectations/tests/class_1_0.rs, tests/expectations/tests/derive-hash-struct-with-incomplete-array.rs, tests/expectations/tests/incomplete-array-padding.rs, tests/expectations/tests/issue-643-inner-struct.rs, tests/expectations/tests/layout_align.rs, tests/expectations/tests/layout_large_align_field.rs, tests/expectations/tests/libclang-9/class.rs, tests/expectations/tests/libclang-9/class_1_0.rs, tests/expectations/tests/libclang-9/derive-hash-struct-with-incomplete-array.rs, tests/expectations/tests/libclang-9/incomplete-array-padding.rs, tests/expectations/tests/libclang-9/issue-643-inner-struct.rs, tests/expectations/tests/libclang-9/layout_align.rs, tests/expectations/tests/libclang-9/zero-sized-array.rs, tests/expectations/tests/zero-size-array-align.rs, tests/expectations/tests/zero-sized-array.rs
Closes #1670 
this way the `as_*ptr()` functions are no longer unsafe and don't use transmute.
(and as a bonus one less clippy warning :) )
(seems like changes in `rustfmt` affected this PR)
=> Replace transmute with `as` casting for pointers

ci/assert-warnings.sh, ci/script.sh, src/features.rs, src/lib.rs
Always building with `deny(warnings)` leads to messups such as
https://docs.rs/crate/bindgen/0.52.0/builds/199624
=> Move warnings check on the CI

src/codegen/mod.rs, src/lib.rs
Rustdoc was treating doc comments containing `#[non_exhaustive]`
as links and warning, so escape it.
Cargo doc builds without warnings after this change.
=> Fix warning on rustdoc

src/codegen/mod.rs, tests/expectations/tests/blocks-signature.rs, tests/expectations/tests/blocks.rs, tests/expectations/tests/issue-1498.rs, tests/expectations/tests/jsval_layout_opaque.rs, tests/expectations/tests/jsval_layout_opaque_1_0.rs, tests/expectations/tests/layout_array.rs, tests/expectations/tests/msvc-no-usr.rs, tests/expectations/tests/nsBaseHashtable.rs
=> Remove size_t to usize conversion

src/features.rs
Now that rust 1.40 is out non_exhaustive is supported in stable. This makes the latest stable rust 1.40 and gives it the non_exhaustive feature
=> Update latest stable rust to 1.40 and give non_exhaustive feature

src/ir/objc.rs, tests/expectations/tests/objc_method.rs, tests/headers/objc_method.h
This closes #1703 and adds the rare needed feature of non-keyword methods from objective-c method declarations.
=> Added non-keyword support to objective-c methods for 1703

src/codegen/struct_layout.rs, tests/expectations/tests/issue-1291.rs, tests/expectations/tests/issue-648-derive-debug-with-padding.rs, tests/expectations/tests/layout_array.rs, tests/expectations/tests/layout_array_too_long.rs, tests/expectations/tests/layout_kni_mbuf.rs, tests/expectations/tests/layout_large_align_field.rs, tests/expectations/tests/layout_mbuf.rs, tests/expectations/tests/libclang-5/call-conv-field.rs, tests/expectations/tests/libclang-9/call-conv-field.rs, tests/expectations/tests/unknown_attr.rs
See individual commits for details.
Fixes #1709.
=> Avoid unnecessary padding in some cases.

book/src/faq.md
@emilio this PR adds a section "How to deal with bindgen generated padding fields?" to the FAQ as discussed in #1709.
=> Add how to deal with bindgen padding fields.

book/src/cpp.md
`book/src/cpp.md` can have little a typo fix, as a treat.
=> fix documentation typo

book/src/cpp.md
https://en.wikipedia.org/wiki/Substitution_failure_is_not_an_error
=> Fix written-out form of SFINAE

src/ir/context.rs
I spent an afternoon scratching my head on this one before I ran
into https://github.com/rust-lang/rust-bindgen/issues/1728.
Since the error message welcomes PRs...maybe this will help save other people time by adding this to the list of things to check?
=> propose adding host v. target architecture mismatch to problem list

src/main.rs
This allows avoiding large numbers of system calls to dynaload clang
to determine its version, when no action is performed, for example:
- When calling `--version` / `-V`
- When calling `--help`
This improves the raw responsiveness from:
Before:
```
time bindgen --help # 0.593s
strace -cf bindgen --help # 83k syscalls, 64k to statx
```
After:
```
time bindgen --help # 0.004s
strace -cf bindgen --help # 90 syscalls
```
However, it does mean that you can no longer obtain the discovered
clang version with:
```bash
RUST_LOG=info bindgen -V
```
But this may be remedied in a future commit.
Closes: https://github.com/rust-lang/rust-bindgen/issues/1736
=> Delay invoking clang version checks until a functional path is taken

Cargo.lock, Cargo.toml
This moves us from nom 4 to nom 5.
=> Update to cexpr 0.4

src/codegen/mod.rs, src/ir/objc.rs, tests/expectations/tests/libclang-3.8/objc_template.rs, tests/expectations/tests/libclang-3.9/objc_template.rs, tests/expectations/tests/libclang-4/objc_template.rs, tests/expectations/tests/libclang-5/objc_template.rs, tests/expectations/tests/libclang-9/objc_template.rs, tests/expectations/tests/objc_category.rs, tests/expectations/tests/objc_class.rs, tests/expectations/tests/objc_class_method.rs, tests/expectations/tests/objc_interface.rs, tests/expectations/tests/objc_interface_type.rs, tests/expectations/tests/objc_method.rs, tests/expectations/tests/objc_method_clash.rs, tests/expectations/tests/objc_property_fnptr.rs, tests/expectations/tests/objc_protocol.rs, tests/expectations/tests/objc_whitelist.rs
I took a whack at doing a bit of #109. There hasn't been much movement on the issue so I wanted some feedback on some of the trait constraints generated.
Here's a summary of the changes:
* Each objective-c interface `Foo` now has a `struct_Foo` which wraps the `id` as mentioned in #109. 
* I removed `impl interface_Foo for id { all_the_trait_fns }` and replaced it with `pub trait interface_Foo { all_the_trait_fns }`, and added `impl interface_Foo for struct_Foo { }`. This allows some of the simple inheritance.
* I added trait constraints of `Sized + std::ops::Deref + objc::Message`, to mimic the [objc-foundation crate](https://github.com/SSheldon/rust-objc-foundation/blob/15f9ebec1190889e48a4bc2d36601e61d303071f/src/object.rs#L10).
* Added an `impl struct_Foo { fn alloc() {...}}` for …
=> Higher level objective-c support.

book/src/tutorial-1.md
using version 0.51.1 would trigger a build error like:
```
|
|         .parse_callbacks(Box::new(bindgen::CargoCallbacks))
|                                            ^^^^^^^^^^^^^^ not found in `bindgen`
```
when using sample from tutorial.
=> Update to latest version of bindgen

book/src/SUMMARY.md, book/src/objc.md
I wrote up some of the pain points for using bindgen stuff for objective-c frameworks (specifically for iOS). Full disclosure, I'm not the best at writing how-to guides so comment away.
This is also mildly dependent on #1750 as objective-c class inheritance is mentioned.
Should I work on adding a simple block example to close #1386?
Anyway, here's the bulk of the PR [Rendered](https://github.com/simlay/rust-bindgen/blob/objc-docs/book/src/objc.md).
=> Initial objective-c docs

src/codegen/mod.rs, src/lib.rs
As talked about in #1554, this intends to make it clear that non_exhaustive doesn't solve the UB problem and recommends using the newtype enum style instead of both types of rustified enum.
=> Indicate possible undefined behaviour in rustified enum docs and point to alternative

src/lib.rs
I believe this should fix #1265.
=> Generator docs: add note about clang documentation string options + minor tweaks

.travis.yml, README.md, ci/script.sh
Write down the minimal supported Rust version in the README.md and add a CI test that ensures MSRV bumps cannot happen accidentally. No promises about MSRV bumps in minor versions are given.
The test intentionally removes `Cargo.lock` as the MSRV problem becomes most important when `bindgen` is used as a library dependency, and `Cargo.lock` is not used in that case anyway.
Fixes #1758.
=> Readme/CI: mention and test the MSRV

src/codegen/mod.rs, tests/expectations/tests/blacklist-function.rs, tests/headers/blacklist-function.hpp
We should not emit Rust struct methods corresponding to a C++ method
unless we are actually emitting a binding for that method.
Resolves #1774
=> Do not emit Rust method wrapper for blacklisted functions

README.md
Mention BINDGEN_EXTRA_CLANG_ARGS and clang-sys variables.
Follow-on to #1795
=> Document environment variables in README

book/src/cpp.md
While `std::*` makes informal sense, the user may be mislead into calling `opaque_type("std::*")` instead of the correct `opaque_type("std::.*")` (as I was).
=> Fix regex to be marked opaque

bindgen-integration/build.rs, bindgen-integration/cpp/Test.h, src/callbacks.rs, src/clang.rs, src/ir/var.rs
Closes #1792.
Because whitespace information is not represented explicitly during parsing, it is non-trivial to reconstruct the exact textual form of the macro from the token list. I had previously inserted whitespace between tokens, which I still believe would be correct and acceptable, but it seems that spelling the tokens separately would be better.
Given this input :
```c
#define jit_get_note(n,u,v,w)	_jit_get_note(_jit,n,u,v,w)
```
and this callback :
```rust
fn func_macro(&self, name: &str, value: &[&[u8]]) {
dbg!(name);
dbg!(value);
}
```
this sort of output is achieved (pseudo-code) :
```rust
name = "jit_get_note(n,u,v,w)"
value = &[ "_jit_get_note", "(", "_jit", ",", "n", ",", "u", ",", "v", ",", "w", ")" ]
```
=> Add a callback for function-like macros

build.rs
Closes #1766.
Using a crate that uses `bindgen`([`lightning-sys`](https://github.com/Petelliott/lightning-sys)), I first confirmed that the following Bash script does not trigger any rebuilds after the first build finishes successfully.
```bash
cargo build
LIBCLANG_PATH="" cargo build
cargo build
```
Then I updated that crate's `Cargo.toml` to point `bindgen` to 18e2fbd6953f56cc5b9751691d596663a2029932 and ran the script again. As expected, the second build failed due to `clang_sys` not finding any libclang, and the third build succeeded like the first one, updating the `bindings.rs` file timestamp.
=> Rebuild bindgen and bindings when clang_sys environment changes

build.rs
This is a fix for a tiny edge case, in the spirit of #1766, to support the flag added in #1537.
I looked for other `env!` and `env::var` instances in `bindgen` itself and did not find anything else to change.
=> Respect changes to BINDGEN_EXTRA_CLANG_ARGS

src/lib.rs
For command_line_flags(), some arguments (like '--no-record-matches')
were added after '--'. The bindgen program would interpret these as
clang args.
=> Output clang args after '--'

src/lib.rs
This itched me when reviewing #1816. Seems easier to switch those to
loop over `get_items()`, but this patch also deduplicates the code a
bit, because all that copy-pasta was also itching me.
These flags don't have ordering dependencies, so the result builder
should be equivalent.
=> lib: Stop using count() to do for loops.

src/lib.rs, src/main.rs
Output from Builder::command_line_flags() would fail if more than one
header were provided. This adds extra headers via the '-include' clang
option.
=> Handle multiple headers for command_line_flags()

src/ir/function.rs, tests/expectations/tests/operator.rs, tests/headers/operator.hpp
This PR closes #1292 and replaces it, if desired.
=> Allow non-operator functions whose names start with `operator`

src/ir/comp.rs
In [Rust 1.45.0](https://blog.rust-lang.org/2020/07/16/Rust-1.45.0.html), [`std::mem::replace` has the `#[must_use]` attribute](https://doc.rust-lang.org/1.45.0/std/mem/fn.replace.html) (which was [not present in Rust 1.44.1](https://doc.rust-lang.org/1.44.1/std/mem/fn.replace.html)), causing a new diagnostic for some `bindgen` code :
error: unused return value of `std::mem::replace` that must be used
--> src/ir/comp.rs:751:17
|
751 | /                 mem::replace(
752 | |                     self,
753 | |                     CompFields::AfterComputingBitfieldUnits {
754 | |                         fields,
755 | |                         has_bitfield_units,
756 | |                     },
757 | |                 );
| |__________________^
|
= note: `-D unused-must-use` implied by `-D …
=> Fix CI for Rust 1.45.0

src/clang.rs, src/codegen/mod.rs, src/codegen/struct_layout.rs, src/ir/context.rs, src/ir/item.rs, src/ir/ty.rs, src/regex_set.rs
This was suggested all the way back in https://github.com/rust-lang/rust-bindgen/issues/363#issuecomment-269513599, but was never implemented. This can be pretty confusing if you're trying to bind to C++, as almost every STL header triggers some of these non-fatal "errors."
=> Change non-fatal errors to warnings

.travis.yml, ci/before_install.sh
Closes #1072 by running a few critical jobs on macOS, but not the whole matrix.
In my experience with Travis in general in the last few years, there has not been a lack of macOS builders as was the case when https://github.com/rust-lang/rust-bindgen/issues/1072#issuecomment-335859660 was written.
**This PR would increase the number of Travis jobs by four, from ~~37 to 41~~ 31 to 35.**
Along the way I refactored `ci/before_install.sh`, making it capable of handling LLVM 9.0.1+ (including 10.0.0). Some of the changes there are not strictly necessary to get macOS builds working again, so let me know if I should pare down the list of changes.
The most significant change here was to set `LIBCLANG_PATH` instead of only `DYLD_LIBRARY_PATH`-plus-a-copy. Perhaps it would be better not to set …
=> Reintroduce some macOS builds to Travis-CI

.travis.yml, ci/before_install.sh
Since Ubuntu 16.04 LTS builds of LLVM are available for each major `libclang` version supported by `bindgen`, it could be worthwhile to point to those instead of Ubuntu 14.04 as before.
For LLVM 10.0.0, Ubuntu builds are available for only 18.04, so the current PR might help to prepare for that transition later.
Using LLVM 5.0.1 instead of 5.0.0 avoids the target-triple mixup that needed a special case for 5.0.0.
=> ci: Explicitly use Ubuntu 16.04

book/src/SUMMARY.md, book/src/nodebug.md, src/codegen/mod.rs, src/ir/analysis/derive.rs, src/ir/annotations.rs, src/ir/context.rs, src/lib.rs, src/options.rs, tests/expectations/tests/no_debug.rs, tests/expectations/tests/no_debug_bypass_impl_debug.rs, tests/expectations/tests/no_debug_opaque.rs, tests/expectations/tests/no_debug_whitelisted.rs, tests/headers/no_debug.hpp, tests/headers/no_debug_bypass_impl_debug.hpp, tests/headers/no_debug_opaque.hpp, tests/headers/no_debug_whitelisted.hpp
This patch based on [[Close #961] Add --no-debug <regex> flag #1190](https://github.com/rust-lang/rust-bindgen/pull/1190#issue-157563951), thanks [ivanovaleksey](https://github.com/ivanovaleksey)
Add `--no-debug <regex>` and `Builder::no_debug(String)` to supply regexes for matching against types that we should not derive or implement `Debug` for.
Adding this feature involves:
=> Add --no-debug <regex> flag

src/ir/ty.rs, tests/expectations/tests/const_multidim_array_fn_arg.rs, tests/headers/const_multidim_array_fn_arg.h
Fixes https://github.com/rust-lang/rust-bindgen/issues/1849 by making sure that multidimensional arrays are properly marked as being `const`
=> Fix constness of multidimensional arrays

src/ir/comp.rs, src/lib.rs, src/options.rs, tests/expectations/tests/anon-fields-prefix.rs, tests/headers/anon-fields-prefix.h
Allow to use the given prefix for the anon fields instead of `__bindgen_anon_`.
=> Add --anon-fields-prefix option

src/codegen/mod.rs, src/ir/var.rs, src/lib.rs, src/options.rs, tests/expectations/tests/default-macro-constant-type-signed.rs, tests/expectations/tests/default-macro-constant-type-unsigned.rs, tests/expectations/tests/default-macro-constant-type.rs, tests/headers/default-macro-constant-type-signed.h, tests/headers/default-macro-constant-type-unsigned.h, tests/headers/default-macro-constant-type.h
* --default-macro-constant-type could be 'signed' or 'unsigned'
* Its default value is 'unsigned' to use u32/u64
for C macro constants that fit into the u32/u64 ranges.
* For old C libraries that use macros as int/long parameter
and/or return value types, their macros are better declared
as i32/i64 if the values fit the i32/i64 ranges,
to be compatible with c_int/c_long types.
They can use "--default-macro-constant-type signed"
=> Add --default-macro-constant-type

src/ir/context.rs
This will prevent common issues in platforms where the Rust target is
not the clang target, like aarch64-apple-darwin (Rust) vs.
arm64-apple-darwin (Clang).
We may want to special-case those too when cross-compiling, in the
future.
=> context: Don't pass --target=rust-target to clang when building for the host.

src/ir/context.rs, src/lib.rs
Because the --target was passed after the include path detection, in
cases of cross-compilation, the include path detection would add paths
relevant to the host (e.g. /usr/include/x86_64_linux-gnu on x86_64 linux
while targeting something else), possibly breaking things along the way.
=> Add --target to the clang args earlier

book/src/objc.md, src/codegen/mod.rs, tests/expectations/tests/objc_class_method.rs, tests/expectations/tests/objc_interface_type.rs, tests/expectations/tests/objc_method.rs, tests/expectations/tests/objc_pointer_return_types.rs, tests/headers/objc_pointer_return_types.h
This closes #1835.
This change seems too easy and really only works because the generated `structs` are `#[repr(transparent)]`.
I tested it with UIKit in my iced branch, and [this is the changeset](https://github.com/simlay/iced/commit/9c20c700360eeefc7880543609e94357d3f81a97).
I also added some more documentation to highlight this change. [Rendered](https://github.com/simlay/rust-bindgen/blob/0e887111a210395b724ced1eccaa6b3e2b711a9f/book/src/objc.md).
Also, I'd like to mention that this is definitely a breaking change to any crates that take advantage of the objective-c generated bindings. After a little bit of searching on crates.io, I can't really find any published crates that do this. Perhaps I'm the only one?
=> Added Bindgen names to objective-c pointer return types for #1835.

Cargo.lock, Cargo.toml, README.md, ci/script.sh
~~First, an update:~~
~~Due to issues where incompatible versions of `clang-sys` pulled in by different versions of `bindgen` would be rejected by Cargo due to duplicate [`package.links` Cargo manifest keys](https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key), I have today published the following patch releases for previous minor versions of `clang-sys` so that they can co-exist peacefully (for more info, see [this issue](https://github.com/KyleMayes/clang-sys/issues/96)):~~
* ~~`v0.29.4`~~
* ~~`v0.28.2`~~
* ~~`v0.27.1`~~
~~However, this was accomplished with a hack, essentially republishing `clang-sys` under a different name (`clang-sys-linkage`) as `v1.0.0` and then re-exporting that crate from the above patch versions.~~
**EDIT:** Unfortunately the …
=> Update to clang-sys 1.0.0

src/lib.rs
Fixes #1211.
Unfortunately other than a unit test, this requires hardware of setting up yet another testing crate for cross-compiling to one of the architectures where this happens...
=> lib: Fix inferred target when clang target differs from rust target.

CHANGELOG.md, Cargo.lock, Cargo.toml, src/codegen/mod.rs, tests/expectations/tests/enum-default-bitfield.rs, tests/expectations/tests/enum-default-consts.rs, tests/expectations/tests/enum-default-module.rs, tests/expectations/tests/enum-default-rust.rs, tests/expectations/tests/enum.rs, tests/expectations/tests/enum_explicit_type_constants.rs, tests/expectations/tests/issue-1025-unknown-enum-repr.rs, tests/headers/enum-default-bitfield.h, tests/headers/enum-default-consts.h, tests/headers/enum-default-module.h, tests/headers/enum-default-rust.h, tests/headers/enum.h
=> codegen: Do generate unnamed enums, as they can be referred to by members and others.

src/ir/context.rs, src/ir/function.rs, tests/expectations/tests/libclang-3.9/wasm-constructor-returns.rs, tests/expectations/tests/libclang-4/wasm-constructor-returns.rs, tests/expectations/tests/wasm-constructor-returns.rs, tests/headers/wasm-constructor-returns.hpp
=> Added constructor return type for wasm32 target

CHANGELOG.md, src/codegen/mod.rs, tests/expectations/tests/libclang-3.9/objc_inheritance.rs, tests/expectations/tests/libclang-3.9/objc_template.rs, tests/expectations/tests/libclang-4/objc_inheritance.rs, tests/expectations/tests/libclang-4/objc_template.rs, tests/expectations/tests/libclang-5/objc_inheritance.rs, tests/expectations/tests/libclang-5/objc_template.rs, tests/expectations/tests/libclang-9/objc_inheritance.rs, tests/expectations/tests/libclang-9/objc_template.rs, tests/expectations/tests/objc_category.rs, tests/expectations/tests/objc_class.rs, tests/expectations/tests/objc_class_method.rs, tests/expectations/tests/objc_interface.rs, tests/expectations/tests/objc_interface_type.rs, tests/expectations/tests/objc_method.rs, tests/expectations/tests/objc_method_clash.rs, tests/expectations/tests/objc_pointer_return_types.rs, tests/expectations/tests/objc_property_fnptr.rs, tests/expectations/tests/objc_protocol.rs, tests/expectations/tests/objc_protocol_inheritance.rs, tests/headers/objc_protocol_inheritance.h
First off, I don't wanna spend forever trying to build the perfect objective-c bindings because I think that might never end. I think this PR adds a bit to the ergonomics to the generated bindings.
In this PR, we add
* `impl From<Bar> for Foo` where `Bar` is a subclass of `Foo` in the objective-c. This will be done for all super classes of `Baz`. The reason why this will be nice is that whatever uses these bindings will want to deal with the generics of stuff. In my case, I plan to create UIKit views using specific types (`UILabel`, `UIButton`, `UITextInput`, etc.) and then turn them into a `UIView`. If there's strong push back against this feature, I suppose using a `Box<dyn UIView>` will have to work.
* Changing `unsafe fn methodWithFoo_(self, foo: Foo)` to `unsafe fn …
=> [Objc] Add From<ChildClass>, TryFrom<ParentClass>, function ownership updates and Protocol inheritance

Cargo.lock
Updates `clang-sys` to `1.0.1`.
All this does is [improve the panic message when calling an unloaded function](https://github.com/KyleMayes/clang-sys/commit/ddd3af568ed76a2af94bcc3a9fd06af8e00fec99#diff-2d74931467e5d712980323de36ae6e86R158-R163) since a user requested this change after [encountering the previous panic message](https://github.com/KyleMayes/clang-sys/issues/116).
=> Bump clang-sys to 1.0.1

Cargo.lock
Version 1.0.3 of clang-sys fixes an issue that was causing upstream builds on macOS 11.0 to fail when it couldn't find LLVM configs properly.
https://github.com/KyleMayes/clang-sys/blob/master/CHANGELOG.md#102---2020-11-17
https://github.com/KyleMayes/clang-sys/pull/118
=> Update clang-sys dependency (for macOS Big Sur 11.0 compatibility)

CONTRIBUTING.md, tests/tests.rs
Hello, as you might know, you can already set BINDGEN_OVERWRITE_EXPECTED=1
Now, you can set BINDGEN_OVERWRITE_EXPECTED=meld (assuming you have [meld](https://meldmerge.org/) installed to get a nice graphical view of the changes.
=> Added option to hand check test differences.

src/codegen/dyngen.rs, src/codegen/mod.rs, tests/expectations/tests/dynamic_loading_simple.rs, tests/expectations/tests/dynamic_loading_template.rs, tests/expectations/tests/dynamic_loading_with_blacklist.rs, tests/expectations/tests/dynamic_loading_with_class.rs, tests/expectations/tests/dynamic_loading_with_whitelist.rs, tests/headers/dynamic_loading_with_whitelist.hpp
Right now trying to generate a dynamic library with variadic functions
panics because we don't account for the extra `...` in the arguments.
Keeping the current interface for variadic functions is tricky, as we
cannot "wrap" a variadic function (VaList[1] is nightly-only).
However, we don't need to. We're already exposing the libloading error,
so exposing the function pointer field as public is just fine and allows
consumers to call the variadic function.
At that point the can_call() / CheckFoo libraries become pointless (you
can just do library.function.is_ok() or such), so we can simplify the
code as well removing those.
[1]: https://doc.rust-lang.org/std/ffi/struct.VaList.html
=> dyngen: Handle variadic functions.

book/src/SUMMARY.md, book/src/nodefault.md, src/codegen/mod.rs, src/ir/analysis/derive.rs, src/ir/annotations.rs, src/ir/context.rs, src/lib.rs, src/options.rs, tests/expectations/tests/no_default.rs, tests/expectations/tests/no_default_bypass_derive_default.rs, tests/expectations/tests/no_default_opaque.rs, tests/expectations/tests/no_default_whitelisted.rs, tests/headers/no_default.hpp, tests/headers/no_default_bypass_derive_default.hpp, tests/headers/no_default_opaque.hpp, tests/headers/no_default_whitelisted.hpp
Sometimes, we need customize the implement of `Default` for certain types,
In these cases, the `nodefault` annotation can be used to prevent bindgen
to autoderive the `Default` traits for a type.
=> Add --no-default <regex> flag

src/lib.rs
Fixes #1919, as otherwise we peek the wrong include paths unless you
pass "-x c++" or such.
=> lib: Improve c++ auto-detection.

src/codegen/mod.rs, src/codegen/struct_layout.rs, src/ir/comp.rs, tests/expectations/tests/divide-by-zero-in-struct-layout.rs, tests/expectations/tests/packed-n-with-padding.rs, tests/headers/packed-n-with-padding.h
This can cause unnecessary padding to be computed otherwise at the end
of the struct.
With repr(packed(n)), a field can have padding to adjacent fields as
long as its alignment is less than n. So reuse the code we have to align
to a field layout, aligning to the struct layout instead.
Fixes #1934
=> struct_layout: Fix field offset computation for packed(n) structs.

src/lib.rs, src/options.rs, tests/expectations/tests/namespace.rs, tests/headers/namespace.hpp
This makes command_line_args properly return them, instead of dropping
them on the floor.
=> cli: Expose module_raw_lines to the CLI.

src/codegen/dyngen.rs, tests/expectations/tests/dynamic_loading_simple.rs, tests/expectations/tests/dynamic_loading_template.rs, tests/expectations/tests/dynamic_loading_with_blacklist.rs, tests/expectations/tests/dynamic_loading_with_class.rs, tests/expectations/tests/dynamic_loading_with_whitelist.rs
=> dyngen: Pass null-terminated byte strings to libloading.

src/ir/context.rs, tests/expectations/tests/keywords.rs, tests/headers/keywords.h
=> context: Escape the dyn keyword properly.

src/clang.rs, src/codegen/mod.rs, src/ir/comp.rs, src/lib.rs, src/options.rs, tests/expectations/tests/no_debug_whitelisted.rs, tests/expectations/tests/private_fields.rs, tests/headers/private_fields.hpp
=> Generate fields as non-pub if they would be access restricted in C++.

bindgen-integration/cpp/Test.cc, bindgen-integration/cpp/Test.h, bindgen-integration/src/lib.rs
https://github.com/rust-lang/rust-bindgen/pull/1973
```
failures:
---- test_homogeneous_aggregate_float_union stdout ----
thread 'test_homogeneous_aggregate_float_union' panicked at 'assertion failed: `(left == right)`
left: `[1.0, 2.0, 3.0, 4.0]`,
right: `[0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000029021264197102883, 0.0, 0.0, 0.0]`', src/lib.rs:268:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> Add failing regression test for #1973.

.github/workflows/bindgen.yml, bindgen-integration/src/lib.rs, ci/test.sh
Uses [run-on-arch-action](https://github.com/uraimo/run-on-arch-action) to run tests in CI on a virtualized AArch64 environment. This slows down CI quite a bit, but if it were up to me I'd say it's worth the trade-off, since this could surface some critical issues on a soon-to-be tier 1 platform. Hopefully GitHub will release native integration with AArch64 in the future such that this slowness is temporary.
=> Run tests on AArch64 in CI

book/src/requirements.md
This adds instructions for using bindgen on the OpenBSD platform.
=> OpenBSD requirements

.github/workflows/bindgen.yml, ci/test.sh
This is a re-implementation of #1980, as described in my comment on that pull request.
I'm not sure if you'll want to merge this because it has advantages and disadvantages:
Pros:
- Runs in about 3 minutes, instead of over 30 minutes
- Easy to add other architectures as long as Ubuntu supports them
Cons:
- Only runs the integration tests on aarch64, not the full test suite - because the build script runs on x86_64 (and uses the x86_64 LibClang), but the tests run on aarch64 (and would require an aarch64 LibClang).
cc @frewsxcv
=> Implement AArch64 tests with Debian multiarch and QEMU

src/lib.rs
Previously the function assumed that the version number appeared in the
third word. This PR adds a heuristic - take the first word that starts
with a number.
This way we can also parse: 
* Debian clang version 11.0
* Apple clang version 12.0.0
=> Make clang version parsing logic more robust

tests/tests.rs
Should fix the test failures described in #1991 and #1975 on modern Mac.
=> tests: Guess modern libclang version when we fail to parse a version.

Cargo.lock, Cargo.toml
This upgrades the [shlex](https://docs.rs/shlex) dependency from version 0.1 to 1. The breaking change in shlex 1 is a fix for [a correctness bug](https://github.com/comex/rust-shlex/issues/6). I haven't looked closely at how shlex is used in bindgen so it should probably be made sure that this doesn't break anything that relied on the incorrect behavior.
=> Upgrade to shlex 1

src/ir/analysis/derive.rs, src/lib.rs, src/options.rs, tests/expectations/tests/issue-1454.rs, tests/headers/issue-1454.h, tests/tests.rs
Fixes #1454
I also prototyped adding the following method to `ParseCallbacks` but I think this PR is nicer:
```rust
/// This will be called to determine whether a particular blocklisted type
/// implements a trait or not. This will be used to implement traits on
/// other types containing the blocklisted type.
///
/// * `None`: use the default behavior
/// * `Some(true)`: `_name` implements `_derive_trait`
/// * `Some(false)`: `_name` doesn't implement `_derive_trait`
fn blocklisted_type_implements_trait(
&self,
_name: &str,
_derive_trait: DeriveTrait
) -> Option<bool>;
```
=> Add flag to ignore type blocklist when computing derive information

src/codegen/mod.rs, src/lib.rs, src/options.rs, tests/expectations/tests/enum-translate-type.rs, tests/headers/enum-translate-type.hpp
=> Add option to translate enum integer types to native Rust integer types

src/ir/context.rs, src/ir/enum_ty.rs, tests/expectations/tests/parsecb-anonymous-enum-variant-rename.rs, tests/headers/parsecb-anonymous-enum-variant-rename.h, tests/parse_callbacks/mod.rs, tests/tests.rs
Prior to this PR, this header
```c
enum {
MyVal = 0,
};
```
in combination with `allowlist_var("^MyVal$")` and an implementation of `ParseCallbacks::enum_variant_name` would generate no code. This is because the renamed variant name is checked against the variable allowlist. All other allowlist checks are against the unrenamed name. This PR makes that consistent. This is a breaking change but I think the old behavior is clearly wrong.
Additionally, I've added a way to test ParseCallbacks in CI.
=> Use original name when checking allowlist for anonymous enum variants

src/codegen/dyngen.rs, tests/expectations/tests/dynamic_loading_simple.rs, tests/expectations/tests/dynamic_loading_template.rs, tests/expectations/tests/dynamic_loading_with_allowlist.rs, tests/expectations/tests/dynamic_loading_with_blocklist.rs, tests/expectations/tests/dynamic_loading_with_class.rs
The `new` method of generated dynamic library structs only allows to load library in a standard way. But under some circumstance a user might want to load the dynamic library with some platform-specific parameters (https://docs.rs/libloading/0.7.0/libloading/os/index.html).
This PR adds a `from_library` method that accepts an already loaded `Library` instance.
=> Add from_library for generated dynamic library structs

src/callbacks.rs, src/ir/analysis/derive.rs, src/ir/context.rs, tests/expectations/tests/issue-1454.rs, tests/headers/issue-1454.h, tests/parse_callbacks/mod.rs
Fixes #1454 #2003
This includes #2006 because it needs the ParseCallbacks testing framework
=> Add callback to check derives for blocklisted types

src/codegen/dyngen.rs, src/codegen/mod.rs, src/lib.rs, src/options.rs, tests/expectations/tests/dynamic_loading_required.rs, tests/expectations/tests/dynamic_loading_template.rs, tests/expectations/tests/dynamic_loading_with_allowlist.rs, tests/expectations/tests/dynamic_loading_with_blocklist.rs, tests/expectations/tests/dynamic_loading_with_class.rs, tests/headers/dynamic_loading_required.h
Currently, `bindgen` allows symbols to go unresolved when loading a dynamic library, only to panic later when a function call is attempted against an unresolved symbol.
Instead, it'd be better to return an error code when we detect an unresolved symbol while loading the library, thereby avoiding any unforeseen runtime errors.
In addition, this will also allow us to save function pointers on our struct instead of a `Result`, saving us the cost of having to unwrap the `Result` every time we make a function call.
---
I'm expecting some criticism from the way I've changed the `quote!` calls, and I'm all for suggestions on how to change the code for the better.
Ideally there would be a way to branch on a conditional, inline in the `quote!` macro, but I haven't seen a way to do so yet.
In …
=> Add a flag to ensure all symbols are resolved when a dynamic library is loaded

book/src/requirements.md
Installation instructions are currently provided for `apt`-based platforms, but there is no mention of `dnf`-based platforms.
Verified on my Fedora 33 install with `dnf provides /usr/lib64/libclang.so`.
=> Document clang installation method on Fedora

src/codegen/mod.rs, tests/expectations/tests/issue-1995.rs, tests/headers/issue-1995.h
As a first contribution, here's a small and possibly quite naive fix and test for #1995  :)
=> Fix docstring comment for constants

README.md, build.rs, src/lib.rs
Closes #2009
As suggested in the issue, I've done it the same way the `cc` crate does it in its [`get_var`](https://github.com/alexcrichton/cc-rs/blob/c8b47ee8b53a57a505ecd0f0981c1bb3b4b58fb4/src/lib.rs#L2180) function.
=> Add env var EXTRA_CLANG_ARGS_<TARGET>

Cargo.lock, Cargo.toml, bindgen-integration/build.rs, bindgen-integration/cpp/Test.h, src/codegen/mod.rs, src/deps.rs, src/ir/context.rs, src/ir/item.rs, src/lib.rs, src/options.rs, tests/expectations/tests/enum-default-rust.d, tests/tests.rs
The motivation here is being able to use bindgen [during a ninja build] without losing dependency information.
I'm not particularly happy with the approach I've taken of wrapping ParseCallbacks. The main alternative I see is to have the parse callbacks separated into a concrete type and a trait object, and to always collect filenames in the struct. I'm open to suggestions for better ways to collect the needed metadata, though.
[during a ninja build]: https://fuchsia-review.googlesource.com/c/fuchsia/+/510318
=> Support emitting Makefile-syntax depfiles like gcc/clang/rustc.

src/ir/function.rs, src/ir/item.rs, tests/expectations/tests/libclang-3.9/template_instantiation_with_fn_local_type.rs, tests/expectations/tests/template_instantiation_with_fn_local_type.rs, tests/headers/template_instantiation_with_fn_local_type.hpp
This fixes a panic with the following header:
template<typename T>
struct Foo {};
template<typename T>
Foo<T> foo{};
void f() {
struct Bar {
Bar() {}
};
foo<Bar>;
}
Because we don't parse the insides of function bodies, code like this could
cause us to parse a type (here, `Bar`) that we didn't see in our initial pass,
which can cause subtle problems.
Closes #2036.
=> Translate types that were declared inside functions as opaque types.

src/codegen/mod.rs, src/codegen/struct_layout.rs, src/lib.rs, src/options.rs, tests/expectations/tests/explicit-padding.rs, tests/headers/explicit-padding.h
If a struct needs to be serialized in its native format (padding bytes and all), for example writing it to a file or sending it on the network, then explicit padding fields are necessary, as anything reading the padding bytes of a struct may lead to Undefined Behavior.
This allows structs with padding to be compatible with `zerocopy::AsBytes`, as well as the more dangerous practice of `transmute` to a byte array.
Who would want such a crazy thing? Well, it turns out that there are a bunch of data structures in the Postgres code base that are written to files in their native memory format, non-portable padding and all. To be able to read and write those files we can use `serde` or `zerocopy`, but in either case we need the padding fields to be explicit.
This change is a bit more …
=> Allow explicit padding

bindgen-integration/build.rs, bindgen-integration/src/lib.rs, src/callbacks.rs, src/codegen/mod.rs
This callback allows us to specify arbitrary derive attributes for each named struct. This is useful for adding things that can't easily be implemented separately, such as `serde::Deserialize` or `zerocopy::FromBytes`.
This addresses the easiest cases of #1089.
There aren't any tests yet-- I'm not sure what the best way would be to test this, since it can't be reduced to a command line.
=> add custom derives callback

src/ir/comp.rs, src/ir/item.rs, tests/expectations/tests/canonical-types.rs, tests/expectations/tests/layout_cmdline_token.rs, tests/expectations/tests/nested-template-typedef.rs, tests/headers/canonical-types.hpp, tests/headers/nested-template-typedef.hpp
In some esoteric cases involving nested templates,
`ty.declaration().definition()` isn't enough to find the definition: we need
`ty.canonical_type().declaration().definition()` instead.
Closes #2078.
r? @emilio
=> Canonicalize types before looking for their definitions.

book/src/SUMMARY.md, book/src/must-use-types.md, src/codegen/mod.rs, src/ir/annotations.rs, src/ir/context.rs, src/lib.rs, src/options.rs, tests/expectations/tests/issue-710-must-use-type.rs, tests/headers/issue-710-must-use-type.h
This PR adds an option to generate `#[must_use]` annotations as described in #710.
=> Implement #710, must-use for types.

src/codegen/mod.rs, tests/expectations/tests/enum-default-bitfield.rs, tests/expectations/tests/enum-default-consts.rs, tests/expectations/tests/enum-default-module.rs, tests/expectations/tests/enum-default-rust.rs, tests/expectations/tests/enum-no-debug-rust.rs, tests/expectations/tests/enum.rs, tests/headers/enum-no-debug-rust.h, tests/headers/enum.h
This enables users to add additional derives, or prevent deriving traits.
Fixes #2076
=> Use annotations on enumerations

src/ir/context.rs, tests/expectations/tests/qualified-dependent-types.rs, tests/headers/qualified-dependent-types.hpp
These can happen in certain cases involving incomplete qualified dependent
types. To avoid looping forever, we need to check for them.
Closes #2085.
r? @emilio
=> Detect and avoid cycles when resolving items.

src/ir/context.rs, tests/expectations/tests/keywords.rs, tests/headers/keywords.h
When trying to compile redbpf, there are errors because the code contains the try keyword
=> context: Escape the try keyword properly

bindgen-integration/build.rs, bindgen-integration/cpp/Test.h, bindgen-integration/src/lib.rs, src/codegen/mod.rs
Custom derives are just as useful on enums as they are on structs; not supporting this was an oversight.
Adds a test that will fail to compile if the custom derive doesn't work on enums. This test fails without the codegen fix.
Fixes #2116.
=> allow custom derives on enums

src/codegen/mod.rs, src/features.rs, tests/expectations/tests/libclang-3.9/constant-evaluate.rs, tests/expectations/tests/libclang-4/constant-evaluate.rs, tests/expectations/tests/libclang-5/constant-evaluate.rs, tests/expectations/tests/libclang-9/constant-evaluate.rs, tests/expectations/tests/macro_const_1_0.rs, tests/headers/macro_const_1_0.h
Constant and static declaration have a 'static live time by default,
that is already elided since 1.17.
Clippy complains on this kind of strings that are present in the
generated code.
This patch remove the 'static live time for those strings.
Fix #1612
Signed-off-by: Alberto Planas <aplanas@suse.com>
=> Drop 'static for pub const strings

CONTRIBUTING.md, book/src/blocklisting.md, src/clang.rs, src/ir/context.rs, src/ir/item.rs, src/lib.rs, src/options.rs, tests/expectations/tests/blocklist-file.rs, tests/headers/blocklist-file.hpp, tests/headers/blocklisted/fake-stdint.h, tests/headers/blocklisted/file.hpp
Update Item to hold a `clang::SourceLocation` and use this to allow
blocklisting based on filename.
The existing code has a special case that always maps <stdint.h> integer
types to corresponding Rust integer types, even if the C types are
blocklisted.  To match this special case behaviour, also treat these
C <stdint.h> types as being eligible for derived Copy/Clone/Debug
traits.
Fixes #2096
=> Add --blocklist-file option

src/ir/context.rs, src/ir/function.rs, src/lib.rs
The CI couldn't pass due to `rustc` issued "field is never read" warnings, so I have fixed it.
=> Remove fields never read

book/src/cpp.md
`bindgen`'s inability to currently support RVO should be noted in C++ bindings generation document.
The issue is complex and definitely not easily summarised but better to still mention something about it than leave it out. Optionally the cpp.md could also link to Issue #778.
=> Add note about RVO in cpp.md

.github/workflows/bindgen.yml, src/ir/analysis/mod.rs, src/lib.rs, tests/tests.rs
I forgot to fix some warnings in `cfg(test)` in #2111 because they can't seen on CI, but I found them by running `cargo clippy -- --cfg test` and fixed.
=> Fix warnings on tests

src/lib.rs
Resolve issue #2136
Runnings `cargo test` on a SiFive Unmatched with Ubuntu worked successfully.
=> Handle difference between clang and rust targets on RISC-V

src/codegen/mod.rs, tests/expectations/tests/enum-no-debug-rust.rs
=> codegen: Don't automatically derive Debug and Copy for non-rust enums.

bindgen-integration/build.rs, src/codegen/helpers.rs
Adding a custom derive like "serde::Deserialize" results in a panic complaining
that it is not a valid Ident. Derive params are not identifiers, so treat it as
a token stream instead.
Relates to  #1089
=> Allow fully-qualified derives

src/codegen/mod.rs, src/lib.rs, src/options.rs, tests/expectations/tests/enum_and_vtable_mangling.rs, tests/expectations/tests/nested_vtable.rs, tests/expectations/tests/ref_argument_array.rs, tests/expectations/tests/virtual_interface.rs, tests/expectations/tests/virtual_overloaded.rs, tests/expectations/tests/vtable_recursive_sig.rs, tests/tests.rs
* Put behind flag as per discussion in the original PR.
* Use pointers as per #2163.
=> Minor vtable tweaks.

src/lib.rs
Hey
This might be a start to fix this issue. Bare with me :)
I created a `Bindings::generate_common()` that i call from `Bindings::generate()`but im unsure if i used the right "parts" of `generate()` and possibly where we should call the `Bindings::generate_common()` to avoid BINDGEN_EXTRA_CLANG_ARGS being evaluated after `dump-preprocessed-input()`
=> issue 1723

src/codegen/mod.rs, src/features.rs, src/ir/function.rs, tests/expectations/tests/win32-vectorcall-1_0.rs, tests/expectations/tests/win32-vectorcall-nightly.rs, tests/headers/win32-vectorcall-1_0.h, tests/headers/win32-vectorcall-nightly.h
Adds support for the `vectorcall` ABI on x86_64 platforms. I have mostly
followed the implementation of the `thiscall` ABI. Similar to `thiscall`,
`vectorcall` is feature-gated and only available on nightly. There is no
tracking issue for the `abi_vectorcall` feature (not sure why).
r? @emilio
=> Add support for `vectorcall` ABI

book/src/tutorial-5.md
The "sanity test" example contains one `panic!()` with wrong argument type (`i32` instead of string literal) that produces warning on recent rust compilers:
```
arning: panic message is not a string literal
--> src/lib.rs:52:59
|
52 |                 r if r == (BZ_PARAM_ERROR as _) => panic!(BZ_PARAM_ERROR),
|                                                           ^^^^^^^^^^^^^^
|
= note: `#[warn(non_fmt_panics)]` on by default
= note: this usage of panic!() is deprecated; it will be a hard error in Rust 2021
= note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/panic-macro-consistency.html>
help: add a "{}" format string to Display the message
|
52 |                 r if r == (BZ_PARAM_ERROR as _) => panic!("{}", BZ_PARAM_ERROR),
| …
```
=> Fix wrong panic!() argument type (quote it)

src/codegen/mod.rs, tests/expectations/tests/packed-vtable.rs
It's impossible to #[derive] from any other trait when not deriving from
Copy when using the newest Rust nightly. Any attempt to do that results
in the following error:
```
error: `#[derive]` can't be used on a `#[repr(packed)]` struct that does not derive Copy (error E0133)
```
Fixes: #2083
Signed-off-by: Michal Rostecki <vadorovsky@gmail.com>
=> Derive from any other trait only when deriving from Copy

.github/workflows/bindgen.yml, .github/workflows/deploy-book.yml
The v2 implementation uses Node 12, which is end-of-life on April 30, 2022. See https://nodejs.org/en/about/releases/. Update to v3, which is based on Node 16 whose support lasts until April 30, 2024.
=> Update GitHub Actions actions/checkout@v2 to v3

book/src/tutorial-3.md
The information is fundamental when working with shared libraries but is never explicitly mentioned. 
Without, it is very possible to get stuck trying to import `lib<name>.so` with `println!("cargo:rustc-link-lib=lib<name>");` which will not work (as it happened to me).
=> Provide information how to link to shared objects

csmith-fuzzing/predicate.py
Fixes a `TypeError: 'NoneType' object is not iterable` ocurring if certain parameters are supplied.
=> Fix TypeError error in predicate.py

Cargo.lock
Via:
$ cargo update -p clang-sys
Contains a fix that was preventing me from running bindgen in my env.
Link: https://github.com/KyleMayes/clang-sys/issues/138
Link: https://github.com/KyleMayes/clang-sys/pull/142
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
=> upgrade clang-sys from 1.2.0 to 1.3.3

.github/workflows/bindgen.yml, build.rs, src/codegen/mod.rs, src/ir/context.rs, src/ir/item.rs, src/lib.rs
The Github Actions flow is showing "Unchanged files with check annotations" for each PR. This PR can mechanically remove some of those warnings, and avoid some of the rest by [an improved invocation of `clippy`](https://github.com/rust-lang/rust-clippy/issues/1436#issuecomment-462059561).
=> Fix some clippy warnings

bindgen-integration/.gitattributes, tests/.gitattributes, tests/expectations/tests/.gitattributes
I noticed that Github interprets `rust-bindgen` as a C++ project, due to the many C++ input headers. I find this misleading and undesirable.
The use of `.gitattributes` for Github's Linguist is described in [`linguist/docs/overrides.md`](https://github.com/github/linguist/blob/02ffab2d4df3034c05fd7b2e8bf0a2fd31c0452d/docs/overrides.md).
The changes in this PR are certainly debatable; if they are not loved, I am happy to withdraw them.
=> Ignore test inputs/outputs for Github Linguist

src/options.rs
=> options: Implement --version manually and print clang version on --version --verbose

src/options.rs
Both `Arg::value_name` and `Arg::number_of_values` imply `Arg::takes_value`, so those calls are just noise.
=> Don't use `Arg::takes_value` when it's implied by other calls.

.github/workflows/bindgen.yml, Cargo.toml, README.md
Fixes #2235.
bindgen depends upon `clap` 3.0.4 which depends upon [`os_str_bytes` ^6.0.0][o]. The latter released [version 6.2.0][s] a few hours ago and its MSRV increased to 1.57.0.
Technically bindgen's MSRV does not have to increase (because its [`Cargo.lock` pins `os_str_bytes` to version 6.0.0][pin]) but the way that the bindgen MSRV CI job is written suggests that updating the MSRV of bindgen is the simplest and most expected solution.
I elected not to make any changes to `Cargo.lock` in this PR, but maybe they could be made in a separate one.
[o]: https://crates.io/crates/clap/3.0.4/dependencies
[s]: https://crates.io/crates/os_str_bytes/versions
[pin]: https://github.com/rust-lang/rust-bindgen/blob/master/Cargo.lock#L234-L236
=> Bump MSRV to 1.57.0

src/ir/ty.rs, tests/expectations/tests/pointer-attr.rs, tests/headers/pointer-attr.h
Using the canonical type fixes this but changes the output of some tests
(in particular, pointer to typedefs now point to the underlying type).
So do this only in known-bad cases.
Fixes #2244
=> ty: Use canonical type to access pointee.

src/ir/context.rs
While compiling bindings for libdevmapper (the device-mapper userspace library) using rust-bindgen 0.59.0 I get a rustc error due to the headers using a Rust reserved word, `await`:
```
Compiling libdevmapper v0.1.0 (/home/breeves/rust/libdevmapper)
error: expected identifier, found keyword `await`
--> /home/breeves/rust/libdevmapper/target/debug/build/libdevmapper-9675fe9b031b9984/out/bindings.rs:9118:9
|
9118 |         await: *mut f64,
|         ^^^^^ expected identifier, found keyword
|
help: escape `await` to use it as an identifier
|
9118 |         r#await: *mut f64,
|         ++
error: expected identifier, found keyword `await`
--> /home/breeves/rust/libdevmapper/target/debug/build/libdevmapper-9675fe9b031b9984/out/bindings.rs:9126:9
|
9126 |         await: *mut f64,
|         ^^^^^ …
```
=> adds 'await' to list of matches in 'rust_mangle'

tests/expectations/tests/keywords.rs, tests/headers/keywords.h
Add declarations for 'await' and 'async' variables to keywords.h and update the expectations in keywords.rs.
=> Add test coverage for 'await' and 'async' keywords

CONTRIBUTING.md
test-one.sh needs to run `dot` command which is installed via Graphviz.
Else, running the script throws error - `dot` command not found.
cc @pvdrz
=> docs(CONTRIBUTING): add a note for single test run

src/codegen/mod.rs, src/ir/context.rs, src/lib.rs, tests/expectations/tests/allowlist_warnings.rs, tests/headers/allowlist_warnings.h, tests/tests.rs
This PR introduces a way to store warning messages inside `Bindings` so they can be emitted later. This allows `bindgen` to use `cargo:warnining=MESSAGE` in build scripts to show warnings and still produce warning log entries (which means this PR would fix https://github.com/rust-lang/rust-bindgen/issues/2167). 
We still have some questions about this that we would like to resolve before promoting this to a non-draft PR:
Apparently cargo won't print warnings for crates.io dependencies unless `-vv` is passed (https://github.com/rust-lang/cargo/issues/3777). I decided to float the warning messages all the way up and add a `Bindings::take_warnings` method so the user can print them directly in the build script. I also added a `print_warnings` macro to ease this process.
cc @amanjeev
Edit: As …
=> Print warnings when allowlist doesn't match anything

src/clang.rs, src/ir/comp.rs, tests/expectations/tests/issue-2239-template-dependent-bit-width.rs, tests/headers/issue-2239-template-dependent-bit-width.hpp
libclang's API does not provide a straightforward way to check for this, and calling clang_getFieldDeclBitWidth is actively unsafe in this case. See https://github.com/llvm/llvm-project/issues/56644
We probably can't generate reasonable bindings for such a type, so make the binding opaque.
Ideally libclang would report if the bit width could not be evaluated. Unfortunately making such a change would mean bumping the minimum libclang version from 6.0 to 15.0.
Instead, add logic to traverse the AST subtree starting from the field's bit width specifier looking for template parameters. If we find one, we make the resulting type opaque
Workaround for https://github.com/rust-lang/rust-bindgen/issues/2239
=> Generate opaque type for template param dependent bit field width

CONTRIBUTING.md, src/lib.rs
This PR adds the `BindgenOptions::require_syn` method that can be used to know if we need to parse the generated items with `syn` to do any code manipulation, like sorting semantically.
It also reorganizes the logic inside `Bindings::generate` so we can easily add different passes of code manipulation in the future.
=> add `BindgenOptions::require_syn` method

src/codegen/mod.rs, src/ir/enum_ty.rs, src/lib.rs, src/options.rs, tests/expectations/tests/newtype-global-enum.rs, tests/headers/newtype-global-enum.hpp
=> Add `--newtype-global-enum` option

src/codegen/mod.rs, src/lib.rs, tests/expectations/tests/newtype-global-enum.rs
Apparently https://github.com/rust-lang/rust-bindgen/pull/2270 introduced several bugs:
- The `RegexSet` for `--newtype-global-enum` was not initialized correctly.
- The flag was not emitted when the option was used either.
- The generated bindings did not use a newtype.
All three have been fixed here.
=> Fix `--newtype-global-enum` option

src/clang.rs, src/codegen/mod.rs, src/ir/function.rs, tests/expectations/tests/noreturn.rs, tests/headers/noreturn.h, tests/headers/noreturn.hpp
Partially fixes https://github.com/rust-lang/rust-bindgen/issues/2094
=> Handle no return attributes

src/codegen/helpers.rs, src/features.rs, tests/expectations/tests/core_ffi_c.rs, tests/headers/core_ffi_c.h
Partially fixes: https://github.com/rust-lang/rust-bindgen/issues/2231
r? @emilio @amanjeev
=> use `#[feature(core_ffi_c)]` when available

asd.fish, src/codegen/mod.rs, src/lib.rs, src/options.rs, tests/expectations/tests/blocks-signature.rs, tests/expectations/tests/blocks.rs, tests/expectations/tests/issue-1498.rs, tests/expectations/tests/jsval_layout_opaque.rs, tests/expectations/tests/jsval_layout_opaque_1_0.rs, tests/expectations/tests/layout_array.rs, tests/expectations/tests/msvc-no-usr.rs, tests/expectations/tests/no_size_t_is_usize.rs, tests/expectations/tests/nsBaseHashtable.rs, tests/headers/no_size_t_is_usize.h
=> Map size_t to usize by default and check compatibility [Rebased]

src/ir/context.rs, src/ir/ty.rs, tests/expectations/tests/stdint_typedef.rs, tests/headers/stdint_typedef.h
Fixes #1663.
Not sure if this is too special-casey, but there's already a bunch of this stuff strewn about. Seems like it would be cleanest to add a new `TypeKind` for stdint types populated in `from_clang_ty` but that seemed like a ton of work for relatively little gain.
=> Don't traverse through special-cased <stdint.h> types.

book/src/objc.md, src/codegen/mod.rs, tests/expectations/tests/objc_blocklist.rs, tests/headers/objc_blocklist.h
This PR adds the ability to blocklist Objective-C methods using --blocklist-item. The path format that's matched against is `ItemPath:: rustMethodName`.
The Rust method name is used over the Objective-C name, as it is needed to deal with the ambiguity when class and instance methods share the same name.
=> Enables blocklisting of Objective-C methods

src/deps.rs, src/ir/context.rs, src/lib.rs, src/regex_set.rs
Basically: https://github.com/rust-lang/rust-bindgen/pull/2263#pullrequestreview-1118043962
=> Make `BindgenOptions` clonable

bindgen-tests/tests/expectations/tests/inline_namespace_nested.rs, bindgen-tests/tests/expectations/tests/libclang-5/inline_namespace_nested.rs, bindgen-tests/tests/headers/inline_namespace_nested.hpp, bindgen-tests/tests/tests.rs, bindgen/ir/context.rs
=> context: Fix tokenization of C++20 inline namespace.

CHANGELOG.md, bindgen/clang.rs, bindgen/ir/context.rs, bindgen/lib.rs
This is done by moving all the remaining `Builder` state into `BindgenOptions` so any internal logic that affects `Builder` state only runs once the builder is consumed by `Builder::generate`:
- move `input_headers` to `BindgenOptions`.
- move `input_header_contents` to `BindgenOptions`.
- derive `Clone` for `Builder`.
Fixes: https://github.com/rust-lang/rust-bindgen/issues/2132
=> Implement `Clone` for `Builder`

bindgen-tests/tests/expectations/tests/var-tracing.rs, bindgen/ir/var.rs
This adds a new special case for constants like:
```c
extern const char some_static_string[];
```
so `bindgen` emits a `static` instead of a `static mut` for them.
Fixes: #2290
=> Handle incomplete external array constants

bindgen-cli/main.rs, bindgen/callbacks.rs, bindgen/lib.rs
One of the advantages of doing this is that `ParseCallbacks` no longer needs to implement `UnwindSafe` which means that users can rely on `RefCell` and `Cell` to extract information from the callbacks.
Users relying on `catch_unwind` can still achieve similar behavior using `std::thread::spawn`.
Fixes #2147.
=> Use panic hooks instead of using `catch_unwind`

bindgen/clang.rs, bindgen/ir/comp.rs, bindgen/ir/ty.rs
In Clang 16, anonymous items may return names like `(anonymous union at ..)` rather than empty names.
The right way to detect them is using clang_Cursor_isAnonymous.
Fixes #2312
Closes #2316
=> clang: Detect anonymous items explicitly, rather than relying on empty names.

bindgen-cli/Cargo.toml, bindgen/Cargo.toml
Travis-CI was fully removed as of faf8b3edbaeb591315fc6f370c1228b8caf9860f.
The only badge now [mentioned in the Cargo book][1] is `maintenance`. The `travis-ci` badge reference was [removed from Cargo two years ago][2]. The Cargo book advises putting badges in README.md instead.
[1]: https://doc.rust-lang.org/cargo/reference/manifest.html#the-badges-section
[2]: https://github.com/rust-lang/cargo/commit/60779a006f98fba1680182c174134363d08e0a9b
=> Remove Travis-CI badges from Cargo.toml

book/src/SUMMARY.md, book/src/visibility.md
I can't see any existing documentation on the `<div rustbindgen private>` documentation so I have added some to the book, demonstrating with examples based on the examples in bindgen-tests/tests/headers/private.hpp.
=> Document visibility annotation

CHANGELOG.md, Cargo.lock, bindgen-cli/Cargo.toml, bindgen-tests/tests/expectations/tests/whitelist-alternates.rs, bindgen-tests/tests/headers/empty-union.hpp, bindgen-tests/tests/headers/forward_declared_opaque.h, bindgen-tests/tests/headers/ord-enum.h, bindgen-tests/tests/headers/whitelist-alternates.h, bindgen/Cargo.toml, bindgen/regex_set.rs
Resolves #1755 by wrapping the regexes provided to a `RegexSet` in a capture group, so the added anchors work properly with alternation.
This doesn't resolve the issue of implicit/hidden regex modifications performed by this crate, which should still be properly documented.
=> Sanitize RegexSet input so alternation is properly handled

CHANGELOG.md, bindgen-cli/main.rs
Apparently I forgot this tiny detail when removing the `catch_unwind` logic. Which means bindgen was suppressing all the panic messages :grimacing:
=> Avoid suppressing panic messages

book/src/cpp.md
The original commit adding this note referenced #778, but then went on to talk about how the problem was RVO and that the problem is not possible to solve in bindgen because bindgen can't know if RVO happened or not. However this is incorrect in several ways. The problem in #778 has nothing whatsoever to do with RVO but rather with bindgen simply not understanding the calling convention for passing or returning types that are "non trivial for the purposes of calls". This is completely consistent and does not depend on what the optimizer decided to do (after all, if callsite side calling-convention did depend on what the optimizer happened to do inside the function it would be impossible for C++ compilers to emit correct calls to external C++ functions!).
You can see this quite clearly …
=> Replace confusing note in cpp.md on "RVO"

book/src/SUMMARY.md, book/src/non-system-libraries.md
fixes https://github.com/rust-lang/rust-bindgen/issues/1299
=> Add tutorial about non-system libraries

bindgen/lib.rs
In some cases, like when processing headers with static inline functions, might be useful to have a mechanism to rerun Bindgen with the same options the user provided.
I'm opening this PR as a first step to solve #1090 and not make a hard to review and huge PR. The idea would be to run bindgen a first time to find any inlined functions, then generate a new `.h` file that wraps the inlined functions and finally run bindgen again using this generated file as an input. 
~~Blocked by: #2302~~
=> Add a mechanism to rerun bindgen with the same user options

CHANGELOG.md, bindgen-cli/options.rs, bindgen-tests/tests/expectations/tests/abi-override.rs, bindgen-tests/tests/headers/abi-override.h, bindgen/codegen/dyngen.rs, bindgen/codegen/mod.rs, bindgen/ir/function.rs, bindgen/lib.rs
This option can be used from the CLI with the <abi>:<regex> syntax and it overrides the ABI of a function if it matches <regex>.
Fixes #2257 as the `".*"` regex can be used to match every function.
=> Add the `--override-abi` option

bindgen/ir/ty.rs, bindgen/ir/var.rs
This fixes #2325.
The issue is that `__bf16` is not exposed at all by libclang, which causes us to crash. It's a bit of a shame libclang doesn't expose it but there's no rust equivalent I think, so this should be ok for now.
Unfortunately no test because the header crashes older clang versions.
=> ir: Don't crash with built-in unexposed types from libclang.

bindgen-tests/tests/expectations/tests/public-dtor.rs, bindgen-tests/tests/headers/constructor-tp.hpp, bindgen-tests/tests/headers/public-dtor.hpp, bindgen/ir/function.rs
Fixes #2158
Checks if definition contains `inline` even if declaration doesn't
Tests have been adjusted
=> Fix inline function identification

bindgen-tests/tests/expectations/tests/duplicated-definition-count.rs, bindgen-tests/tests/headers/duplicated-definition-count.hpp, bindgen/codegen/mod.rs
Even though this change does name deduplication in a slower way, it avoids name collisions without any breaking changes in the test suite.
Fixes #2202
=> Fix duplicated function names

bindgen-tests/tests/expectations/tests/blocklist-methods.rs, bindgen-tests/tests/headers/blocklist-methods.hpp, bindgen/lib.rs
Fixes https://github.com/rust-lang/rust-bindgen/issues/669
=> Document and test allowlisting and blocklisting methods

CHANGELOG.md, bindgen-integration/build.rs, bindgen/callbacks.rs, bindgen/codegen/mod.rs
This PR introduces a new non-exhaustive `struct` called `DeriveInfo` to be used as the sole argument of `ParseCallbacks::add_derives` with the purpose of being able to extend the information passed to this method in a backwards-compatible manner, meaning that adding new fields to `DeriveInfo` won't be a breaking change when releasing a new version.
Some candidates to new fields have been requested already:
- https://github.com/rust-lang/rust-bindgen/issues/2168: Requests for a way to know if a type is PoD and can be safely transmuted from/to bytes.
- https://github.com/rust-lang/rust-bindgen/pull/2328: Could be simplified if the kind of the type (whether a type is a `struct`, `enum` or `union`)  were included.
=> Introduce `DeriveInfo`

CHANGELOG.md, bindgen/callbacks.rs, bindgen/codegen/helpers.rs, bindgen/codegen/mod.rs, bindgen/ir/comment.rs, bindgen/ir/item.rs, bindgen/lib.rs
This method can be used to process comments and replace them with whatever the user wants.
=> Add `ParseCallbacks::process_comment`

bindgen-tests/tests/expectations/tests/objc_escape.rs, bindgen-tests/tests/headers/objc_escape.h, bindgen/ir/objc.rs
Fixes https://github.com/rust-lang/rust-bindgen/issues/2242
=> Escape method fragments that happen to be rust keywords

bindgen-tests/tests/expectations/tests/enum-typedef.rs, bindgen-tests/tests/headers/enum-typedef.h, bindgen/codegen/mod.rs, bindgen/ir/context.rs, bindgen/ir/ty.rs
Fixes #2008.
Example:
```c
enum Enum { Variant };
typedef int16_t Enum;
```
This is valid and idiomatic C (though not valid C++). `cbindgen` uses this idiom as the default C translation of Rust enums, the equivalent of what would be `enum Enum : int16_t { Variant };` in C++.
`bindgen header.h` before:
```rust
pub const Enum_Variant: Enum = 0;
pub type Enum = ::std::os::raw::c_uint;
pub type Enum = i16;
```
```console
error[E0428]: the name `Enum` is defined multiple times
--> generated.rs:3:1
|
2 | pub type Enum = ::std::os::raw::c_uint;
| --------------------------------------- previous definition of the type `Enum` here
3 | pub type Enum = i16;
| ^^^^^^^^^^^^^^^^^^^^ `Enum` redefined here
|
= note: `Enum` must be defined only once in the type namespace of this module
```
After:
```rust …
```
=> Fix name collision between C enum and typedef

bindgen-tests/tests/expectations/tests/inherit_multiple_interfaces.rs, bindgen-tests/tests/expectations/tests/virtual_inheritance.rs, bindgen-tests/tests/headers/inherit_multiple_interfaces.hpp, bindgen-tests/tests/headers/virtual_inheritance.hpp, bindgen/codegen/mod.rs
The bug only affects virtual inheritance, so instead disable layout tests in the test that we know is broken. Not generating layout tests is wrong anyways, because the offset would be wrong.
=> codegen: Do generate field offset checks for classes with multiple virtual methods in bases

CHANGELOG.md, bindgen/lib.rs
Fixes https://github.com/rust-lang/rust-bindgen/issues/2373
=> Extend documentation about deprecation of wildcard patterns

CHANGELOG.md, bindgen-tests/tests/expectations/tests/dynamic_loading_with_class.rs, bindgen-tests/tests/expectations/tests/void_typedef.rs, bindgen-tests/tests/headers/void_typedef.h, bindgen/codegen/dyngen.rs, bindgen/codegen/mod.rs
And reuse a bit more code.
Should fix #2377, but needs a test (can't run tests atm).
=> codegen: Look through typedefs to detect void return type.

CONTRIBUTING.md, bindgen-tests/tests/test-one.sh
Minor and quick fix.  Directory changes have left the fuzzy test runner broken.  Fixing that here.
Since this is a minor fix, I am not assigning this to anyone else but @pvdrz.
cc/ @emilio 
Signed-off-by: Amanjeev Sethi <aj@amanjeev.com>
=> fix: test runner for fuzzy tests and update documentation

book/src/cpp.md
=> Document semantic difference between constructors and wrappers

.github/workflows/bindgen.yml, CHANGELOG.md, Cargo.lock, README.md, bindgen-cli/Cargo.toml, bindgen-cli/options.rs, bindgen-tests/Cargo.toml, bindgen/Cargo.toml
Most other crates (including `cxx`) use clap 4 by now, and bindgen using clap 3 results in multiple versions needing to be maintained in projects which vendor dependencies.
=> Update to clap 4.

.github/workflows/sync-master-from-main.yml
Thank you for paying attention to this issue.  This is the first PR which we will merge into `master`.  I believe we can then open another PR for `main` and at that time switch the default branch to `main`.
#2286
=> Add trigger for push to `main` branch for sync'ing with `master`

CHANGELOG.md, bindgen-cli/Cargo.toml, bindgen-cli/options.rs, bindgen-tests/Cargo.toml, bindgen-tests/tests/expectations/tests/derive-custom-cli.rs, bindgen-tests/tests/headers/derive-custom-cli.h, bindgen/Cargo.toml, bindgen/callbacks.rs, bindgen/codegen/mod.rs, bindgen/lib.rs, bindgen/regex_set.rs
=> Implement cli option for custom derive

bindgen/lib.rs
Fixes #2396.
This makes it possible to workaround cc/bindgen issues with esp-rs projects by using only environment varaibles (TARGET_CC, CLANG_PATH, etc).  Without this, it requires modifying each crate's build.rs that you try to depend on to add a target option passed along to clang.
=> Add *-espidf target triple mappings

bindgen/codegen/serialize.rs, bindgen/lib.rs, clippy.toml
This is a temporary fix for https://github.com/rust-lang/rust-bindgen/issues/2409 in case someone decides to use one of the values that changed in clang 15.
If we really need such values we should figure out how to enable the `clang_sys/clang_15`  feature if clang 15 is present in the system.
=>  Disallow constant values that were changed in clang 15 

book/src/using-bitfields.md
Simple fix for a typo in the docs: "Far each ..." should be "For each ...".
First time opening a PR here, let me know if there is anything else that needs to be done!
=> Fix typo in bitfields documentation

bindgen-tests/tests/expectations/tests/generated/wrap_static_fns.c, bindgen-tests/tests/expectations/tests/wrap-static-fns.rs, bindgen-tests/tests/headers/wrap-static-fns.h, bindgen/codegen/serialize.rs
This PR adds support for enums with the wrapped static functions feature.
I ran the experimental feature on a fairly large C project and got a crash with "Cannot serialize type kind enum"... so I fixed it and test it. Works as expected.
=> Add support for enums with the wrapped static functions feature

bindgen-tests/tests/headers/wrap-static-fns.h, bindgen/codegen/mod.rs
This PR moves the logic for adding an item to be serialized after all the conditions which defines if a Rust extern function will be created are done. This is to make sure that functions are de-duplicated but also that we don't generate C wrapped that won't be used at all.
=> Also de-duplicate functions with wrapped static functions feature

book/src/tutorial-1.md
Users (such as myself) that have enough experience to know to copy dependencies into the `Cargo.toml` file, but not enough to know that they should not add it under `[dependencies]`. Note that searching for the error does point you directly to [this thread](https://users.rust-lang.org/t/bindgen-basic-help/11478) which has a solution, so not like it's particularly difficult to resolve.
I chose this style of block for the warning since it looks alright and by default, neither standard Markdown nor mdbook supports admonishments (though if we really wanted, we could add a preprocessor like [mdbook-admonish](https://tommilligan.github.io/mdbook-admonish/), but that seems like overkill).
Also added the actual error message both for reference and to boost the likelihood that this will capture …
=> Add warning section to build dependency tutorial doc

book/src/requirements.md
Recent versions of Windows 10 and Windows 11 ship with the winget CLI tool, which can be used to install LLVM in a way similar to Linux. This PR adds this option to the requirements docs.
=> Add winget install bindgen setup docs

Cargo.lock
Fixes https://github.com/rust-lang/rust-bindgen/security/dependabot/3
=> Update `tempfile` dependency to avoid vulnerability

bindgen/regex_set.rs
This makes the code more complex than needed.
Part of a clippy lint being developed.
=> Do not build an extra identical structure

bindgen/codegen/postprocessing/merge_extern_blocks.rs, bindgen/codegen/postprocessing/mod.rs, bindgen/codegen/postprocessing/sort_semantically.rs
This PR uses `syn::File` instead of wrapping all the items generated by bindgen into a module.
=> Remove the wrapping mod hack

CHANGELOG.md, bindgen-integration/build.rs, bindgen-tests/tests/expectations/tests/generated/wrap_static_fns.c, bindgen/codegen/mod.rs
Partial fix for https://github.com/rust-lang/rust-bindgen/issues/2445
=> Add `#include` directives with headers for static wrappers

CHANGELOG.md, bindgen-tests/tests/expectations/tests/generated/wrap_static_fns.c, bindgen-tests/tests/expectations/tests/wrap-static-fns.rs, bindgen/codegen/helpers.rs, bindgen/codegen/mod.rs, bindgen/codegen/serialize.rs
=> Let LLVM mangle the link name of static wrappers

bindgen/lib.rs
This PR destructures `BindgenOptions` inside `Builder::command_line_flags` so it is harder for contributors to forget emitting the CLI flags when adding new options and hopefully save some headaches due to the roundtrip tests failing.
=> Make harder to forget to update `Builder::command_line_flags`

bindgen-cli/Cargo.toml, bindgen-tests/Cargo.toml, bindgen/Cargo.toml, bindgen/callbacks.rs, bindgen/lib.rs
This is done to prevent users from thinking this should be an user-facing feature
=> Rename `cli` feature to `__cli`

bindgen/options/mod.rs
The Rust API Guidelines state that macors should keep the input syntax of a macro similar to the Rust syntax when possible.
The `options!` macro input followed this format:
```rust
field: {
ty: Ty,
...
}
```
However, the following syntax should be better:
```rust
field: ty {
...
}
```
This is done because the `options!` macro defines a `struct` and these changes still evoke the common `field: ty` syntax followed by Rust.
See
https://rust-lang.github.io/api-guidelines/macros.html#input-syntax-is-evocative-of-the-output-c-evocative.
=> Apply the C-EVOCATIVE guideline to `options!`

bindgen/codegen/mod.rs, bindgen/ir/context.rs, bindgen/ir/var.rs, bindgen/lib.rs, bindgen/options/mod.rs, bindgen/regex_set.rs
This fixes the `unused_code` warnings that appear when compiling `bindgen` without the `experimental` and `__cli` features.
=> Fix `unused_code` warnings without `experimental`

.github/workflows/bindgen.yml
This workflow runs `cargo check` for the `bindgen` crate without its default features and denies any warnings that occur. This would help us catch any build warnings that happen when building `bindgen` without the CLI and experimental features disabled.
=> Add minimal workflow

CHANGELOG.md, bindgen/clang.rs
A header with
```cpp
#include <stddef.h>
const char S1[] = "Hello";
const unsigned char S2[] = u8"Hello";
const char16_t S3[] = u"Hello";
const char32_t S4[] = U"Hello";
const wchar_t S5[] = L"Hello";
```
will wrongly generate (`-- -std=c++11`)
```rust
pub const S1: &[u8; 6usize] = b"Hello\0";
pub const S2: &[u8; 6usize] = b"Hello\0";
pub const S3: &[u8; 2usize] = b"H\0";
pub const S4: &[u8; 2usize] = b"H\0";
pub const S5: &[u8; 2usize] = b"H\0";
```
since `clang_EvalResult_getAsStr` only works for ordinary and UTF-8 strings. This seems like a `libclang` limitation since there isn't a similar function for other string literal types.
This disables generating code for unsupported string types.
=> Don't generate wrong strings.

CHANGELOG.md, bindgen/callbacks.rs, bindgen/lib.rs
bindgen currently has a `bindgen/build.rs` which attempts to have cargo rebuild bindgen when `TARGET` specific env variables change, specifically `BINDGEN_EXTRA_CLANG_ARGS_<target>`. Unfortunately, this doesn't have the desired effect in most cases.
Specifically, when a crate `A` has `bindgen` in `build-dependencies`, and we're cross compiling `A` for target `T` on a host `H`, `bindgen`'s `build.rs` will observe `TARGET` set to `H` (the host target name) instead of `T` (because `bindgen` itself is being built for `H` and not `T`). Then, within the build script of crate `A`, one would use `bindgen` to generate bindings, and now `TARGET` is set to `T`, so different env variables are used.
Allow crates using `bindgen` in build scripts to correctly handle env variable changes by adding …
=> bindgen::ParseCallbacks: support tracking env variable usage for cargo

CHANGELOG.md, bindgen-tests/tests/expectations/tests/generated/wrap_static_fns.c, bindgen-tests/tests/expectations/tests/wrap-static-fns.rs, bindgen-tests/tests/headers/wrap-static-fns.h, bindgen/codegen/serialize.rs, bindgen/ir/ty.rs
Update the code generation for the `--wrap-static-fns` feature so the wrapper for a static function that returns `void` no longer contains a `return` statement and only calls the function instead.
=>  Do not return when calling void functions 

CHANGELOG.md, bindgen-cli/options.rs, bindgen-tests/tests/expectations/tests/libclang-5/constant-evaluate.rs, bindgen-tests/tests/expectations/tests/libclang-9/constant-evaluate.rs, bindgen-tests/tests/expectations/tests/macro_const.rs, bindgen-tests/tests/expectations/tests/macro_const_1_0.rs, bindgen-tests/tests/expectations/tests/strings_array.rs, bindgen-tests/tests/expectations/tests/strings_cstr.rs, bindgen-tests/tests/headers/strings_array.h, bindgen-tests/tests/headers/strings_cstr.h, bindgen/codegen/helpers.rs, bindgen/codegen/mod.rs, bindgen/features.rs, bindgen/options/mod.rs
~~The `bindgen` MSRV is 1.60.0, `CStr::from_bytes_with_nul` is `const`-stable since 1.59.0.~~
I see that the MSRV is only for compiling `bindgen`, so I added a new target for Rust 1.59 instead of always generating `CStr`s.
There is also a discussion regarding this in https://github.com/rust-lang/rust-bindgen/pull/2369#discussion_r1135967775.
=> Generate `CStr`s instead of byte arrays.

CHANGELOG.md, bindgen-tests/tests/headers/wrap-static-fns.h, bindgen/codegen/mod.rs, bindgen/codegen/serialize.rs
Currently there is no way to generate a wrapper for a static variadic function while using the `--wrap-static-fns` feature.
These changes modify `bindgen`'s behavior so such functions are skipped instead of generating invalid code for them. At the same time, a warning is emitted if the `--emit-diagnostics` feature is enabled.
Fixes #2498
=> Do not wrap static variadic functions

CHANGELOG.md, bindgen/deps.rs
Header file paths included from C/C++ files may include spaces in them, and if they do, the spaces need to be escaped in order to generate a proper depfile. Otherwise, the dep file ends up pointing to non-existant paths.
For example:
../../third_party/depot_tools/win_toolchain/vs_files/27370823e7\Windows Kits\10\Include\10.0.22621.0\shared\winapifamily.h
This path ends up being parsed as two files, neither of which exist: ../../third_party/depot_tools/win_toolchain/vs_files/27370823e7\Windows Kits\10\Include\10.0.22621.0\shared\winapifamily.h
This leads to build failures with ninja when it's verifying that the build is complete:
```
$ ninja -C out rust_mojo_unittests -w dupbuild=err -n -d explain
ninja explain: output ../../third_party/depot_tools/win_toolchain/vs_files/27370823e7\Windows …
```
=> Escape spaces in the depfile output

CHANGELOG.md, bindgen/lib.rs
Broken by #2491 because this is not a feature anymore.
=> Fix Formatter::Prettyplease

book/book.toml
These ones are particularly uncomfortable due to being of large font, in addition to being visible on all pages of the book.
=> backticks are not pretty when not rendered

CHANGELOG.md, bindgen/Cargo.toml, bindgen/lib.rs
This is a partial revert of these two PRs:
- https://github.com/rust-lang/rust-bindgen/pull/2491
- https://github.com/rust-lang/rust-bindgen/pull/2505
Allow formatting of generated bindings and the inclusion of the `prettyplease` dependency to be optional when depending on bindgen as a library.
`prettyplease` remains required and enabled by bindgen-cli.
In a project I maintain, `bindgen` is used in a build script to generate bindings for a native C library. Those bindings are written to `OUT_DIR` and are `include!`'d into the crate sources; these bindings don't need to be formatted.
See for additional context:
- https://github.com/rust-lang/rust-bindgen/pull/2491#issuecomment-1558266335
- https://github.com/rust-lang/rust-bindgen/pull/2491#issuecomment-1559699924
- …
=> Restore prettyplease feature gate to bindgen library crate

bindgen-tests/tests/expectations/tests/default_visibility_private_respects_cxx_access_spec.rs, bindgen-tests/tests/expectations/tests/field-visibility-callback.rs, bindgen-tests/tests/expectations/tests/field-visibility.rs, bindgen-tests/tests/expectations/tests/private_fields.rs, bindgen-tests/tests/headers/field-visibility-callback.h, bindgen-tests/tests/headers/field-visibility.h, bindgen-tests/tests/headers/private_fields.hpp, bindgen-tests/tests/parse_callbacks/mod.rs, bindgen/callbacks.rs, bindgen/codegen/mod.rs, bindgen/codegen/struct_layout.rs, bindgen/ir/annotations.rs
Add a callback mechanism for determining field visibility. This PR includes 2 other related (breaking) behavior changes in the prior commits:
* *Use default visibility for padding fields* Previously, padding fields were always pub. Now, they follow the default visibility for the type they're in.
* *Compute visibility of bitfield unit based on actual field visibility* A bitfield unit field and its related functions now have their visibility determined based on the minimum of the default visibility and the actual visibility of the bitfields within the unit. private < pub(crate) < pub.
=> Field visibility callback

CHANGELOG.md, bindgen-integration/build.rs, bindgen-integration/src/lib.rs, bindgen-tests/tests/expectations/tests/generated/wrap_static_fns.c, bindgen-tests/tests/expectations/tests/wrap-static-fns.rs, bindgen-tests/tests/headers/wrap-static-fns.h, bindgen-tests/tests/parse_callbacks/mod.rs, bindgen-tests/tests/tests.rs, bindgen/callbacks.rs, bindgen/codegen/mod.rs, bindgen/codegen/serialize.rs, ci/no-includes.sh
~~Opening a draft before doing more to get opinion on it.~~
This PR add a way to wrap `va_list` function as variadic function. See below for an example.
Input:
```c
#include <stdarg.h>
static inline int vfoo(int flags, va_list va) {
// ...
return flags;
}
```
Output:
```c
int vfoo__extern(int flags, ...) {
int ret;
va_list ap;
va_start(ap, flags);
ret = vfoo(flags, ap);
va_end(ap);
return ret;
}
```
```rust
extern "C" {
#[link_name = "vfoo__extern"]
pub fn vfoo(flags: ::std::os::raw::c_int, ...) -> ::std::os::raw::c_int;
}
```
Related to https://github.com/rust-lang/rust-bindgen/issues/2498
cc @pvdrz
=> Wrap `va_list` function as variadic function

CHANGELOG.md, bindgen-tests/tests/expectations/tests/allowlist-file.rs, bindgen-tests/tests/expectations/tests/jsval_layout_opaque.rs, bindgen-tests/tests/expectations/tests/jsval_layout_opaque_1_0.rs, bindgen-tests/tests/expectations/tests/layout_arp.rs, bindgen-tests/tests/expectations/tests/layout_array.rs, bindgen-tests/tests/expectations/tests/layout_eth_conf.rs, bindgen-tests/tests/expectations/tests/layout_eth_conf_1_0.rs, bindgen-tests/tests/expectations/tests/namespace.rs, bindgen-tests/tests/expectations/tests/template_instantiation_with_fn_local_type.rs, bindgen/clang.rs, bindgen/deps.rs, bindgen/ir/context.rs, bindgen/ir/item.rs, bindgen/ir/module.rs, bindgen/lib.rs
Extracted from https://github.com/rust-lang/rust-bindgen/pull/2369.
In order to somewhat support `#undef`, code needs to be parsed in the correct order. Previously, all macros were parsed before all variables, making it impossible to reason about whether a variable was declared before or after a macro with the same name.
=> Parse code by source order.

CHANGELOG.md, bindgen-cli/Cargo.toml, bindgen-tests/Cargo.toml, bindgen-tests/tests/expectations/Cargo.toml, bindgen/Cargo.toml
This breaks CLI that people may depend on, so maybe should be part of a new release.
=> avoid implicit Cargo features

CHANGELOG.md, bindgen/lib.rs
Similar problem as the one mentioned in #2136, just continuing by adding the 32 bit risc tuple mappings. Tuples like riscv32imc- and riscv32imac- should map to the clang riscv32- tuple.
Fixed by adding mappings and tests for the mappings. Projects that now failed to build with the "riscv32imac-unknown-none-elf" target tuple now build without issue.
=> Add target mappings for riscv32imc and riscv32imac

bindgen/codegen/error.rs, bindgen/codegen/helpers.rs, bindgen/codegen/mod.rs, bindgen/ir/function.rs, bindgen/ir/layout.rs, bindgen/ir/ty.rs
Extracted from https://github.com/rust-lang/rust-bindgen/pull/2369 for easier review.
=> Use `syn::Type` instead of raw `TokenStream`.

bindgen-tests/tests/expectations/tests/allowlist-file.rs, bindgen-tests/tests/expectations/tests/issue-2556.rs, bindgen-tests/tests/expectations/tests/jsval_layout_opaque.rs, bindgen-tests/tests/expectations/tests/jsval_layout_opaque_1_0.rs, bindgen-tests/tests/expectations/tests/layout_arp.rs, bindgen-tests/tests/expectations/tests/layout_array.rs, bindgen-tests/tests/expectations/tests/layout_eth_conf.rs, bindgen-tests/tests/expectations/tests/layout_eth_conf_1_0.rs, bindgen-tests/tests/expectations/tests/namespace.rs, bindgen-tests/tests/expectations/tests/template_instantiation_with_fn_local_type.rs, bindgen-tests/tests/headers/issue-2556.h, bindgen-tests/tests/headers/issue-2556/LayoutConstants.h, bindgen-tests/tests/headers/issue-2556/nsSize.h, bindgen-tests/tests/headers/issue-2556/nsStyleStruct.h, bindgen/clang.rs, bindgen/lib.rs
This disables (hopefully temporarily, if this is eventually going to be needed)
source order sorting, for causing correctness regressions like #2556, for which
I added a test.
=> clang: Disable source order sorting for now.

bindgen-tests/tests/expectations/tests/libclang-5/issue-2556.rs
For some reason, the expectation test for issue #2556 fails due to clang 5 not being able to compile it.
r? @emilio
=> Fix expectation tests for clang 5

bindgen-tests/tests/expectations/tests/issue-2566-cstr.rs, bindgen-tests/tests/expectations/tests/issue-2566.rs, bindgen-tests/tests/headers/issue-2566-cstr.h, bindgen-tests/tests/headers/issue-2566.h, bindgen/codegen/mod.rs
And fix a crash when strings have interior nulls.
Fixes #2566
=> codegen: Generate CStr only if possible.

CHANGELOG.md, bindgen-tests/tests/expectations/tests/objc_escape.rs, bindgen-tests/tests/headers/objc_escape.h, bindgen/ir/objc.rs
=> Fix escaping for objective-C identifiers

bindgen-cli/options.rs, bindgen/codegen/mod.rs, bindgen/features.rs, bindgen/lib.rs, bindgen/options/mod.rs
This PR refactors the `features` module, replacing the several macros we had for a single one.
This means that when a new version or feature needs to be added, all the changes need to be done in a single place.
cc @emilio, @tshepang
=> Refactor the `features` module

bindgen/clang.rs, bindgen/codegen/mod.rs, bindgen/deps.rs, bindgen/ir/context.rs, bindgen/ir/item.rs, bindgen/lib.rs, bindgen/options/as_args.rs, bindgen/options/mod.rs, bindgen/regex_set.rs
This PR changes all the bindgen options that are collections of `String`s into collections of `Box<str>`.
These changes should slightly diminish the amount of memory used by bindgen which could be relevant for larger projects using it, specially if they use heavily one or more of the following options:
- `Builder::header`.
- `Builder::header_contents`.
- `Builder::raw_line`.
- `Builder::clang_arg` or `Builder::clang_args`.
- Any regex based option.
There are no changes to the public API and this doesn't increase bindgen's codebase complexity other than some `.into_boxed_str()` calls here and there.
cc @tshepang @emilio. These changes are better reviewed commit-per-commit.
=> Turn collections of `String` into collections of `Box<str>`

bindgen/Cargo.toml
docs.rs/bindgen doesn't contain the documentation for things under the `"experimental"` feature. This means that no-one can see the `emit_diagnostics` replacement for `emit_warnings()`. 
This fixes that. I'm not sure if you need to add more features, but feel free to do so.
=> Add "experimental" features to docs.rs

.github/workflows/release.yml, CONTRIBUTING.md, Cargo.lock, Cargo.toml, bindgen-tests/tests/expectations/Cargo.toml
Ease release process by introducing cargo-dist and cargo-release to release flow.
In addition, bindgen-cli is also published as a binary.
=> cargo-dist (and cargo-release)

CHANGELOG.md, bindgen-tests/tests/expectations/tests/generated/wrap_static_fns.c, bindgen-tests/tests/expectations/tests/wrap-static-fns.rs, bindgen-tests/tests/headers/wrap-static-fns.h, bindgen/codegen/serialize.rs
=> Use void in parameterless functions

CHANGELOG.md, bindgen-cli/Cargo.toml
Before we link bindgen with default features including runtime libclang.
After the pr, we can build bindgen-cli with no-defautl-features to link static libclang, such as 'cargo install --locked --no-default-features -F static,logging --path .'
If not , runtime and static feature will be confict reported by the clang-sys.
=> Fix bindgen-cli support link static libclang

CHANGELOG.md, bindgen/callbacks.rs, bindgen/lib.rs
=> Introduce `ParseCallbacks::header_file`

bindgen-cli/options.rs
This PR removes some ad-hoc error propagation that the CLI parser had for more sophisticated arguments and just uses `clap::Error` for everything.
=> Let clap handle all CLI parsing errors

book/src/allowlisting.md
While playing with bindgen, I noticed that the entry for allowlist-item is missing from the official doc. This patch helps add it.
I've checked that the doc for allowlist_* and blocklist_* are up-to-date.
=> [Doc] Add missing entry for allowlist-item.

.github/workflows/publish.yml, CONTRIBUTING.md
This results in requiring a manual button push to publish to crates.io, to avoid having published crates if there is a failed release workflow.
=> publish from GitHub release page

bindgen-cli/options.rs
=> fix(args): make header argument optional

bindgen/ir/item.rs
Context:
- https://github.com/llvm/llvm-project/pull/72401
- https://github.com/llvm/llvm-project/issues/56687
Past versions of Clang have a longstanding bug (11+ years; see https://stackoverflow.com/questions/11865486/clang-ast-extern-linkagespec-issue) of `clang::getCursorKindForDecl` reporting linkage specifications such as `extern "C"` as CXCursor_UnexposedDecl, rather than CXCursor_LinkageSpec.
This was recently fixed in Clang 18, which breaks bindgen by making all `extern "C"` decls invisible to bindgen. Bindgen just generates nothing.
This PR makes bindgen compatible with Clang 18 by treating CXCursor_LinkageSpec the same as the old CXCursor_UnexposedDecl.
=> Handle CXCursor_LinkageSpec in Clang 18+

bindgen/ir/function.rs
"vectorcall" and "aarch64 vectorcall" are the same calling conventions only for different architectures, is it right?
closes #2693
=> prevent panic when compiling aarch64 vectorcall functions

bindgen-tests/tests/expectations/tests/bitfield-32bit-overflow.rs, bindgen-tests/tests/expectations/tests/bitfield-method-same-name.rs, bindgen-tests/tests/expectations/tests/bitfield_align.rs, bindgen-tests/tests/expectations/tests/bitfield_align_2.rs, bindgen-tests/tests/expectations/tests/bitfield_method_mangling.rs, bindgen-tests/tests/expectations/tests/bitfield_pragma_packed.rs, bindgen-tests/tests/expectations/tests/default_visibility_crate.rs, bindgen-tests/tests/expectations/tests/default_visibility_private.rs, bindgen-tests/tests/expectations/tests/default_visibility_private_respects_cxx_access_spec.rs, bindgen-tests/tests/expectations/tests/issue-1034.rs, bindgen-tests/tests/expectations/tests/issue-1076-unnamed-bitfield-alignment.rs, bindgen-tests/tests/expectations/tests/issue-1947.rs, bindgen-tests/tests/expectations/tests/issue-739-pointer-wide-bitfield.rs, bindgen-tests/tests/expectations/tests/jsval_layout_opaque.rs, bindgen-tests/tests/expectations/tests/jsval_layout_opaque_1_0.rs, bindgen-tests/tests/expectations/tests/only_bitfields.rs, bindgen-tests/tests/expectations/tests/union_bitfield.rs, bindgen-tests/tests/expectations/tests/union_with_anon_struct_bitfield.rs, bindgen-tests/tests/expectations/tests/union_with_anon_struct_bitfield_1_0.rs, bindgen-tests/tests/headers/bitfield_pragma_packed.h, bindgen/codegen/struct_layout.rs
Partial fix to https://lore.kernel.org/rust-for-linux/Y8Ax%2FI5qOcVDZljG@zn.tnic/ (not a full fix, because if `short` below is replaced with a `int` then the code still fails to compile)
Currently binding for code like this wouldn't compile:
```c
struct outer {
struct {
short a: 16;
short b: 16;
};
} __attribute__((packed));
```
because bindgen sticks an extra `#[repr(align(2))]` on the inner struct.
This extra alignment is not necessary and can be removed. The removed NB line in this PR is no longer relevant because of the addition _bitfield_align field generated starting in #1950.
Reopen of #2388
=> Consider alignment contribution from bitfields

bindgen-tests/tests/expectations/tests/float16.rs, bindgen-tests/tests/headers/float16.h, bindgen/codegen/helpers.rs, bindgen/codegen/mod.rs, bindgen/codegen/serialize.rs, bindgen/ir/context.rs, bindgen/ir/ty.rs
This is done by defining `pub struct __BindgenFloat16(pub u16);`. Clang has half (`__fp16`; storage type, casted to float for calculations) and float16 (`__Float16`) types, both have same binary representations, and this PR handles both as same.
More about half types here: https://clang.llvm.org/docs/LanguageExtensions.html#half-precision-floating-point.
When rust implements `f16` we could use those if appropriate target rust is used.
Rust `f16` RFC: https://github.com/rust-lang/rfcs/blob/master/text/3453-f16-and-f128.md#f16-type (contains some clang details)
Fixes #2500.
=> Support float16

bindgen-tests/tests/expectations/tests/win32-dtors.rs, bindgen-tests/tests/headers/win32-dtors.hpp, bindgen/clang.rs, bindgen/ir/context.rs, bindgen/ir/function.rs
Tries to solve #1725 and #2092.
I found that clang can only generate one entry when calling `clang_Cursor_getCXXManglings` with the Microsoft ABI. Also the conditions for "group 1" destructors don't apply at all on the MS ABI, having a completely different mangling format.
Also, it seems like the entry from `clang_Cursor_getCXXManglings` will always be the regular "base" destructor that is most interesting usually, while the entry from `clang_Cursor_getMangling` will always be the "vbase destructor" that's supposed to be able to destroy anything. However, only the base destructor is always available, the other ones being generated on the fly when the code actually needs it.
So far, the code always chose the vbase dtor that happened to never exist, and this is why the code always failed …
=> Better working destructors on windows

bindgen/Cargo.toml
rust-lang/rust-bindgen#1643 disabled many deafault features of the `regex` crate but left the `unicode` meta feature enabled. With the `unicode` feature enabled and `bindgen` as a build dependency, `regex-syntax` (a direct dependency of the `regex` crate) takes 7 seconds to compile as a build dependency in my application.
The `unicode` feature includes support for many Unicode character class lookups which I find unlikely that bindgen uses. Even without the `unicode` feature enabled, the `regex` crate supports Unicode. The various `unicode-*` features only remove compiled in data tables that support various types of character classes.
From https://docs.rs/regex/latest/regex/#unicode-features:
> - **unicode-age** - Provide the data for the Unicode Age property. This makes it possible to …
=> Deactivate many `regex` Unicode crate features

bindgen/Cargo.toml
When building a crate that depends on `bindgen` with `-Zminimal-features`, `cargo` ends up selecting `regex 1.5.0` which fails to compile when its `perf-literal` feature isn't enabled. This was aptly fixed in `1.5.1`, albeit without yanking the `1.5.0` release.
https://github.com/rust-lang/regex/issues/931
=> Use at least `regex 1.5.1` to avoid build build failures without `perf-literal` feature

bindgen-tests/tests/expectations/tests/noreturn.rs, bindgen-tests/tests/headers/noreturn.hpp, bindgen/ir/function.rs
Fixes #2715.
I have not been able to find a way to get at this information directly through the C API of libclang 9, so instead this patch just checks how deeply nested in parentheses the `__attribute__((noreturn))` qualifier is.
=> Correctly handle  __attribute__((noreturn)) in function arguments

bindgen-tests/tests/expectations/tests/issue-2695.rs, bindgen-tests/tests/headers/issue-2695.h, bindgen/codegen/struct_layout.rs
=> Use field align if it's smaller than pack align

bindgen-tests/tests/expectations/tests/win32-thiscall_1_73.rs, bindgen-tests/tests/headers/win32-thiscall_1_73.hpp, bindgen/features.rs
1.73 Changelog:
- https://github.com/rust-lang/rust/releases/tag/1.73.0
Stabilization issue:
- https://github.com/rust-lang/rust/pull/114562/
----
Maybe there are some tests to be fixed. I'm not quite sure how to review those.
=> Add thiscall_abi to stable version Rust 1.73.

triagebot.toml
This allows non-maintainers to set labels with `@rustbot`.
This won't work until https://github.com/rust-lang/team/pull/1200 merges.
=> Add a triagebot.toml file

Cargo.lock
Hello !
Here's a little PR updating `shlex` regarding the [RUSTSEC-2024-0006](https://rustsec.org/advisories/RUSTSEC-2024-0006).
The changelog of `shlex` which was in `1.1.0` to `1.3.0` is visible [here](https://github.com/comex/rust-shlex/blob/master/CHANGELOG.md).
Feel free to tell me if this PR isn't suitable, I read the contribution file but see nothing about dependency update for vulnerability issues.
Thanks !
=> chore: updating shlex regarding RUSTSEC-2024-0006

CONTRIBUTING.md
The contribution guide seems to be pointing at a dead link. This
commit updates the link to a working version.
I was not sure if this is the link we were looking for. An alternative is:
https://foundation.rust-lang.org/policies/code-of-conduct/
=> Update Rust Code of Conduct link in Contribution guide

book/src/tutorial-3.md
#2740 A simple little update to the tutorial book.
=> Use `CargoCallbacks::new()` instead of `bindgen::CargoCallbacks`

bindgen/lib.rs, book/src/non-system-libraries.md, book/src/tutorial-3.md
Use `CargoCallbacks::new()` to fix:
```
warning: use of deprecated constant `bindgen::CargoCallbacks`: Use `CargoCallbacks::new()` instead. Please, check the documentation for further information.
--> build.rs:11:44
|
11 |         .parse_callbacks(Box::new(bindgen::CargoCallbacks))
```
=> Use CargoCallbacks::new() in documentation

bindgen-tests/tests/expectations/tests/redundant-packed-and-align.rs, bindgen-tests/tests/headers/redundant-packed-and-align.h, bindgen/codegen/mod.rs, bindgen/codegen/struct_layout.rs, bindgen/ir/comp.rs
This is for https://github.com/rust-lang/rust-bindgen/issues/2725
This patch handles the "type has both packed and align attrs" case, but it doesn't do anything for the "packed type transitively contains aligned type" case.
The test header intentionally generates types that won't compile. If this is a problem, and the test output rust source needs to compile, let me know and I'll remove those types...
I'm still pretty new to Rust, so a thorough review would be much appreciated! 
-------
Currently rustc forbids compound types from having both a `packed` and `align` attribute.
When a source type has both attributes, this may mean it cannot be represented with the current rustc. Often, though, one or both of these attributes is redundant and can be safely removed from the generated Rust …
=> try to avoid `#[repr(packed)]` when `align` is needed

bindgen-tests/tests/tests.rs
Before the test was too broad and just tested for existence of the variable. With this test we can ensure that quoting was indeed managed.
Context: I don't know if it's mandatory to check this kind of shell quoting detail, but wandering the code due to the [shlex advisory](https://rustsec.org/advisories/RUSTSEC-2024-0006.html) I found this case not covered so I submit a patch!
It's used here:
```
rg -C 5 shlex
[...[
bindgen/lib.rs
308-        Some(s) => s,
309-    };
310-
311-    // Try to parse it with shell quoting. If we fail, make it one single big argument.
312:    if let Some(strings) = shlex::split(&extra_clang_args) {
313-        return strings;
314-    }
315-    vec![extra_clang_args]
316-}
```
Edited: has some not commited stuff in the rg cmd
=> Add test for quoted Env variables passed with BINDGEN_EXTRA_CLANG_ARGS.

bindgen-cli/options.rs, bindgen-tests/tests/expectations/tests/blocklist-var.rs, bindgen-tests/tests/headers/blocklist-var.hpp, bindgen/ir/item.rs, bindgen/lib.rs, bindgen/options/mod.rs, book/src/blocklisting.md
Implements #2730.
Note: This is my first contribution to the project. Let me know if I missed anything.
=> feat: add blocklist_var

CHANGELOG.md, Cargo.lock, bindgen/Cargo.toml
This can help avoid duplicate dependencies when using bindgen as a library.
=> Update itertools and allow itertools 0.10 too.

bindgen-tests/tests/tests.rs, bindgen/options/mod.rs
Problem: It's cumbersome to define multiple input headers using the existing `header` API. It's difficult for the user to configure the `Builder` with a list of input headers.
Solution: Add `headers` method that permits adding multiple headers via an iterable of Strings.
Testing: Added `test_headers_call_in_builder`. Ran `cargo test` in `bindgen-tests/tests/expectations`.
Issue: https://github.com/rust-lang/rust-bindgen/issues/2738
=> feat: add `headers` option

CHANGELOG.md, bindgen/lib.rs
Similar change to #2551. Just filling in more mappings.
`riscv64imac` and `riscv32imafc` both appear in built-in targets (`riscv64imac-unknown-none-elf` and `riscv32imafc-unknown-none-elf`, respectively).
=> Add target mappings for `riscv64imac` and `riscv32imafc`

bindgen-integration/build.rs, bindgen/clang.rs, bindgen/codegen/serialize.rs, bindgen/ir/annotations.rs, bindgen/ir/comp.rs, bindgen/ir/context.rs, bindgen/ir/item_kind.rs, bindgen/ir/objc.rs, bindgen/ir/ty.rs, bindgen/lib.rs, bindgen/options/mod.rs, book/src/cpp.md, book/src/non-system-libraries.md, book/src/objc.md
Hi there. I noticed a typo when reviewing options. Fixed that one plus a few others I searched for.
=> Fix several typos

bindgen/Cargo.toml
This is reopened PR of https://github.com/rust-lang/rust-bindgen/pull/2717 because I don't have the permission to reopen it.
Even with regex 1.5.1, bindgen fails to build with `-Z minimal-versions`.
```
$ cd path/to/rust-bindgen
$ cargo +nightly update -Z minimal-versions
$ cargo build
Compiling regex-syntax v0.6.24
error[E0433]: failed to resolve: use of undeclared crate or module `unicode_tables`
--> /home/kawasin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/regex-syntax-0.6.24/src/unicode.rs:351:13
|
351 |         use unicode_tables::perl_space::WHITE_SPACE;
|             ^^^^^^^^^^^^^^ use of undeclared crate or module `unicode_tables`
error[E0433]: failed to resolve: use of undeclared crate or module `unicode_tables`
--> …
```
=> Update minimum regex version to fix compile error

bindgen-tests/tests/tests.rs, bindgen/ir/item.rs
Fix warnings, one of which causes CI to fail currently.
=> Fix warnings.

bindgen-tests/tests/expectations/tests/const_array_typedef.rs, bindgen-tests/tests/headers/const_array_typedef.h, bindgen/codegen/mod.rs
Fix #2683. Fairly hacky fix right now, but it doesn't seem to break any tests.
=> Fix const array issue

bindgen-integration/build.rs, bindgen-integration/cpp/Test.h, bindgen-integration/src/lib.rs, bindgen/codegen/mod.rs
This allows custom derives on new-type aliases which brings them in line with other structs and enums regarding derive callbacks.
The implementation was mostly copied from https://github.com/rust-lang/rust-bindgen/pull/2117.
=> Allow custom derives on new-type alias

bindgen/options/mod.rs
`rerun-if-changed` for only needed files is great and useful for almost all projects, but somewhat difficult to find. Add a bit about it in the `Builder` docs.
=> Make `CargoCallbacks` more discoverable

CHANGELOG.md, bindgen-cli/Cargo.toml
The bindgen documentation explictly mentions being able to use `--formatter=prettyplease`, but currently the prettyplease feature has no way to be enabled.
Enable it by default, since the documentation also doesn't mention needing to cargo install with a feature.
Documentation: https://rust-lang.github.io/rust-bindgen/code-formatting.html
=> Add prettyplease feature to bindgen-cli

bindgen-tests/tests/expectations/tests/dynamic_loading_variable_required.rs, bindgen-tests/tests/expectations/tests/dynamic_loading_variable_simple.rs, bindgen-tests/tests/expectations/tests/dynamic_loading_variable_with_allowlist.rs, bindgen-tests/tests/headers/dynamic_loading_variable_required.h, bindgen-tests/tests/headers/dynamic_loading_variable_simple.h, bindgen-tests/tests/headers/dynamic_loading_variable_with_allowlist.hpp, bindgen/codegen/dyngen.rs, bindgen/codegen/mod.rs
It's just a rebase of #2114 , since the original pull requests are closed, I thought might just rebase and create a new one for reviewing, @emilio.
Supporting for dynamic loading can be a useful feature when one need to found library in a dynamic way(i.e. choose between libraries with compatible ABI), and supporting loading static variable is a important feature in this feature.
=> feat: add dynamic loading of variable

Cargo.lock, bindgen-cli/Cargo.toml, bindgen-tests/Cargo.toml, bindgen/Cargo.toml, bindgen/lib.rs
The which dependency was introduced alongside the ability for bindgen to call rustfmt: https://github.com/rust-lang/rust-bindgen/pull/905
Theres been some dancing around the need for this dependency, with a feature added to disable it back in 2019 https://github.com/rust-lang/rust-bindgen/pull/1615
But I dont believe its actually required at all and in this PR I propose that we can just remove it entirely.
My understanding is that `which` will check the PATH for any binaries matching the passed name.
However if we were to just attempt to execute that name directly the OS would perform the exact same operation, checking the PATH for any binaries matching the name.
So we should just directly execute `rustfmt`, unless its overridden by the `RUSTFMT` env var.
If my understanding is incorrect, …
=> Remove which dependency

bindgen/lib.rs
This change simplifies/generalizes the rust to clang target conversion and allows more targets to work. (e.g. `riscv32i-unknown-none-elf`)
Let me know if I'm missing something!
=> Simplify Rust to Clang target conversion

.github/workflows/bindgen.yml
Now seems to run on arm64 out of the blue...
=> ci: Try to fix macOS runner

.github/workflows/bindgen.yml, Cargo.lock, README.md, bindgen-cli/Cargo.toml, bindgen-tests/tests/quickchecking/Cargo.toml, bindgen-tests/tests/quickchecking/src/lib.rs, bindgen/Cargo.toml, bindgen/callbacks.rs, bindgen/clang.rs, bindgen/codegen/mod.rs, bindgen/ir/analysis/has_vtable.rs, bindgen/ir/analysis/mod.rs, bindgen/ir/analysis/sizedness.rs, bindgen/ir/annotations.rs, bindgen/ir/derive.rs, bindgen/ir/item.rs, bindgen/ir/var.rs, bindgen/lib.rs
They couldn't be merged without a rebase because of a CI issue (fixed by #2819).
Closes #2818
Closes #2817
=> Rebase of #2818 and #2817

bindgen/clang.rs
Both had the same behavior... until https://github.com/llvm/llvm-project/commit/2e770edd8ce13f48402f1d93e5fb982d8a2ebe64 which fixed getSpellingLocation, but bindgen looks like it actually expects the getFileLocation result.
=> Use clang_getFileLocation instead of clang_getSpellingLocation

bindgen-tests/tests/expectations/tests/libclang-9/macro_fallback_non_system_dir.rs, bindgen-tests/tests/expectations/tests/test_macro_fallback_non_system_dir.rs, bindgen-tests/tests/headers/issue-753.h, bindgen-tests/tests/macro_fallback_test_headers/another_header.h, bindgen-tests/tests/macro_fallback_test_headers/one_header.h, bindgen-tests/tests/tests.rs, bindgen/clang.rs, bindgen/ir/context.rs
Fix for issue reported [here](https://github.com/rust-lang/rust-bindgen/pull/2779#issuecomment-2081376090).
@SeleDreams Could you also confirm that this resolves your problem?
=> Switch to single precompiled header in macro fallback

Cargo.lock, bindgen/Cargo.toml
In the vein of https://github.com/rust-lang/rust-bindgen/pull/2745, just in the other direction.
Changes: https://github.com/rust-itertools/itertools/blob/master/CHANGELOG.md#0130
=> Allow itertools 0.13, bump Cargo.lock to it

bindgen-tests/tests/expectations/tests/anon_enum_blocklist.rs, bindgen-tests/tests/expectations/tests/blocklist_bitfield_unit.rs, bindgen-tests/tests/headers/anon_enum_blocklist.h, bindgen-tests/tests/headers/blocklist_bitfield_unit.h, bindgen/codegen/helpers.rs, bindgen/codegen/mod.rs, book/src/using-bitfields.md
Closes #2835
Simply skip emitting it if the list of blocklisted types/items matches its name.
Also add a test that verifies blocklisting anonymous types by `_bindgen_ty_*` works as expected – which could be used to prevent similar conflicts between generated type names for anonymous types.
=> Support blocklisting `__BindgenBitfieldUnit`

bindgen-cli/main.rs
This prevents them of sneaking into output files instead of being displayed when manually generating bindings by redirecting stdout.
Similar to #1031, the CLI should print to stderr too.
=> Print CLI errors to stderr instead of stdout

CHANGELOG.md, bindgen-cli/options.rs, bindgen/lib.rs
Currently the CLI allows for all other enum builder options except for non-exhaustive rustified enums. This PR fixes the omission.
Solves #2846
=> Added non-exhaustive enums to the CLI

CHANGELOG.md, bindgen-tests/tests/expectations/tests/infinite-macro.rs, bindgen/codegen/helpers.rs, bindgen/codegen/mod.rs, bindgen/features.rs
https://github.com/rust-lang/rust-bindgen/issues/2853
=> Fix generated constants: f64::INFINITY & f64::NEG_ INFINITY

.github/workflows/bindgen.yml
The `actions-rs` actions are not maintained (and haven't been for a long time). Some tests used `dtolnay/rust-toolchain`, so use it consistently.
=> ci: Use `dtolnay/rust-toolchain`, not `actions-rs`

bindgen/features.rs
The `"vectorcall"` ABI now has a tracking issue at rust-lang/rust#124485.
=> Add tracking issue number for `"vectorcall"` ABI feature

bindgen-tests/tests/expectations/tests/flexarray.rs, bindgen/codegen/mod.rs
The signature of `core::ptr::from_raw_parts` is different between Rust 1.79 and Rust 1.80, causing an ambiguity in the code previously produced by bindgen.
- https://doc.rust-lang.org/1.79.0/core/ptr/fn.from_raw_parts.html
- https://doc.rust-lang.org/1.80.0/core/ptr/fn.from_raw_parts.html
```diff
- pub fn from_raw_parts<T: ?Sized>(
+ pub const fn from_raw_parts<T: ?Sized>(
-     data_pointer: *const (),
+     data_pointer: *const impl Thin,
metadata: <T as Pointee>::Metadata,
) -> *const T
```
```console
error[E0283]: type annotations needed
--> lib.rs:317:62
|
317 |             let p: *const Self = ::core::ptr::from_raw_parts(::core::ptr::null(), len);
|                                  --------------------------- ^^^^^^^^^^^^^^^^^ cannot infer type of the type parameter `T` declared on …
```
=> Update flex-array implementation to work with Rust 1.80

.github/workflows/publish.yml
This workflow has been running several times after a release has already happened.
I'm putting it on manual mode until we figure out how to fix the release process.
=> Only trigger the publish workflow manually

CONTRIBUTING.md
The link to their INSTALL.MD is on a different branch.
--rustc-grep expects a regex, so the example doesn't work
=> Fix creduce instructions

bindgen-tests/tests/expectations/tests/atomic-constant.rs, bindgen-tests/tests/expectations/tests/libclang-9/atomic-constant.rs, bindgen-tests/tests/headers/atomic-constant.h, bindgen/Cargo.toml, bindgen/clang.rs, bindgen/ir/ty.rs, bindgen/ir/var.rs
=> ir: Dig into atomic types.

CHANGELOG.md, Cargo.lock, bindgen-cli/Cargo.toml, bindgen-cli/options.rs, bindgen-integration/build.rs, bindgen-integration/src/lib.rs, bindgen-tests/Cargo.toml, bindgen-tests/tests/expectations/tests/attribute-custom-cli.rs, bindgen-tests/tests/expectations/tests/attribute-custom.rs, bindgen-tests/tests/headers/attribute-custom-cli.h, bindgen-tests/tests/headers/attribute-custom.h, bindgen/callbacks.rs, bindgen/codegen/mod.rs, bindgen/ir/annotations.rs
This adds support for custom attributes:
- `ParseCallbacks::add_attributes(&self, info: &AttributeInfo<'_>) -> Vec<TokenStream>`
- `--with-attribute-custom <CUSTOM>`
- `--with-attribute-custom-struct <CUSTOM>`
- `--with-attribute-custom-enum <CUSTOM>`
- `--with-attribute-custom-union <CUSTOM>`
The implementation is very similar to the custom derives functionality. One thing I am not sure about is returning `Vec<TokenStream>` instead of `Vec<String>`, but that seemed natural to me.
Fixes https://github.com/rust-lang/rust-bindgen/issues/2520
=> Add support for custom attributes

CHANGELOG.md, bindgen-cli/options.rs, bindgen-tests/tests/headers/wrap-static-fns.h, bindgen/options/mod.rs
Fixes https://github.com/rust-lang/rust-bindgen/issues/2900
=> Stabilize `--wrap-static-fns`

.github/workflows/bindgen.yml, ci/test.sh
Rust for Linux, so far, has pinned the Rust compiler and `bindgen` versions. The kernel is looking into expanding that support to several versions, i.e. establishing a minimum supported version, so that the kernel can start to be more easily built. In particular, it should be possible to build the kernel using the tools provided directly by Linux distributions. In order to help achieve that goal, the Rust project has added the kernel to its Rust pre-merge CI.
This commit does the same for `bindgen`. In particular, it adds a quick, build-only test of the Rust code in the kernel as an extra step in the `test` workflow.
This is intended to be an end-to-end test that runs what kernel developers/users would do. In particular, it is useful to catch certain issues that go beyond the C header …
=> ci: Add Rust for Linux

bindgen/lib.rs, book/src/requirements.md
Adds a check for the loaded libclang version and returns an error if the version is unsupported.
=> Require libclang 9.0 or newer

book/src/requirements.md
Bindgen doesn't need the llvm package at all and only needs the clang package for one function. I've tested this by running the bindgen tests on a fresh Debian installation.
I removed the line about Ubuntu because it is not relevant anymore.
closes #2934
=> Update documentation of Debian dependencies

book/src/tutorial-3.md
This is an example code that does not work based on the current version (bindgen = "0.65.1").
=> Docs: Fix example code error

ci/test.sh
The CI is hitting errors and warnings now [1], due to Rust 1.82.0 being used to build an older Linux kernel:
warning: the feature `new_uninit` has been stable since 1.82.0 and no longer requires an attribute to enable
--> rust/kernel/lib.rs:17:12
|
17 | #![feature(new_uninit)]
|            ^^^^^^^^^^
|
= note: `#[warn(stable_features)]` on by default
error[E0658]: use of unstable library feature 'box_uninit_write'
--> rust/kernel/alloc/box_ext.rs:25:12
|
25 |         Ok(Box::write(b, x))
|            ^^^^^^^^^^
|
= note: see issue #129397 <https://github.com/rust-lang/rust/issues/129397> for more information
= help: add `#![feature(box_uninit_write)]` to the crate attributes to enable
= note: this compiler was built on 2024-10-15; consider upgrading it if it is out of date
Which is due to …
=> ci: Move forward Rust for Linux version

bindgen/codegen/mod.rs
Does it make sense that "traits" is the correct word?... :-)
=> fix very small typo

bindgen-tests/tests/expectations/tests/wrap_unsafe_ops_dynamic_loading_simple.rs, bindgen-tests/tests/headers/wrap_unsafe_ops_dynamic_loading_simple.h, bindgen/codegen/dyngen.rs, bindgen/codegen/mod.rs
Closes https://github.com/rust-lang/rust-bindgen/issues/2957
=> Fix unsafe_op_in_unsafe_fn when using dynamic librarys and wrap_unsafe_ops

bindgen-tests/tests/expectations/tests/issue-2966.rs, bindgen-tests/tests/headers/issue-2966.h, bindgen-tests/tests/parse_callbacks/mod.rs, bindgen/codegen/mod.rs
The `field_visibility` callback is now called in case of alias new-type and new-type-deref with the type name and field_name set to `"0"`
This PR allows generation of different accessibility:
```c
typedef const char *  pub_var1;
typedef const char *  pubcrate_var2;
typedef const char *  private_var3;
```
```rust
pub struct pub_var1(pub *const ::std::os::raw::c_char);
pub struct pubcrate_var2(pub(crate) *const ::std::os::raw::c_char);
pub struct private_var3(*const ::std::os::raw::c_char);
```
Fixes #2966
=> Fix `field_visibility` not called for new-type aliases

.github/workflows/release.yml
The release workflow should not run on pull requests.
See e.g. https://github.com/rust-lang/rust-bindgen/actions/runs/11816897132 which was triggered by another pull request opened by me.
=> Restrict release workflow to pushes

CHANGELOG.md
This option was added after the 0.70.1 release and is not available yet.
=> Changelog: Move --with-attribute-custom to unreleased

Cargo.toml, bindgen-cli/Cargo.toml, bindgen-integration/Cargo.toml, bindgen-tests/Cargo.toml, bindgen/Cargo.toml
This introduces workspace dependencies to avoid unintentional mismatches of dependencies between crates and sets the edition for the `bindgen-integration` crate so we stop getting a warning about it
=> Some updates to the cargo manifests

Cargo.lock, Cargo.toml, bindgen-cli/Cargo.toml, bindgen-cli/main.rs, bindgen-tests/Cargo.toml, bindgen-tests/tests/tests.rs, bindgen/Cargo.toml, bindgen/lib.rs, bindgen/options/as_args.rs, bindgen/options/cli.rs, bindgen/options/mod.rs, bindgen/regex_set.rs
This is done in an effort to allow `bindgen` (the library) parse arguments from a configuration file just like #2917 does for `bindgen-cli`.
=> Move CLI options to `bindgen`

CONTRIBUTING.md
While reading `CONTRIBUTING.md`, I noticed a few things that I could fix:
- Passes `markdownlint` (mostly)
- Removed `$` from shell instructions, as to be more copy/paste friendly
- Annotated code-like things with backticks.
- Annotated all shell blocks with `sh` to format nicely on GitHub.com.
I intend to attempt at making a real PR/MR for `rust-bindgen`, therefore I noticed these things because I was trying to get an overview of what is required to pass review..
=> Formatted `CONTRIBUTING.md`

bindgen/options/cli.rs
These changes abstract away the most commonly used patterns to apply CLI args to the `Builder`:
```rust
if bool_cli_arg {
builder = builder.method(bool_cli_arg);
}
```
```rust
if let Some(value) = option_cli_arg {
builder = builder.method(value);
}
```
```rust
for value in vec_cli_arg {
builder = builder.method(value);
}
```
=> Refactor how CLI args are applied to `Builder`

bindgen-tests/tests/expectations/tests/derive-bitfield-method-same-name.rs, bindgen-tests/tests/expectations/tests/derive-debug-bitfield-1-51.rs, bindgen-tests/tests/expectations/tests/derive-debug-bitfield-core.rs, bindgen-tests/tests/expectations/tests/derive-partialeq-bitfield.rs, bindgen-tests/tests/expectations/tests/jsval_layout_opaque_1_0.rs, bindgen-tests/tests/expectations/tests/layout_eth_conf.rs, bindgen-tests/tests/expectations/tests/layout_eth_conf_1_0.rs, bindgen-tests/tests/expectations/tests/layout_mbuf_1_0.rs, bindgen-tests/tests/expectations/tests/union_bitfield_1_0.rs, bindgen-tests/tests/expectations/tests/union_with_anon_struct_bitfield_1_0.rs, bindgen-tests/tests/headers/derive-debug-bitfield-1-51.hpp, bindgen/codegen/bitfield_unit_raw_ref_macros.rs, bindgen/codegen/mod.rs, bindgen/features.rs
This feature was stabilized in rust 1.51 and adds the `addr_of` and `addr_of_mut` macros.
Without these changes, `bindgen` cannot generate code that's valid for Rust versions lower than 1.51 in certain contexts.
=> Add `raw_ref_macros` feature

.github/workflows/bindgen.yml
I noticed CI failures in #2951 because libtinfo5 is no longer available in ubuntu-latest since https://github.com/actions/runner-images/issues/10636.
```console
Run sudo apt-get update
sudo apt-get update
sudo apt-get install libtinfo5
shell: /usr/bin/bash -e {0}
env:
CARGO_HOME: /home/runner/.cargo
CARGO_INCREMENTAL: 0
CARGO_TERM_COLOR: always
Hit:1 http://azure.archive.ubuntu.com/ubuntu noble InRelease
Get:2 http://azure.archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu noble-backports InRelease [126 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu noble-security InRelease [126 kB]
Hit:5 https://packages.microsoft.com/repos/azure-cli noble InRelease
Get:6 https://packages.microsoft.com/ubuntu/24.04/prod noble InRelease [3600 B]
Get:7 …
```
=> Fix libtinfo dependency in CI

bindgen-tests/tests/expectations/tests/inline_namespace_macro.rs, bindgen-tests/tests/headers/inline_namespace_macro.hpp, bindgen-tests/tests/headers/namespace/nsdefine.h, bindgen/clang.rs, bindgen/ir/context.rs
=> Recognize inline namespaces using clang's dedicated API for that

bindgen-cli/Cargo.toml, bindgen-integration/Cargo.toml, bindgen-integration/src/lib.rs, bindgen-tests/Cargo.toml, bindgen-tests/tests/expectations/Cargo.toml, bindgen-tests/tests/quickchecking/Cargo.toml, bindgen/Cargo.toml
This will make it possible to introduce C-string literals and possibly other language features in separate PRs.
This PR blocks #2996
=> Bump to 2021 edition

Cargo.lock, bindgen-tests/tests/expectations/tests/strings_cstr2.rs, bindgen-tests/tests/headers/strings_cstr2.h, bindgen/codegen/mod.rs, bindgen/features.rs
When `generate_cstr` is enabled, and the target rust version is >= 1.77, generate `c"..."` literals instead of the unsafe `from_bytes_with_nul_unchecked` calls.  Note that this requires 2021 edition, but since this is not on by default, and CStr support is relatively recent, i think it is ok to tie them together
Note that this also resolves the Clippy 1.83's [manual_c_str_literals](https://rust-lang.github.io/rust-clippy/master/index.html#/manual_c_str_literals) issue
Fixes #2994
=> Generate C-String literals `c"example"` instead of unsafe code

Cargo.toml, bindgen/lib.rs
The 2021 usually implies resolver v2, and warns otherwise.
=> Use v2 cargo resolver

bindgen-tests/tests/expectations/Cargo.toml, bindgen/clang.rs, bindgen/ir/analysis/derive.rs, bindgen/ir/annotations.rs, bindgen/ir/comment.rs, bindgen/ir/comp.rs, bindgen/ir/context.rs, bindgen/ir/enum_ty.rs, bindgen/ir/function.rs, bindgen/ir/item.rs, bindgen/ir/layout.rs, bindgen/ir/ty.rs, bindgen/ir/var.rs, bindgen/lib.rs
Happy clippy = happy developers
The test expectations generate a bunch of lints that are mostly irrelevant, at least at the moment, so might as well record them to avoid `cargo clippy` from reporting them.
=> Clippify, and hide some lints in test output

bindgen-tests/tests/expectations/tests/strings_cstr2_2018.rs, bindgen-tests/tests/headers/strings_cstr2_2018.h, bindgen/features.rs, bindgen/lib.rs, bindgen/options/cli.rs, bindgen/options/mod.rs
This PR introduces the concept of Rust editions to bindgen so it can generate appropriate code based on the desired edition.
The motivation behind this PR comes from #2996 which allows bindgen to generate code with C-String literals, a feature that has been available since rust 1.77 but are gated behind the 2021 edition.
The changes in this PR are:
- Introduce the `--rust-edition` CLI argument and `Builder::rust_edition` method.
- Update bindgen internals to filter features based on the set edition. 
- Gate the `literal_cstr` feature behind the 2021 edition.
cc @nyurik @emilio
=> Introduce `--rust-edition`

bindgen/features.rs, bindgen/lib.rs
Making RustEdition public allows calling Builder::rust_edition() from the build.rs scripts.
+ Adding documentation to the RustEdition enum to not break linter rules.
Fixes #3012
=> Make RustEdition public

bindgen/codegen/helpers.rs, bindgen/ir/analysis/derive.rs, bindgen/ir/analysis/has_destructor.rs, bindgen/ir/analysis/has_float.rs, bindgen/ir/analysis/has_type_param_in_array.rs, bindgen/ir/analysis/has_vtable.rs, bindgen/ir/analysis/mod.rs, bindgen/ir/analysis/sizedness.rs, bindgen/ir/analysis/template_params.rs, bindgen/ir/context.rs
Removed a few unneeded cloning
=> Applied clippy cloned->copied, and cleanup

.github/workflows/bindgen.yml, Cargo.toml, bindgen-cli/Cargo.toml, bindgen-integration/Cargo.toml, bindgen-tests/Cargo.toml, bindgen-tests/tests/expectations/Cargo.toml, bindgen-tests/tests/quickchecking/Cargo.toml, bindgen/Cargo.toml
* Consolidate MSRV management, and automate CI to pick it from the `Cargo.toml` instead of hardcoding
* Consolidate Rust language edition management
* Consolidate dependency management
With workspaces we can consolidate all dependency management in one location.  Even if dependency is used only once, we do not need to track if it is being used only once, plus we don't need to move things to a central places when more than one place uses it.  This keeps things much simpler, and ensures that every single dependency is listed in one location.
=> Consolidate dependency version management

Cargo.toml, bindgen-cli/Cargo.toml, bindgen-integration/Cargo.toml, bindgen-tests/Cargo.toml, bindgen-tests/tests/expectations/Cargo.toml, bindgen-tests/tests/quickchecking/Cargo.toml, bindgen/Cargo.toml
Move all clippy configurations to one central place, except for the expected tests - they seem to require their own handling for now due to a Cargo limitation.
=> Consolidate clippy configuration

bindgen-integration/build.rs, bindgen-tests/tests/tests.rs, bindgen/build.rs, bindgen/clang.rs, bindgen/codegen/dyngen.rs, bindgen/codegen/mod.rs, bindgen/ir/comment.rs, bindgen/ir/comp.rs, bindgen/ir/context.rs, bindgen/ir/dot.rs, bindgen/ir/item.rs, bindgen/ir/layout.rs, bindgen/ir/ty.rs, bindgen/ir/var.rs, bindgen/lib.rs, bindgen/options/cli.rs
Moved from #3016 per @pvdrz request
=> Fix a lot of `unused_qualifications` lints

bindgen/clang.rs, bindgen/codegen/mod.rs, bindgen/codegen/serialize.rs, bindgen/ir/item.rs, bindgen/options/cli.rs
```
cargo clippy --workspace --exclude bindgen-integration --exclude tests_expectations -- -W clippy::map_unwrap_or
```
=> Fix `map_unwrap_or` lint

bindgen/clang.rs, bindgen/codegen/mod.rs, bindgen/ir/analysis/derive.rs, bindgen/ir/analysis/mod.rs, bindgen/ir/analysis/template_params.rs, bindgen/ir/annotations.rs, bindgen/lib.rs
Using negations in the `if` makes them a bit harder to read... and there is a lint for that :)
```
cargo clippy --workspace --exclude bindgen-integration --exclude tests_expectations -- -W clippy::if_not_else
```
=> Fix `if_not_else` lint

bindgen/codegen/impl_partialeq.rs, bindgen/codegen/mod.rs, bindgen/ir/analysis/mod.rs, bindgen/ir/analysis/template_params.rs, bindgen/ir/comp.rs, bindgen/ir/context.rs, bindgen/ir/objc.rs, bindgen/lib.rs, bindgen/options/mod.rs, bindgen/regex_set.rs
```
cargo clippy --fix --workspace --exclude bindgen-integration --exclude tests_expectations -- -W clippy::explicit_iter_loop
```
=> Fix `explicit_iter_loop` lint

bindgen-tests/build.rs, bindgen-tests/tests/tests.rs, bindgen/clang.rs, bindgen/codegen/helpers.rs, bindgen/codegen/impl_debug.rs, bindgen/codegen/mod.rs, bindgen/codegen/serialize.rs, bindgen/codegen/struct_layout.rs, bindgen/features.rs, bindgen/ir/analysis/derive.rs, bindgen/ir/analysis/has_float.rs, bindgen/ir/analysis/has_type_param_in_array.rs, bindgen/ir/context.rs, bindgen/ir/item.rs, bindgen/ir/template.rs, bindgen/ir/ty.rs, bindgen/ir/var.rs, bindgen/regex_set.rs
Used this to find issues, apply suggestions, and manually fixed a [clippy bug](https://github.com/rust-lang/rust-clippy/issues/13768)
```bash
cargo clippy --all-targets --workspace --exclude bindgen-integration --exclude tests_expectations -- -W clippy::manual_let_else -W clippy::single_match_else
```
=> Fix `manual_let_else` and `single_match_else` lints

bindgen-tests/tests/expectations/tests/derive-bitfield-method-same-name.rs, bindgen-tests/tests/expectations/tests/derive-debug-bitfield.rs, bindgen-tests/tests/expectations/tests/derive-debug-function-pointer.rs, bindgen/codegen/impl_debug.rs
Generates more optimized code per https://rust-lang.github.io/rust-clippy/master/index.html#format_collect
=> Improve debug str generator

bindgen-integration/src/lib.rs, bindgen-tests/tests/expectations/tests/issue-544-stylo-creduce-2.rs, bindgen-tests/tests/expectations/tests/non-type-params.rs, bindgen-tests/tests/expectations/tests/nsBaseHashtable.rs, bindgen-tests/tests/expectations/tests/partial-specialization-and-inheritance.rs, bindgen-tests/tests/expectations/tests/size_t_template.rs, bindgen-tests/tests/expectations/tests/va_list_aarch64_linux.rs, bindgen-tests/tests/headers/va_list_aarch64_linux.h, bindgen/codegen/helpers.rs, bindgen/codegen/mod.rs, bindgen/codegen/struct_layout.rs, bindgen/features.rs, bindgen/ir/context.rs, bindgen/ir/ty.rs
Fixes #2845. Wrapping the generated array in a struct ensures that it is passed in an FFI-safe way. This does assume that the calling convention for structs is only dependent on size and alignment, but that seems like an improvement on using a type whose calling convention is not considered stable at all. Padding bytes (etc.) have been excluded from this treatment.
=> Wrap the array representation of opaque types in a #[repr(C)] struct

CHANGELOG.md, bindgen/callbacks.rs, bindgen/codegen/mod.rs
In my case, I want to make a field private and wrap it behind an accessor function that makes the field `unsafe` to access. I need the field's type in order to make this decision correctly. In some cases a type name is not available and I am fine with that.
=> Add `FieldInfo::field_type_name`

bindgen-tests/tests/quickchecking/src/fuzzers.rs, bindgen/callbacks.rs, bindgen/clang.rs, bindgen/codegen/helpers.rs, bindgen/codegen/mod.rs, bindgen/codegen/struct_layout.rs, bindgen/extra_assertions.rs, bindgen/ir/analysis/has_vtable.rs, bindgen/ir/comp.rs, bindgen/ir/context.rs, bindgen/ir/function.rs, bindgen/ir/item.rs, bindgen/ir/objc.rs, bindgen/ir/template.rs, bindgen/ir/traversal.rs, bindgen/ir/ty.rs, bindgen/ir/var.rs, bindgen/lib.rs, bindgen/options/cli.rs, bindgen/regex_set.rs
First ran this
```
cargo clippy --fix --workspace --exclude bindgen-integration --exclude tests_expectations -- -W clippy::doc_markdown
```
followed by a bunch of manual fixes.
=> Fix some markdown

.github/workflows/bindgen.yml, ci/test.sh
This means that we no longer test amd64 on macos but there's not much we can do to be honest.
=> Use `macos-latest` on CI

ci/test.sh
The kernel merge window has finished, so let's upgrade to the first release candidate tag so that `bindgen` CI tests the latest additions/changes.
=> ci: Move forward Rust for Linux version to v6.13-rc1

book/src/requirements.md
=> Miscelaneous fixes to the requirement section of the book

.github/workflows/bindgen.yml, bindgen/options/cli.rs
This regressed again in #2984. Partially revert d75fe271418e and 42a86e288c43 and restore the previous behavior.
Fixes: https://github.com/rust-lang/rust-bindgen/issues/3037
Fixes: https://github.com/rust-lang/rust-bindgen/issues/3039
=> Unbreak shell completion and --version without header

Cargo.toml
This crate started using  `proc_macro2::Literal::c_string` (in #2996) which was added to `proc-macro2` in [1.0.80](https://github.com/dtolnay/proc-macro2/releases/tag/1.0.80). This PR bumps the version requirement for `proc-macro2` to reflect that.
=> Update `proc-macro2` version requirement to `1.0.80`

bindgen/features.rs
These traits are useful to get expressions like `RustTarget::stable(82, 0).unwrap()` to build, as `unwrap()` requires such a `Result` to implement `Debug`. The equality comparison traits may also be useful in cases where pattern matching the enum variants through e.g. `matches!` or match expressions is deemed less stylish. The `Hash` trait is also derived in case anyone wants to put these variants into a hash table based data structure.
=> Derive `Debug` and eq. comparison traits for `InvalidRustTarget` enum

book/src/non-system-libraries.md
This PR addresses and removes the usage of a deprecated constant in the documentation example.
Specifically, the deprecated `bindgen::CargoCallbacks` constant was replaced with the correct `bindgen::CargoCallbacks::new()` in the docs example.
=> Fix deprecated constant in docs example

.github/workflows/bindgen.yml, Cargo.toml, bindgen-tests/tests/parse_callbacks/item_discovery_callback/mod.rs, bindgen-tests/tests/quickchecking/src/bin.rs, bindgen-tests/tests/tests.rs, bindgen/clang.rs, bindgen/codegen/mod.rs, bindgen/ir/context.rs, bindgen/ir/function.rs, bindgen/ir/item.rs, bindgen/ir/ty.rs, bindgen/lib.rs, bindgen/time.rs
Added all detected pedantic lints, and allowed them all to keep track of them because some should be fixed.  Also fixed a few minor simple ones.
Logic change:  now files with `.hpp`, `.hxx`, `.hh`, and `.h++` extensions will work even if the extension is not lowercase
=> Multiple minor lint fixes

bindgen/lib.rs
This fixes the issue with c-string literals which require edition 2021. Now the edition is automatically computed if not specified.
Fixes #3047
=> Use appropriate `rustfmt --format ...` param

bindgen-tests/tests/expectations/tests/abi-override.rs, bindgen-tests/tests/expectations/tests/mangling-win32.rs, bindgen-tests/tests/headers/abi-override.h, bindgen-tests/tests/headers/mangling-win32.hpp
Seems like recent compiler changes no longer allow invalid calling conventions
=> CI fix - calling convention tests

bindgen/lib.rs
Instead of using the last registered callback, iterate through all callbacks and use the last one that was actually implemented and returned `Some()`.
This is essential when users register more than one parse callback.
=> process_comment: Use last defined callback

.github/workflows/publish.yml
This fixes an issue introduced in #3041 - the `publish` workflow runs every time `release` workflow runs, but since 3041, release workflow also runs in a "testing" mode - thus causing failed publish (due to a missing github token). This could also result in an accidental crate publishing
=> Fix CI to NOT run publish on every pull request

bindgen/codegen/mod.rs, bindgen/ir/context.rs, bindgen/ir/objc.rs, bindgen/lib.rs
* convert `assert!` to `assert_eq!` and `assert_ne!` where possible
* remove unneeded parenthesis
=> use `assert_eq!` and `_ne!`, remove uneeded parens

bindgen-tests/tests/expectations/tests/keywords.rs, bindgen-tests/tests/headers/keywords.h, bindgen/ir/context.rs
This addresses https://github.com/rust-lang/rust-bindgen/issues/3093
=> Mangle identifiers named 'gen' now that it's a reserved keyword

bindgen-tests/tests/expectations/tests/dynamic_loading_template.rs, bindgen-tests/tests/expectations/tests/dynamic_loading_with_allowlist.rs, bindgen-tests/tests/expectations/tests/dynamic_loading_with_blocklist.rs, bindgen-tests/tests/expectations/tests/dynamic_loading_with_class.rs, bindgen/codegen/dyngen.rs, bindgen/codegen/mod.rs
Dynamic library codegen generates code trying to load symbols using the name exposed in bindings instead of the overriden link name or mangled name.
[Note that libloading::Library::get does not mangle the name for you](https://docs.rs/libloading/latest/libloading/struct.Library.html#method.get)
1. When generating bindings for a dynamically loaded library (behaviour available by calling `dynamic_library_name` on the builder), the symbol names used in the generated `__library.get("XXX")` calls aren't the mangled link name as one might expect, but instead the bindings name. This behaviour by chance works with C-style exports, but is incorrect with mangled symbols (e.g. C++ exports) or when a user overrides the name of an item.
2. In addition, the link_name attribute is sometimes erroneously …
=> Use link_name for dynamic library loading

bindgen/ir/item.rs
We already tried `location.raw_comment()` first. 
Originally the last `or_else` branch debug printed `location.raw_comment()`, but the print was removed in c94367c8e9607d3b6d5cf80f0c589971dca40f7c.
=> Remove useless fallback

bindgen/codegen/mod.rs
Forward declarations never have a known layout, so the warning makes no sense in that case.
=> Remove warning for opaque forward declarations

bindgen-tests/tests/expectations/tests/char16_t.rs, bindgen-tests/tests/headers/char16_t.hpp, bindgen/codegen/helpers.rs, bindgen/ir/context.rs, bindgen/ir/int.rs, bindgen/options/cli.rs, bindgen/options/mod.rs
With a new command-line option, this ensures that char16_t is distinct from uint16_t in generated bindings. On some platforms these are distinct types, so it can be important for downstream post processors to spot the difference.
See the documentation on the new command-line option for expected behavior and usage here.
Part of https://github.com/google/autocxx/issues/124.
=> Distinguish char16_t.

bindgen-tests/tests/parse_callbacks/item_discovery_callback/header_item_discovery.h, bindgen-tests/tests/parse_callbacks/item_discovery_callback/mod.rs, bindgen/callbacks.rs, bindgen/codegen/mod.rs
ParseCallbacks previously reported structs but not enums. Enhance it to do so. At the moment, little information is provided about enums - but bindgen doesn't handle (rare) anonymous enums so this seems the right amount of information to report. At the moment, effectively this just provides a mapping between name and DiscoveredItemId.
One of a number of PRs I'll be raising for https://github.com/google/autocxx/issues/124.
In future PRs I'll be hoping to add further callbacks which report more information based on DiscoveredItemId, so having the DiscoveredItemId for each enum is an important pre-requisite.
=> Report enums in ParseCallbacks.

bindgen-tests/tests/expectations/tests/class_with_enum.rs, bindgen-tests/tests/expectations/tests/special-members.rs, bindgen-tests/tests/headers/class_with_enum.hpp, bindgen-tests/tests/headers/special-members.hpp
These files aspects of bindgen behavior which may not be generally useful to most consumers but are more important to downstream postprocessors such as autocxx.
One of them tests enums embedded within classes, and the other tests various types of C++ constructor.
A later PR will aim to add callbacks indicating which type of C++ constructor it is, but for now, this is just a test to ensure they're all generated OK.
Part of https://github.com/google/autocxx/issues/124.
=> Add extra tests.

bindgen/codegen/helpers.rs, bindgen/ir/int.rs, bindgen/options/mod.rs
Follow up from #3135. Part of https://github.com/google/autocxx/issues/124
=> Improve comments and docs relating to char16_t.

bindgen-tests/tests/expectations/tests/uncallable_functions.rs, bindgen-tests/tests/headers/uncallable_functions.hpp, bindgen/codegen/mod.rs, bindgen/ir/function.rs, bindgen/options/cli.rs, bindgen/options/mod.rs
Downstream code generators may need to know about the existence of certain C++ functions even if those functions can't be called. This is counterintuitive but:
* A type can't even be allocated if it contains pure virtual functions or if its constructor is private.
* A type may not be relocatable if it contains a deleted move constructor.
This PR provides command line options to reveal the existence of these functions. Subsequent PRs will announce their special status using the ParseCallbacks mechanism.
Part of https://github.com/google/autocxx/issues/124.
=> Options to generate uncallable C++ functions.

bindgen-tests/tests/expectations/tests/opencl_vector.rs, bindgen-tests/tests/headers/opencl_vector.h, bindgen/ir/ty.rs
The SIMD header provided by Apple uses [ext_vector_type](https://clang.llvm.org/docs/LanguageExtensions.html#vectors-and-extended-vectors) to define vectors. Previously bindgen would generate an opaque type as seen [here](https://github.com/gfx-rs/metal-rs/blob/cce2b486dd39d19ba232e823148ee2c557e97e62/examples/texture/src/main.rs#L112). The vector extension seems to behave similar to the already defined vector, so it doesn't look like using that case overlooks anything.
=> Add support for vectors that use "ext_vector_type" 

bindgen/lib.rs
=> Convert *-apple-ios-sim to *-apple-ios-simulator in rust_to_clang_target

bindgen-tests/tests/expectations/tests/bitfield-enum-basic.rs, bindgen-tests/tests/expectations/tests/bitfield-enum-repr-c.rs, bindgen-tests/tests/expectations/tests/bitfield-enum-repr-transparent.rs, bindgen-tests/tests/expectations/tests/enum-default-bitfield.rs, bindgen-tests/tests/expectations/tests/enum-doc-bitfield.rs, bindgen-tests/tests/expectations/tests/issue-1198-alias-rust-bitfield-enum.rs, bindgen-tests/tests/expectations/tests/issue-1435.rs, bindgen-tests/tests/expectations/tests/newtype-enum.rs, bindgen/codegen/mod.rs
Gather all the enum variants and let the builder generate everything at once.
This allows us to simplify some logic and makes the code more readable, by putting the actual code generation close together in the build method.
For users, the main benefit is that Newtype enums now only have a single impl block, instead of one impl block per enum variant.
=> Refactor enum generation

bindgen-tests/tests/expectations/tests/union_with_zero_sized_array.rs, bindgen-tests/tests/headers/union_with_zero_sized_array.h, bindgen/codegen/struct_layout.rs
=> Fix union layout when it contains 0 sized array.

.github/workflows/bindgen.yml, ci/test.sh
See individual commits.
Fixes: https://github.com/rust-lang/rust-bindgen/issues/3188
=> ci: use stable again moving forward Rust for Linux job

.github/workflows/bindgen.yml, bindgen-tests/build.rs, bindgen-tests/tests/parse_callbacks/item_discovery_callback/mod.rs, bindgen-tests/tests/quickchecking/src/fuzzers.rs, bindgen-tests/tests/tests.rs, bindgen/codegen/mod.rs, bindgen/codegen/serialize.rs, bindgen/codegen/struct_layout.rs, bindgen/ir/analysis/derive.rs, bindgen/ir/comp.rs, bindgen/ir/context.rs, bindgen/ir/dot.rs, bindgen/ir/item.rs, bindgen/lib.rs
* make bindgen faster - converted a lot of string format allocations to direct writes
* turns out clippy was part of CI, but was not used to enforce anything
* clippy should not use nightly channel
* check-cfg has been stabilized since 1.80, so no need for a separate CI job
* rustfmt is the only job requiring nightly
Also, I think we should remove installation of the stable rust - github runners have been very good at keeping rust version up to date, no need to waste time for each job to install it.
=> chore: fix last clippy lints and enforce in CI

bindgen/options/cli.rs
Noticed today when I ran `bindgen --help` that the backticks around `enum` on the descriptions for the `--with-derive-custom-enum` and `--with-attribute-custom-enum` options and improperly enclosed. This two-character PR fixes that.
=> Minor CLI documentation typo when running `bindgen --help`

ci/test.sh
A hopefully routine upgrade to Linux v6.15-rc4!
This matches the one getting merged for Rust's CI.
=> ci: Move forward Rust for Linux version to v6.15-rc4

bindgen-integration/build.rs, bindgen-integration/cpp/Test.h, bindgen-integration/src/lib.rs, bindgen/callbacks.rs, bindgen/ir/var.rs
This a rerun of PR #2119. The goal is to provide a callback to allow modifying the tokens when parsing macros to handle values that are non-standard. As described in the original PR, I have several header files which contains things like:
```c
#define FLAG_BITS            8:10
```
In my specific case, these values are later on used within a ternary operator. This PR enables transforming those values into a valid integer that generates a valid integer constant.
=> Allow modifying macro tokens at parse time

bindgen/Cargo.toml
Hello, Foxie here. I was reading bindgen's `Cargo.toml` file while I'm searching workaround for unrelated problem and found comment indicating `which-rustfmt` feature should be removed by 0.70 release but its already 0.71.1 and it persists.
Because it is 0.71.1 already, I do think this removal was missed as I couldn't find any open/closed PR which mentioned "Remove which-rustfmt".
=> Remove unused which-rustfmt feature

ci/test.sh
Another hopefully routine upgrade to Linux v6.16-rc1, just released.
=> ci: Move forward Rust for Linux version to v6.16-rc1

bindgen-tests/build.rs, bindgen-tests/tests/tests.rs, bindgen/ir/analysis/has_destructor.rs, bindgen/ir/analysis/has_vtable.rs, bindgen/ir/context.rs, bindgen/ir/function.rs, bindgen/lib.rs, bindgen/options/mod.rs, clippy.toml
=> chore: Do a clippy pass.

bindgen/callbacks.rs
Add common traits like `Debug` to the callback objects like `ItemKind` and `ItemInfo`.
=> feat: add Debug,Clone,Eq traits to callback objects

Cargo.lock, bindgen/codegen/mod.rs, bindgen/ir/context.rs, bindgen/ir/ty.rs
* `clap` is held back at 4.4 to remain compatible with MSRV 1.70.
* Everything else is current within semver requirements.
=> cargo update

bindgen-tests/tests/parse_callbacks/item_discovery_callback/mod.rs, bindgen/callbacks.rs, bindgen/codegen/mod.rs
[ This is a takeover of #3141, resolving merge conflicts. Original PR text below. ]
Builds on top of #3140.
This provides the source code location of an item in the existing item discovery callback. See f607994c3ab87ee754ce7a9138564c2a22b6bb92 for discussion of whether it's OK to break compatibility like this.
Part of https://github.com/google/autocxx/issues/124
=> Include source code location in discovery callback

bindgen/options/cli.rs
s/coma/comma/ in the strings added by PR #2866.
=> Fix typos in the descriptions of a few flags

triagebot.toml
As per the [related Zulip thread](https://rust-lang.zulipchat.com/#narrow/channel/469104-wg-bindgen/topic/GH.20rustbot.20configuration.20in.20rust-bindgen/with/533464084).
=> Configure an assign section in triagebot.toml to allow rustbot to assign PRs

bindgen/ir/comp.rs, bindgen/lib.rs
* fix error messages missing spaces
* simplify rustfmt_path()
=> chore: minor cleanup

bindgen-tests/tests/expectations/tests/nested-class-field.rs, bindgen-tests/tests/headers/nested-class-field.hpp, bindgen/clang.rs, bindgen/ir/comp.rs
Fixes #3275 
Fixes #3264
Closes #3277 (included here squashed)
=> Fix type completeness issues with clang 22

bindgen-tests/tests/expectations/tests/constify-module-enums-basic.rs, bindgen-tests/tests/expectations/tests/constify-module-enums-namespace.rs, bindgen-tests/tests/expectations/tests/constify-module-enums-shadow-name.rs, bindgen-tests/tests/expectations/tests/constify-module-enums-simple-alias.rs, bindgen-tests/tests/expectations/tests/constify-module-enums-simple-nonamespace.rs, bindgen-tests/tests/expectations/tests/constify-module-enums-types.rs, bindgen-tests/tests/expectations/tests/default-enum-style-constified-module.rs, bindgen-tests/tests/expectations/tests/empty-enum.rs, bindgen-tests/tests/expectations/tests/enum-default-bitfield.rs, bindgen-tests/tests/expectations/tests/enum-default-consts.rs, bindgen-tests/tests/expectations/tests/enum-default-module.rs, bindgen-tests/tests/expectations/tests/enum-default-rust.rs, bindgen-tests/tests/expectations/tests/enum-doc-mod.rs, bindgen-tests/tests/expectations/tests/enum-no-debug-rust.rs, bindgen-tests/tests/expectations/tests/issue-1198-alias-rust-const-mod-bitfield-enum.rs, bindgen-tests/tests/expectations/tests/issue-1198-alias-rust-const-mod-enum.rs, bindgen-tests/tests/expectations/tests/issue-1488-enum-new-type.rs, bindgen-tests/tests/headers/constify-module-enums-types.hpp, bindgen/codegen/mod.rs
=> codegen: Fix typedefs inside constified modules.

bindgen-tests/tests/expectations/tests/issue-2618.rs, bindgen-tests/tests/headers/issue-2618.h, bindgen/clang.rs, bindgen/ir/int.rs, bindgen/ir/var.rs
=> Allow constant expressions that doesn't fit in i64.
