.travis.yml
as requested in https://github.com/servo/rust-bindgen/pull/3
=> Add homu webhook

README.md
=> readme: Add a bit more up-to-date information.

README.md
=> Add description of how to run the tests to README.md

README.md
=> Add documentation for building with ports and LLVM 3.9

src/bin/bindgen.rs
=> Remove usage for flags that no longer exist

src/ir/comp.rs, src/ir/context.rs, src/ir/ty.rs
=> Removed TypeResolver

src/lib.rs
=> Remove dtor attrs

bindgen_plugin/src/bgmacro.rs, src/lib.rs
=> Remove the unused fail_on_unknown_type option

src/bin/bindgen.rs, src/lib.rs
=> Remove the unused gen_bitfield_methods option

src/bin/bindgen.rs, src/lib.rs
=> Remove unused rust enums option

src/bin/bindgen.rs, src/lib.rs, tests/headers/class_with_typedef.hpp, tests/headers/crtp.hpp, tests/headers/vtable_recursive_sig.hpp
=> Remove the ignored and unused --no-type-renaming flag and option

src/bin/bindgen.rs, src/lib.rs, tests/headers/class_with_typedef.hpp, tests/headers/crtp.hpp, tests/headers/vtable_recursive_sig.hpp
=> Remove the unused class_constants option

bindgen_plugin/src/bgmacro.rs, src/bin/bindgen.rs, src/lib.rs, tests/headers/class_with_typedef.hpp, tests/headers/crtp.hpp, tests/headers/vtable_recursive_sig.hpp
=> Remove unused override enum ty option

src/ir/comp.rs
cargo test --features llvm_stable successful
=> s/type_resolver/ctx/ in src/ir/comp.rs

src/ir/item.rs, src/lib.rs, src/parse.rs, src/regex_set.rs
=> Document the `regex_set` module

src/clang.rs
I built it and ran the test, and they all pass. Not sure what else there is to test for.
Fixes #145.
=> Implement Drop for Diagnostic

tests/tests.rs
=> Fix a small typo and expand batching comment

src/ir/context.rs
It turns out that we can end up overwriting existing replacements. This commit embeds the assumption that the first replacement definition is the correct one, and warns on all attempts to overwrite the first replacement definition with a new one. Additionally, it adds some debug logging about replacements.
This actually isn't enough to fix the test case in #89, but it is a good start.
r? @emilio
=> Do not overwrite existing replacements

src/bin/bindgen.rs, src/clang.rs, src/lib.rs
PR to address #152 for logging libclang version for debugging purposes. Let me know if it needs tweaking!
=> Add logging of Clang version

src/clang.rs
=> Remove unused template_arg_kind

src/ir/item.rs, src/ir/ty.rs
Just a couple things I have found helpful when debugging, and should probably exist either way.
r? @emilio
=> Useful little helpers for Item and Type

libbindgen/src/codegen/mod.rs, libbindgen/src/ir/context.rs, libbindgen/src/ir/module.rs, libbindgen/src/lib.rs, libbindgen/tests/expectations/tests/anon_union.rs, libbindgen/tests/expectations/tests/crtp.rs, libbindgen/tests/expectations/tests/forward-inherit-struct-with-fields.rs, libbindgen/tests/expectations/tests/forward-inherit-struct.rs, libbindgen/tests/expectations/tests/vtable_recursive_sig.rs
=> ir: Rework how we discover children of modules.

libbindgen/Cargo.toml
=> Bump version.

bindgen/src/main.rs, libbindgen/src/codegen/mod.rs, libbindgen/src/ir/context.rs, libbindgen/src/ir/ty.rs, libbindgen/src/regex_set.rs
This fix https://github.com/servo/rust-bindgen/issues/368
=> Replace all non-fatal `error!`s with `warn!`s

libbindgen/src/clang.rs, libbindgen/src/ir/var.rs, libbindgen/tests/expectations/tests/constant-evaluate.rs, libbindgen/tests/headers/constant-evaluate.h
=> ir: Evaluate constant strings too.

CONTRIBUTING.md, Cargo.toml, README.md
=> Small cargo and docs clean ups

.gitignore, Cargo.lock
Fixes #421 
r? @emilio or @emilio
=> Add Cargo.lock file

src/clang.rs
This improves the situation slightly, but even `clang_Type_getNumTemplateArgs` doesn't work for most templates...
r? @emilio
=> Make Cursor::num_template_args slightly more reliable

Cargo.lock, Cargo.toml
See https://bugzilla.mozilla.org/show_bug.cgi?id=1336655
r? @emilio @fitzgen
=> Don't publish tests

Cargo.toml
=> Also exclude the test crate from packaging.

src/ir/ty.rs
I didn't add an extra test module, since I couldn't find any precedents in the project.
Feedback welcome!
=> ty: add tests for Type.is_invalid_named_type() (#460)

src/clang.rs
=> Clang 3.5 support

src/clang.rs, src/ir/comp.rs
=> ir: Remove unused call to clang_Cursor_isAnonymous.

src/lib.rs
=> lib: Simplify the libclang setup.

Cargo.lock, Cargo.toml
There've been no breaking changes in v0.22.0..HEAD, only a bunch of bugfixes.
=> Bump to v0.22.1

src/log_stubs.rs, src/main.rs
The build was broken without default features
=> Run without logging feature

CONTRIBUTING.md, src/ir/dot.rs, tests/test-one.sh
A couple things that I've found helpful for iterative debugging.
r? @emilio
=> Little helper stuff

src/options.rs
I tried to make the wording more consistent and easier to read.
=> Clarify wording of command line help

Cargo.lock, Cargo.toml, src/main.rs
=> Remove rustc-serialize dependency.

Cargo.lock, Cargo.toml
After all the huge work @fitzgen has been doing diagnosing stylo issues, we seem ready to try again!
Also, a lot of issues have been fixed lately.
=> Breaking version bump.

.github/ISSUE_TEMPLATE.md
=> Fix issue template typo

Cargo.lock, Cargo.toml
Need to publish a new version so I can rely on the MacOS mangling fix for my smup branch.
r? @emilio
=> Bump to version 0.25.2

CONTRIBUTING.md
Filling in some obvious gaps from https://github.com/nrc/dev-tools-team/blob/master/contribution/checklist.md
r? @emilio 
cc @rust-lang/dev-tools : would anyone like to review our CONTRIBUTING.md file in general? (and our contribution workflow?) (and probably outside of this PR)
=> Going through the rust dev tools contributing checklist

ci/deploy-book.sh, ci/test-book.sh
=> Pin the mdbook version for CI.

src/codegen/mod.rs
=> Remove whitelisted_items as arg to codegen funcs

src/ir/analysis/derive_debug.rs, src/ir/analysis/has_vtable.rs, src/ir/analysis/mod.rs
=> Pull out the loop that generates dependency map into its own function.

src/options.rs
=> Report what the unknown generate item was when parsing `--generate`

src/ir/analysis/derive_debug.rs, src/ir/derive.rs, src/ir/function.rs, src/ir/layout.rs
=> Clean up trivially derive debug

tests/headers/enum_explicit_type.hpp
=> fix test for explicitly typed enum on aarch64

CONTRIBUTING.md
=> Mention the test expectations in CONTRIBUTING.md

CONTRIBUTING.md
=> LD_LIBRARY_PATH is unnecessary; LIBCLANG_PATH is enough

src/lib.rs, src/options.rs
See #949 for context and motivation.
r? @emilio
=> Document that not recursively whitelisting is dangerous

README.md
=> Add links to `impl period` blog post and gitter.im

src/codegen/mod.rs, src/ir/comp.rs
As per https://github.com/rust-lang-nursery/rust-bindgen/pull/1012#discussion_r140378893
r? @fitzgen
=> Generate base names upon construction

src/codegen/mod.rs, src/ir/comp.rs, src/ir/context.rs
=> Deanonymize fields

book/src/SUMMARY.md, book/src/cpp.md, book/src/faq.md
I feel like we've had to anwer these questions multiple times... Good to be able to just point people to these canonical answers instead of repeating ourselves.
r? @emilio
=> Create an FAQ section in the book

CONTRIBUTING.md
=> Add @pepyakin to the list of reviewers 🎉 🎉 🎉

src/codegen/helpers.rs, src/codegen/mod.rs, tests/expectations/tests/bitfield-32bit-overflow.rs, tests/expectations/tests/bitfield-method-same-name.rs, tests/expectations/tests/bitfield_align.rs, tests/expectations/tests/bitfield_align_2.rs, tests/expectations/tests/bitfield_method_mangling.rs, tests/expectations/tests/derive-bitfield-method-same-name.rs, tests/expectations/tests/derive-debug-bitfield.rs, tests/expectations/tests/derive-partialeq-bitfield.rs, tests/expectations/tests/jsval_layout_opaque.rs, tests/expectations/tests/jsval_layout_opaque_1_0.rs, tests/expectations/tests/layout_align.rs, tests/expectations/tests/layout_eth_conf.rs, tests/expectations/tests/layout_eth_conf_1_0.rs, tests/expectations/tests/layout_mbuf.rs, tests/expectations/tests/layout_mbuf_1_0.rs, tests/expectations/tests/only_bitfields.rs, tests/expectations/tests/struct_with_bitfields.rs, tests/expectations/tests/union_bitfield.rs, tests/expectations/tests/union_bitfield_1_0.rs, tests/expectations/tests/union_with_anon_struct_bitfield.rs, tests/expectations/tests/union_with_anon_struct_bitfield_1_0.rs, tests/expectations/tests/weird_bitfields.rs
=> Emit hex bitfield masks

Cargo.lock, Cargo.toml
Again, just fixes, and I got FF to build with #1124.
=> Minor version bump.

src/lib.rs
Fix for a comment in #1092.
r? @fitzgen
=> Don't unwrap header metadata

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Bump to 0.32.1 minor release

Cargo.lock, Cargo.toml
=> Bump libclang.

src/ir/context.rs
=> Improve error message when libclang fails

src/ir/context.rs
r? @emilio 
I'll need to install `rustfmt` before I do anything more elaborate
=> adds 'async' to list of matches in 'rust_mangle'

Cargo.lock, Cargo.toml, src/ir/var.rs, tests/headers/issue-674-1.hpp, tests/headers/issue-674-2.hpp, tests/headers/issue-674-3.hpp
This lands #1390 with some test fixes and a clang-sys update.
Part of #1407.
Closes #1390.
=> Update some crates

book/src/tutorial-3.md
Just a very small fix for the tutorial.
This is my first PR. Hope everything is ok.
=> Small fix in tutorial

src/lib.rs
=> Add comments about regex usage in {white|black}list functions

src/ir/comp.rs, tests/expectations/tests/packed-bitfield.rs, tests/headers/divide-by-zero-in-struct-layout.h, tests/headers/packed-bitfield.h
=> ir: Account for packedness when computing bitfield sizes.

book/src/requirements.md
I was having trouble figuring out how to install Clang for bindgen, and this helped right away.
=> Update requirements.md with Mingw64 install instruction

src/lib.rs
Feature was originally introduced in pull-request #1537
=> Document BINDGEN_EXTRA_CLANG_ARGS env variable

src/codegen/mod.rs, tests/expectations/tests/issue-1488-enum-new-type.rs, tests/expectations/tests/issue-1488-options.rs, tests/expectations/tests/issue-1488-template-alias-new-type.rs
=> Derive traits for newtype aliases

CONTRIBUTING.md, src/lib.rs, tests/tests.rs
=>  tests: Check that command_line_args round-trips.

csmith-fuzzing/predicate.py
This happened to be useful for me...
=> Allow grepping bindings for multiple patterns.

src/ir/comp.rs
`cursor` here points at the type's declaration, while `cur` points at the field declaration currently being visited. This meant `is_mutable` was always being set to `false`.
AFAICT, the information about whether fields are declared `mutable` isn't actually used anywhere yet, so no changes to the tests.
r? @emilio
=> Look at correct cursor when checking field mutability.

.github/workflows/bindgen.yml, .github/workflows/deploy-book.yml, book/book.toml
This should be better, simpler, and faster.
=> ci: update mdbook.

book/src/objc.md
=> From Nullablibility to Nullability

tests/expectations/build.rs, tests/expectations/tests/bitfield_align_2.rs, tests/expectations/tests/convert-cpp-comment-to-rust.rs, tests/expectations/tests/derive-custom.rs, tests/expectations/tests/enum_explicit_type_constants.rs, tests/expectations/tests/issue-739-pointer-wide-bitfield.rs, tests/expectations/tests/use-core.rs, tests/headers/bitfield_align_2.h, tests/headers/convert-cpp-comment-to-rust.hpp, tests/headers/derive-custom.h, tests/headers/enum_explicit_type_constants.hpp, tests/headers/issue-739-pointer-wide-bitfield.h, tests/headers/use-core.h, tests/tests.rs
This PR fixes some tests and the testing infrastructure so that tests can be run on windows.
touches on #1009 and similar issues, but does not fix the underlying issue.
=> Fix tests on Windows

Cargo.lock
=> Update `which` crate to 4.2.2

src/clang.rs, src/codegen/mod.rs, src/ir/analysis/derive.rs, src/ir/annotations.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/layout.rs, src/ir/ty.rs
Some changes fixing clippy warnings
=> Address clippy lints

src/ir/context.rs, src/ir/traversal.rs
Fixes https://github.com/rust-lang/rust-bindgen/issues/2261
=> Replace the `TraversalPredicate` trait with an alias type

src/codegen/mod.rs, src/codegen/struct_layout.rs, src/ir/comp.rs
This doesn't change behavior but makes the code make more sense.
=> codegen: Implement manuallydrop fields better.

tests/expectations/tests/inner-typedef-gh422.rs, tests/headers/inner-typedef-gh422.hpp
GitHub issue 422 was fixed but needs a test. This was quick.
https://github.com/rust-lang/rust-bindgen/issues/422
Closes #422 
cc. @pvdrz
=> Test for #422

book/src/faq.md
Fixes https://github.com/rust-lang/rust-bindgen/issues/2311
=> Add FAQ about custom targets

.github/workflows/bindgen.yml, CHANGELOG.md, Cargo.lock
Fixes https://github.com/rust-lang/rust-bindgen/issues/2360
=> Bump `clang-sys` version

book/src/SUMMARY.md, book/src/code-formatting.md, book/src/faq.md
Fixes https://github.com/rust-lang/rust-bindgen/issues/2348
=> Document how to format code

Cargo.lock, bindgen-tests/tests/expectations/Cargo.toml, bindgen-tests/tests/quickchecking/Cargo.toml, bindgen-tests/tests/quickchecking/src/lib.rs
=> Remove `tempfile` dependency to fix vulnerability

bindgen/ir/annotations.rs
Link broken. Fixed it and used modern style
=> Fix broken link to doxygen docblocks

CHANGELOG.md, bindgen-tests/tests/expectations/tests/generated/wrap_static_fns.c, bindgen/codegen/serialize.rs
Fixes https://github.com/rust-lang/rust-bindgen/issues/2442
=> Avoid emitting old-style C declarations

CHANGELOG.md, Cargo.lock, bindgen-cli/Cargo.toml, bindgen-cli/options.rs, bindgen-integration/build.rs, bindgen-tests/tests/tests.rs, bindgen/Cargo.toml, bindgen/lib.rs, book/src/code-formatting.md, book/src/faq.md
=> Add `prettyplease` support

CHANGELOG.md
=> Typo: Update CHANGELOG.md

CHANGELOG.md, Cargo.lock, bindgen/Cargo.toml, bindgen/codegen/mod.rs, bindgen/lib.rs
This is a new major version which changes the API a bit, and as such requires some code changes too.
=> Update the bitflags to 2.2.1.

book/src/non-system-libraries.md
=> replace inappropriate markup

.github/workflows/bindgen.yml
=> remove obsolete comment

CHANGELOG.md, Cargo.lock, bindgen-cli/Cargo.toml, bindgen/Cargo.toml
@emilio, you can merge this early tomorrow if we didn't miss anything.
Blocked by: https://github.com/rust-lang/rust-bindgen/pull/2559
=> 0.66.1 release preparation

Cargo.lock, bindgen-tests/Cargo.toml, bindgen-tests/tests/tests.rs
second commit brings in many new deps... will happily remove if that's deemed too much
closes #2541
=> make expected-tests diff more pretty

CHANGELOG.md, bindgen-tests/tests/expectations/tests/abi-override.rs, bindgen-tests/tests/headers/abi-override.h, bindgen/ir/function.rs
=> account for system abi

bindgen/ir/ty.rs, bindgen/options/mod.rs
=> Make clippy happy

bindgen/options/mod.rs
=> Document non-generation of `size_t` definition

.github/workflows/bindgen.yml, .github/workflows/deploy-book.yml
Should of been part of 922655f33646b7a126f4c39fb7df60a122d7eb1b
=> we stopped building mdbook from source

book/book.toml
This is so it matches common search engines
=> make search less surprising

bindgen/options/mod.rs
=> Fix typo in cfg attribute

CHANGELOG.md, bindgen-tests/tests/expectations/tests/libclang-5/ptr32-has-different-size.rs, bindgen-tests/tests/expectations/tests/libclang-9/ptr32-has-different-size.rs, bindgen-tests/tests/expectations/tests/ptr32-has-different-size.rs, bindgen-tests/tests/headers/ptr32-has-different-size.h, bindgen/codegen/error.rs, bindgen/codegen/mod.rs
=> Check pointer size and emit opaque type if required

Cargo.lock, bindgen/Cargo.toml, bindgen/ir/comp.rs
It seems like https://github.com/fitzgen/peeking_take_while is not maintained any more and most projects depend on itertools anyways.
=> Replace peeking_take_while with itertools

.github/workflows/release.yml, CONTRIBUTING.md, Cargo.toml
This removes one step that was once needed to update cargo-dist
=> bump cargo-dist

CHANGELOG.md, bindgen-tests/tests/expectations/tests/anon_enum_allowlist_item.rs, bindgen-tests/tests/headers/anon_enum_allowlist_item.h, bindgen/ir/context.rs
=> Fix `--allowlist-item` so it doesn't ignore anon enums

CONTRIBUTING.md
This fixes a broken link and adds 2 missing entries.
=> CONTRIBUTING.md: Update toc

bindgen/codegen/mod.rs, bindgen/ir/analysis/sizedness.rs, bindgen/ir/analysis/template_params.rs, bindgen/ir/derive.rs, bindgen/ir/template.rs, bindgen/options/mod.rs
These are in `nightly` clippy.
=> Fix `clippy::doc_lazy_continuation` lints

.github/workflows/publish.yml
Reverts rust-lang/rust-bindgen#2887
=> Trigger the crates.io publish workflow automatically again

book/src/faq.md
Addresses https://github.com/rust-lang/rust-bindgen/issues/1748
=> Explain how to generate documentation for system headers

bindgen/clang.rs, bindgen/codegen/mod.rs, bindgen/ir/var.rs, bindgen/time.rs
```
cargo clippy --fix --workspace --exclude bindgen-integration --exclude tests_expectations -- -W clippy::cast_lossless
```
=> Fix `cast_lossless` lint

bindgen-tests/tests/expectations/tests/issue-3027.rs, bindgen-tests/tests/headers/issue-3027.hpp, bindgen/codegen/helpers.rs
=> Fix regression spotted at #3027

.github/workflows/bindgen.yml
=> Disable rust-for-linux test temporarily.

bindgen/log_stubs.rs
See https://doc.rust-lang.org/nightly/clippy/attribs.html#clippyformat_args
=> Mark all format-like macros for Clippy
